import { readFileSync, readdirSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dir = dirname(fileURLToPath(import.meta.url));
const VEC = process.env.VEC_DIR || join(__dir, '..', '.tests-cache', 'vectors');

const manifest = JSON.parse(readFileSync(join(VEC, 'manifest.json'), 'utf-8'));
const models = manifest.testModels;
const scalars = manifest.scalars;

function getReadMethod(type) {
  const map = {
    'int32': 'readInt32',
    'int64': 'readInt64',
    'uint32': 'readUint32',
    'uint64': 'readUint64',
    'float32': 'readFloat32',
    'float64': 'readFloat64',
    'string': 'readString',
    'bytes': 'readBytes',
    'bool': 'readBool',
  };
  return map[type] || 'readInt32';
}

function getWriteMethod(type) {
  const map = {
    'int32': 'writeInt32',
    'int64': 'writeInt64',
    'uint32': 'writeUint32',
    'uint64': 'writeUint64',
    'float32': 'writeFloat32',
    'float64': 'writeFloat64',
    'string': 'writeString',
    'bytes': 'writeBytes',
    'bool': 'writeBool',
  };
  return map[type] || 'writeInt32';
}

function toSnakeCase(name) {
  return name.replace(/([A-Z])/g, '_$1').toLowerCase().replace(/^_/, '');
}

let scalarCode = '';
for (const [name, info] of Object.entries(scalars)) {
  const snake = toSnakeCase(name);
  scalarCode += `
    // ${name}
    val mpData${snake} = File(Paths.get(VEC, "scalars", "${name}.mp").toUri()).readBytes()
    val r${snake} = MsgPackReader(mpData${snake})
    val val${snake} = r${snake}.${getReadMethod(info.type)}()
    val w${snake} = MsgPackWriter()
    w${snake}.${getWriteMethod(info.type)}(val${snake})
    File(Paths.get(OUT, "scalars", "${name}.mp").toUri()).writeBytes(w${snake}.toBytes())
    passed++
`;
}

let modelCode = '';
for (const model of models) {
  const snake = toSnakeCase(model);
  modelCode += `
    // ${model}
    val codec${model} = getCodec("${model}")
    // msgpack
    val mpData${model} = File(Paths.get(VEC, "${model}.msgpack").toUri()).readBytes()
    val r${model} = MsgPackReader(mpData${model})
    val obj${model} = codec${model}.decode(r${model})
    val w${model} = MsgPackWriter()
    codec${model}.encode(w${model}, obj${model})
    File(Paths.get(OUT, "${model}.msgpack").toUri()).writeBytes(w${model}.toBytes())
    passed++
    // json
    val jsonData${model} = File(Paths.get(VEC, "${model}.json").toUri()).readBytes()
    val rj${model} = JsonReader(jsonData${model})
    val objj${model} = codec${model}.decode(rj${model})
    val wj${model} = JsonWriter()
    codec${model}.encode(wj${model}, objj${model})
    File(Paths.get(OUT, "${model}.json").toUri()).writeBytes(wj${model}.toBytes())
    passed++
    // unformatted json
    val ufData${model} = File(Paths.get(VEC, "${model}.unformatted.json").toUri()).readBytes()
    val ru${model} = JsonReader(ufData${model})
    val obju${model} = codec${model}.decode(ru${model})
    val wu${model} = JsonWriter()
    codec${model}.encode(wu${model}, obju${model})
    File(Paths.get(OUT, "${model}.unformatted.json").toUri()).writeBytes(wu${model}.toBytes())
    passed++
    // gron
    val gronData${model} = File(Paths.get(VEC, "${model}.gron").toUri()).readBytes()
    val rg${model} = GronReader(gronData${model})
    val objg${model} = codec${model}.decode(rg${model})
    val wg${model} = GronWriter()
    codec${model}.encode(wg${model}, objg${model})
    File(Paths.get(OUT, "${model}.gron").toUri()).writeBytes(wg${model}.toBytes())
    passed++
`;
}

let codecSwitch = '';
for (const model of models) {
  codecSwitch += `        "${model}" -> ${model}Codec\n`;
}

const code = `// Generated by generate_emit_runner.mjs. DO NOT EDIT.
package emit_kotlin

import java.io.File
import java.nio.file.Paths
import specodec.*
import emit_gen.specodec_all_types.*

fun main() {
    val VEC = System.getenv("VEC_DIR")!!
    val OUT = System.getenv("OUT_DIR")!!
    File(OUT).mkdirs()
    File(Paths.get(OUT, "scalars").toUri()).mkdirs()

    var passed = 0
    var failed = 0

    // Scalar tests
${scalarCode}

    // Object tests
${modelCode}

    println("emit-kotlin: $passed passed, $failed failed")
    if (failed > 0) System.exit(1)
}

fun getCodec(name: String): SpecCodec<Any> = when (name) {
${codecSwitch}    else -> throw IllegalArgumentException("Unknown codec: $name")
}
`;

writeFileSync(join(__dir, 'src', 'main', 'kotlin', 'Main.kt'), code);
console.log(`Generated Main.kt with ${models.length} models + ${Object.keys(scalars).length} scalars`);