// Generated by @specodec/typespec-emitter-kotlin. DO NOT EDIT.
package all_types_arrays

import specodec.*

data class ArrString(
    val items: List<String>,
)

fun writeArrString(w: SpecWriter, obj: ArrString) {
    w.beginObject(1)
    w.writeField("items"); w.beginArray(obj.items.size)
        for (item in obj.items) { w.nextElement(); w.writeString(item) }
        w.endArray()
    w.endObject()
}

val ArrStringCodec: SpecCodec<ArrString> = SpecCodec(
    encode = { w, obj -> writeArrString(w, obj) },
    decode = { r ->
        var itemsVal: List<String> = emptyList()
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "items" -> itemsVal = run { val list = mutableListOf<String>(); r.beginArray(); while (r.hasNextElement()) { list.add(r.readString()) }; r.endArray(); list }
                else -> r.skip()
            }
        }
        r.endObject()
        ArrString(items = itemsVal)
    }
)

data class ArrInt32(
    val items: List<Int>,
)

fun writeArrInt32(w: SpecWriter, obj: ArrInt32) {
    w.beginObject(1)
    w.writeField("items"); w.beginArray(obj.items.size)
        for (item in obj.items) { w.nextElement(); w.writeInt32(item) }
        w.endArray()
    w.endObject()
}

val ArrInt32Codec: SpecCodec<ArrInt32> = SpecCodec(
    encode = { w, obj -> writeArrInt32(w, obj) },
    decode = { r ->
        var itemsVal: List<Int> = emptyList()
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "items" -> itemsVal = run { val list = mutableListOf<Int>(); r.beginArray(); while (r.hasNextElement()) { list.add(r.readInt32()) }; r.endArray(); list }
                else -> r.skip()
            }
        }
        r.endObject()
        ArrInt32(items = itemsVal)
    }
)

data class ArrBoolean(
    val items: List<Boolean>,
)

fun writeArrBoolean(w: SpecWriter, obj: ArrBoolean) {
    w.beginObject(1)
    w.writeField("items"); w.beginArray(obj.items.size)
        for (item in obj.items) { w.nextElement(); w.writeBool(item) }
        w.endArray()
    w.endObject()
}

val ArrBooleanCodec: SpecCodec<ArrBoolean> = SpecCodec(
    encode = { w, obj -> writeArrBoolean(w, obj) },
    decode = { r ->
        var itemsVal: List<Boolean> = emptyList()
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "items" -> itemsVal = run { val list = mutableListOf<Boolean>(); r.beginArray(); while (r.hasNextElement()) { list.add(r.readBool()) }; r.endArray(); list }
                else -> r.skip()
            }
        }
        r.endObject()
        ArrBoolean(items = itemsVal)
    }
)

data class ArrFloat64(
    val items: List<Double>,
)

fun writeArrFloat64(w: SpecWriter, obj: ArrFloat64) {
    w.beginObject(1)
    w.writeField("items"); w.beginArray(obj.items.size)
        for (item in obj.items) { w.nextElement(); w.writeFloat64(item) }
        w.endArray()
    w.endObject()
}

val ArrFloat64Codec: SpecCodec<ArrFloat64> = SpecCodec(
    encode = { w, obj -> writeArrFloat64(w, obj) },
    decode = { r ->
        var itemsVal: List<Double> = emptyList()
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "items" -> itemsVal = run { val list = mutableListOf<Double>(); r.beginArray(); while (r.hasNextElement()) { list.add(r.readFloat64()) }; r.endArray(); list }
                else -> r.skip()
            }
        }
        r.endObject()
        ArrFloat64(items = itemsVal)
    }
)

data class ArrBytes(
    val items: List<ByteArray>,
)

fun writeArrBytes(w: SpecWriter, obj: ArrBytes) {
    w.beginObject(1)
    w.writeField("items"); w.beginArray(obj.items.size)
        for (item in obj.items) { w.nextElement(); w.writeBytes(item) }
        w.endArray()
    w.endObject()
}

val ArrBytesCodec: SpecCodec<ArrBytes> = SpecCodec(
    encode = { w, obj -> writeArrBytes(w, obj) },
    decode = { r ->
        var itemsVal: List<ByteArray> = emptyList()
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "items" -> itemsVal = run { val list = mutableListOf<ByteArray>(); r.beginArray(); while (r.hasNextElement()) { list.add(r.readBytes()) }; r.endArray(); list }
                else -> r.skip()
            }
        }
        r.endObject()
        ArrBytes(items = itemsVal)
    }
)

data class ArrInt64(
    val items: List<Long>,
)

fun writeArrInt64(w: SpecWriter, obj: ArrInt64) {
    w.beginObject(1)
    w.writeField("items"); w.beginArray(obj.items.size)
        for (item in obj.items) { w.nextElement(); w.writeInt64(item) }
        w.endArray()
    w.endObject()
}

val ArrInt64Codec: SpecCodec<ArrInt64> = SpecCodec(
    encode = { w, obj -> writeArrInt64(w, obj) },
    decode = { r ->
        var itemsVal: List<Long> = emptyList()
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "items" -> itemsVal = run { val list = mutableListOf<Long>(); r.beginArray(); while (r.hasNextElement()) { list.add(r.readInt64()) }; r.endArray(); list }
                else -> r.skip()
            }
        }
        r.endObject()
        ArrInt64(items = itemsVal)
    }
)

data class ArrUint64(
    val items: List<ULong>,
)

fun writeArrUint64(w: SpecWriter, obj: ArrUint64) {
    w.beginObject(1)
    w.writeField("items"); w.beginArray(obj.items.size)
        for (item in obj.items) { w.nextElement(); w.writeUint64(item) }
        w.endArray()
    w.endObject()
}

val ArrUint64Codec: SpecCodec<ArrUint64> = SpecCodec(
    encode = { w, obj -> writeArrUint64(w, obj) },
    decode = { r ->
        var itemsVal: List<ULong> = emptyList()
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "items" -> itemsVal = run { val list = mutableListOf<ULong>(); r.beginArray(); while (r.hasNextElement()) { list.add(r.readUint64()) }; r.endArray(); list }
                else -> r.skip()
            }
        }
        r.endObject()
        ArrUint64(items = itemsVal)
    }
)

data class MultiArr1(
    val names: List<String>,
    val scores: List<Int>,
)

fun writeMultiArr1(w: SpecWriter, obj: MultiArr1) {
    w.beginObject(2)
    w.writeField("names"); w.beginArray(obj.names.size)
        for (item in obj.names) { w.nextElement(); w.writeString(item) }
        w.endArray()
    w.writeField("scores"); w.beginArray(obj.scores.size)
        for (item in obj.scores) { w.nextElement(); w.writeInt32(item) }
        w.endArray()
    w.endObject()
}

val MultiArr1Codec: SpecCodec<MultiArr1> = SpecCodec(
    encode = { w, obj -> writeMultiArr1(w, obj) },
    decode = { r ->
        var namesVal: List<String> = emptyList()
        var scoresVal: List<Int> = emptyList()
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "names" -> namesVal = run { val list = mutableListOf<String>(); r.beginArray(); while (r.hasNextElement()) { list.add(r.readString()) }; r.endArray(); list }
                "scores" -> scoresVal = run { val list = mutableListOf<Int>(); r.beginArray(); while (r.hasNextElement()) { list.add(r.readInt32()) }; r.endArray(); list }
                else -> r.skip()
            }
        }
        r.endObject()
        MultiArr1(names = namesVal, scores = scoresVal)
    }
)

data class MultiArr2(
    val flags: List<Boolean>,
    val values: List<Double>,
    val payload: List<ByteArray>,
)

fun writeMultiArr2(w: SpecWriter, obj: MultiArr2) {
    w.beginObject(3)
    w.writeField("flags"); w.beginArray(obj.flags.size)
        for (item in obj.flags) { w.nextElement(); w.writeBool(item) }
        w.endArray()
    w.writeField("values"); w.beginArray(obj.values.size)
        for (item in obj.values) { w.nextElement(); w.writeFloat64(item) }
        w.endArray()
    w.writeField("payload"); w.beginArray(obj.payload.size)
        for (item in obj.payload) { w.nextElement(); w.writeBytes(item) }
        w.endArray()
    w.endObject()
}

val MultiArr2Codec: SpecCodec<MultiArr2> = SpecCodec(
    encode = { w, obj -> writeMultiArr2(w, obj) },
    decode = { r ->
        var flagsVal: List<Boolean> = emptyList()
        var valuesVal: List<Double> = emptyList()
        var payloadVal: List<ByteArray> = emptyList()
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "flags" -> flagsVal = run { val list = mutableListOf<Boolean>(); r.beginArray(); while (r.hasNextElement()) { list.add(r.readBool()) }; r.endArray(); list }
                "values" -> valuesVal = run { val list = mutableListOf<Double>(); r.beginArray(); while (r.hasNextElement()) { list.add(r.readFloat64()) }; r.endArray(); list }
                "payload" -> payloadVal = run { val list = mutableListOf<ByteArray>(); r.beginArray(); while (r.hasNextElement()) { list.add(r.readBytes()) }; r.endArray(); list }
                else -> r.skip()
            }
        }
        r.endObject()
        MultiArr2(flags = flagsVal, values = valuesVal, payload = payloadVal)
    }
)

data class MultiArr3(
    val a: List<String>,
    val b: List<Int>,
    val c: List<Double>,
)

fun writeMultiArr3(w: SpecWriter, obj: MultiArr3) {
    w.beginObject(3)
    w.writeField("a"); w.beginArray(obj.a.size)
        for (item in obj.a) { w.nextElement(); w.writeString(item) }
        w.endArray()
    w.writeField("b"); w.beginArray(obj.b.size)
        for (item in obj.b) { w.nextElement(); w.writeInt32(item) }
        w.endArray()
    w.writeField("c"); w.beginArray(obj.c.size)
        for (item in obj.c) { w.nextElement(); w.writeFloat64(item) }
        w.endArray()
    w.endObject()
}

val MultiArr3Codec: SpecCodec<MultiArr3> = SpecCodec(
    encode = { w, obj -> writeMultiArr3(w, obj) },
    decode = { r ->
        var aVal: List<String> = emptyList()
        var bVal: List<Int> = emptyList()
        var cVal: List<Double> = emptyList()
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = run { val list = mutableListOf<String>(); r.beginArray(); while (r.hasNextElement()) { list.add(r.readString()) }; r.endArray(); list }
                "b" -> bVal = run { val list = mutableListOf<Int>(); r.beginArray(); while (r.hasNextElement()) { list.add(r.readInt32()) }; r.endArray(); list }
                "c" -> cVal = run { val list = mutableListOf<Double>(); r.beginArray(); while (r.hasNextElement()) { list.add(r.readFloat64()) }; r.endArray(); list }
                else -> r.skip()
            }
        }
        r.endObject()
        MultiArr3(a = aVal, b = bVal, c = cVal)
    }
)

data class MultiArr4(
    val ids: List<Long>,
    val tags: List<String>,
)

fun writeMultiArr4(w: SpecWriter, obj: MultiArr4) {
    w.beginObject(2)
    w.writeField("ids"); w.beginArray(obj.ids.size)
        for (item in obj.ids) { w.nextElement(); w.writeInt64(item) }
        w.endArray()
    w.writeField("tags"); w.beginArray(obj.tags.size)
        for (item in obj.tags) { w.nextElement(); w.writeString(item) }
        w.endArray()
    w.endObject()
}

val MultiArr4Codec: SpecCodec<MultiArr4> = SpecCodec(
    encode = { w, obj -> writeMultiArr4(w, obj) },
    decode = { r ->
        var idsVal: List<Long> = emptyList()
        var tagsVal: List<String> = emptyList()
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "ids" -> idsVal = run { val list = mutableListOf<Long>(); r.beginArray(); while (r.hasNextElement()) { list.add(r.readInt64()) }; r.endArray(); list }
                "tags" -> tagsVal = run { val list = mutableListOf<String>(); r.beginArray(); while (r.hasNextElement()) { list.add(r.readString()) }; r.endArray(); list }
                else -> r.skip()
            }
        }
        r.endObject()
        MultiArr4(ids = idsVal, tags = tagsVal)
    }
)

data class MultiArr5(
    val xs: List<ULong>,
    val ys: List<Float>,
    val zs: List<Boolean>,
)

fun writeMultiArr5(w: SpecWriter, obj: MultiArr5) {
    w.beginObject(3)
    w.writeField("xs"); w.beginArray(obj.xs.size)
        for (item in obj.xs) { w.nextElement(); w.writeUint64(item) }
        w.endArray()
    w.writeField("ys"); w.beginArray(obj.ys.size)
        for (item in obj.ys) { w.nextElement(); w.writeFloat32(item) }
        w.endArray()
    w.writeField("zs"); w.beginArray(obj.zs.size)
        for (item in obj.zs) { w.nextElement(); w.writeBool(item) }
        w.endArray()
    w.endObject()
}

val MultiArr5Codec: SpecCodec<MultiArr5> = SpecCodec(
    encode = { w, obj -> writeMultiArr5(w, obj) },
    decode = { r ->
        var xsVal: List<ULong> = emptyList()
        var ysVal: List<Float> = emptyList()
        var zsVal: List<Boolean> = emptyList()
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "xs" -> xsVal = run { val list = mutableListOf<ULong>(); r.beginArray(); while (r.hasNextElement()) { list.add(r.readUint64()) }; r.endArray(); list }
                "ys" -> ysVal = run { val list = mutableListOf<Float>(); r.beginArray(); while (r.hasNextElement()) { list.add(r.readFloat32()) }; r.endArray(); list }
                "zs" -> zsVal = run { val list = mutableListOf<Boolean>(); r.beginArray(); while (r.hasNextElement()) { list.add(r.readBool()) }; r.endArray(); list }
                else -> r.skip()
            }
        }
        r.endObject()
        MultiArr5(xs = xsVal, ys = ysVal, zs = zsVal)
    }
)

data class OptCombo1(
    val req: String,
    val optA: Int? = null,
)

fun writeOptCombo1(w: SpecWriter, obj: OptCombo1) {
    var fieldCount = 1
    if (obj.optA != null) fieldCount++
    w.beginObject(fieldCount)
    w.writeField("req"); w.writeString(obj.req)
    if (obj.optA != null) { w.writeField("opt_a"); w.writeInt32(obj.optA) }
    w.endObject()
}

val OptCombo1Codec: SpecCodec<OptCombo1> = SpecCodec(
    encode = { w, obj -> writeOptCombo1(w, obj) },
    decode = { r ->
        var reqVal: String = ""
        var optAVal: Int? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "req" -> reqVal = r.readString()
                "opt_a" -> optAVal = r.readInt32()
                else -> r.skip()
            }
        }
        r.endObject()
        OptCombo1(req = reqVal, optA = optAVal)
    }
)

data class OptCombo2(
    val req: String,
    val optA: Int? = null,
    val optB: Boolean? = null,
)

fun writeOptCombo2(w: SpecWriter, obj: OptCombo2) {
    var fieldCount = 1
    if (obj.optA != null) fieldCount++
    if (obj.optB != null) fieldCount++
    w.beginObject(fieldCount)
    w.writeField("req"); w.writeString(obj.req)
    if (obj.optA != null) { w.writeField("opt_a"); w.writeInt32(obj.optA) }
    if (obj.optB != null) { w.writeField("opt_b"); w.writeBool(obj.optB) }
    w.endObject()
}

val OptCombo2Codec: SpecCodec<OptCombo2> = SpecCodec(
    encode = { w, obj -> writeOptCombo2(w, obj) },
    decode = { r ->
        var reqVal: String = ""
        var optAVal: Int? = null
        var optBVal: Boolean? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "req" -> reqVal = r.readString()
                "opt_a" -> optAVal = r.readInt32()
                "opt_b" -> optBVal = r.readBool()
                else -> r.skip()
            }
        }
        r.endObject()
        OptCombo2(req = reqVal, optA = optAVal, optB = optBVal)
    }
)

data class OptCombo3(
    val req: String,
    val optA: Int? = null,
    val optB: Boolean? = null,
    val optC: Double? = null,
)

fun writeOptCombo3(w: SpecWriter, obj: OptCombo3) {
    var fieldCount = 1
    if (obj.optA != null) fieldCount++
    if (obj.optB != null) fieldCount++
    if (obj.optC != null) fieldCount++
    w.beginObject(fieldCount)
    w.writeField("req"); w.writeString(obj.req)
    if (obj.optA != null) { w.writeField("opt_a"); w.writeInt32(obj.optA) }
    if (obj.optB != null) { w.writeField("opt_b"); w.writeBool(obj.optB) }
    if (obj.optC != null) { w.writeField("opt_c"); w.writeFloat64(obj.optC) }
    w.endObject()
}

val OptCombo3Codec: SpecCodec<OptCombo3> = SpecCodec(
    encode = { w, obj -> writeOptCombo3(w, obj) },
    decode = { r ->
        var reqVal: String = ""
        var optAVal: Int? = null
        var optBVal: Boolean? = null
        var optCVal: Double? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "req" -> reqVal = r.readString()
                "opt_a" -> optAVal = r.readInt32()
                "opt_b" -> optBVal = r.readBool()
                "opt_c" -> optCVal = r.readFloat64()
                else -> r.skip()
            }
        }
        r.endObject()
        OptCombo3(req = reqVal, optA = optAVal, optB = optBVal, optC = optCVal)
    }
)

data class OptCombo4(
    val req: Int,
    val optA: String? = null,
    val optB: ByteArray? = null,
)

fun writeOptCombo4(w: SpecWriter, obj: OptCombo4) {
    var fieldCount = 1
    if (obj.optA != null) fieldCount++
    if (obj.optB != null) fieldCount++
    w.beginObject(fieldCount)
    w.writeField("req"); w.writeInt32(obj.req)
    if (obj.optA != null) { w.writeField("opt_a"); w.writeString(obj.optA) }
    if (obj.optB != null) { w.writeField("opt_b"); w.writeBytes(obj.optB) }
    w.endObject()
}

val OptCombo4Codec: SpecCodec<OptCombo4> = SpecCodec(
    encode = { w, obj -> writeOptCombo4(w, obj) },
    decode = { r ->
        var reqVal: Int = 0
        var optAVal: String? = null
        var optBVal: ByteArray? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "req" -> reqVal = r.readInt32()
                "opt_a" -> optAVal = r.readString()
                "opt_b" -> optBVal = r.readBytes()
                else -> r.skip()
            }
        }
        r.endObject()
        OptCombo4(req = reqVal, optA = optAVal, optB = optBVal)
    }
)

data class OptCombo5(
    val req1: String,
    val req2: Int,
    val optA: Boolean? = null,
    val optB: Double? = null,
)

fun writeOptCombo5(w: SpecWriter, obj: OptCombo5) {
    var fieldCount = 2
    if (obj.optA != null) fieldCount++
    if (obj.optB != null) fieldCount++
    w.beginObject(fieldCount)
    w.writeField("req1"); w.writeString(obj.req1)
    w.writeField("req2"); w.writeInt32(obj.req2)
    if (obj.optA != null) { w.writeField("opt_a"); w.writeBool(obj.optA) }
    if (obj.optB != null) { w.writeField("opt_b"); w.writeFloat64(obj.optB) }
    w.endObject()
}

val OptCombo5Codec: SpecCodec<OptCombo5> = SpecCodec(
    encode = { w, obj -> writeOptCombo5(w, obj) },
    decode = { r ->
        var req1Val: String = ""
        var req2Val: Int = 0
        var optAVal: Boolean? = null
        var optBVal: Double? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "req1" -> req1Val = r.readString()
                "req2" -> req2Val = r.readInt32()
                "opt_a" -> optAVal = r.readBool()
                "opt_b" -> optBVal = r.readFloat64()
                else -> r.skip()
            }
        }
        r.endObject()
        OptCombo5(req1 = req1Val, req2 = req2Val, optA = optAVal, optB = optBVal)
    }
)

data class OptCombo6(
    val req: String,
    val optS: String? = null,
    val optI: Int? = null,
    val optF: Double? = null,
    val optB: ByteArray? = null,
)

fun writeOptCombo6(w: SpecWriter, obj: OptCombo6) {
    var fieldCount = 1
    if (obj.optS != null) fieldCount++
    if (obj.optI != null) fieldCount++
    if (obj.optF != null) fieldCount++
    if (obj.optB != null) fieldCount++
    w.beginObject(fieldCount)
    w.writeField("req"); w.writeString(obj.req)
    if (obj.optS != null) { w.writeField("opt_s"); w.writeString(obj.optS) }
    if (obj.optI != null) { w.writeField("opt_i"); w.writeInt32(obj.optI) }
    if (obj.optF != null) { w.writeField("opt_f"); w.writeFloat64(obj.optF) }
    if (obj.optB != null) { w.writeField("opt_b"); w.writeBytes(obj.optB) }
    w.endObject()
}

val OptCombo6Codec: SpecCodec<OptCombo6> = SpecCodec(
    encode = { w, obj -> writeOptCombo6(w, obj) },
    decode = { r ->
        var reqVal: String = ""
        var optSVal: String? = null
        var optIVal: Int? = null
        var optFVal: Double? = null
        var optBVal: ByteArray? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "req" -> reqVal = r.readString()
                "opt_s" -> optSVal = r.readString()
                "opt_i" -> optIVal = r.readInt32()
                "opt_f" -> optFVal = r.readFloat64()
                "opt_b" -> optBVal = r.readBytes()
                else -> r.skip()
            }
        }
        r.endObject()
        OptCombo6(req = reqVal, optS = optSVal, optI = optIVal, optF = optFVal, optB = optBVal)
    }
)

data class OptCombo7(
    val req: Long,
    val optU64: ULong? = null,
    val optStr: String? = null,
)

fun writeOptCombo7(w: SpecWriter, obj: OptCombo7) {
    var fieldCount = 1
    if (obj.optU64 != null) fieldCount++
    if (obj.optStr != null) fieldCount++
    w.beginObject(fieldCount)
    w.writeField("req"); w.writeInt64(obj.req)
    if (obj.optU64 != null) { w.writeField("opt_u64"); w.writeUint64(obj.optU64) }
    if (obj.optStr != null) { w.writeField("opt_str"); w.writeString(obj.optStr) }
    w.endObject()
}

val OptCombo7Codec: SpecCodec<OptCombo7> = SpecCodec(
    encode = { w, obj -> writeOptCombo7(w, obj) },
    decode = { r ->
        var reqVal: Long = 0L
        var optU64Val: ULong? = null
        var optStrVal: String? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "req" -> reqVal = r.readInt64()
                "opt_u64" -> optU64Val = r.readUint64()
                "opt_str" -> optStrVal = r.readString()
                else -> r.skip()
            }
        }
        r.endObject()
        OptCombo7(req = reqVal, optU64 = optU64Val, optStr = optStrVal)
    }
)

data class OptCombo8(
    val a: String,
    val b: Int? = null,
    val c: Double? = null,
    val d: Boolean? = null,
    val e: ByteArray? = null,
    val f: Long? = null,
)

fun writeOptCombo8(w: SpecWriter, obj: OptCombo8) {
    var fieldCount = 1
    if (obj.b != null) fieldCount++
    if (obj.c != null) fieldCount++
    if (obj.d != null) fieldCount++
    if (obj.e != null) fieldCount++
    if (obj.f != null) fieldCount++
    w.beginObject(fieldCount)
    w.writeField("a"); w.writeString(obj.a)
    if (obj.b != null) { w.writeField("b"); w.writeInt32(obj.b) }
    if (obj.c != null) { w.writeField("c"); w.writeFloat64(obj.c) }
    if (obj.d != null) { w.writeField("d"); w.writeBool(obj.d) }
    if (obj.e != null) { w.writeField("e"); w.writeBytes(obj.e) }
    if (obj.f != null) { w.writeField("f"); w.writeInt64(obj.f) }
    w.endObject()
}

val OptCombo8Codec: SpecCodec<OptCombo8> = SpecCodec(
    encode = { w, obj -> writeOptCombo8(w, obj) },
    decode = { r ->
        var aVal: String = ""
        var bVal: Int? = null
        var cVal: Double? = null
        var dVal: Boolean? = null
        var eVal: ByteArray? = null
        var fVal: Long? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readString()
                "b" -> bVal = r.readInt32()
                "c" -> cVal = r.readFloat64()
                "d" -> dVal = r.readBool()
                "e" -> eVal = r.readBytes()
                "f" -> fVal = r.readInt64()
                else -> r.skip()
            }
        }
        r.endObject()
        OptCombo8(a = aVal, b = bVal, c = cVal, d = dVal, e = eVal, f = fVal)
    }
)

data class OptCombo9(
    val id: String,
    val name: String? = null,
    val age: Int? = null,
    val score: Double? = null,
)

fun writeOptCombo9(w: SpecWriter, obj: OptCombo9) {
    var fieldCount = 1
    if (obj.name != null) fieldCount++
    if (obj.age != null) fieldCount++
    if (obj.score != null) fieldCount++
    w.beginObject(fieldCount)
    w.writeField("id"); w.writeString(obj.id)
    if (obj.name != null) { w.writeField("name"); w.writeString(obj.name) }
    if (obj.age != null) { w.writeField("age"); w.writeInt32(obj.age) }
    if (obj.score != null) { w.writeField("score"); w.writeFloat64(obj.score) }
    w.endObject()
}

val OptCombo9Codec: SpecCodec<OptCombo9> = SpecCodec(
    encode = { w, obj -> writeOptCombo9(w, obj) },
    decode = { r ->
        var idVal: String = ""
        var nameVal: String? = null
        var ageVal: Int? = null
        var scoreVal: Double? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "id" -> idVal = r.readString()
                "name" -> nameVal = r.readString()
                "age" -> ageVal = r.readInt32()
                "score" -> scoreVal = r.readFloat64()
                else -> r.skip()
            }
        }
        r.endObject()
        OptCombo9(id = idVal, name = nameVal, age = ageVal, score = scoreVal)
    }
)

data class OptCombo10(
    val code: Int,
    val msg: String? = null,
    val detail: String? = null,
    val retry: Boolean? = null,
)

fun writeOptCombo10(w: SpecWriter, obj: OptCombo10) {
    var fieldCount = 1
    if (obj.msg != null) fieldCount++
    if (obj.detail != null) fieldCount++
    if (obj.retry != null) fieldCount++
    w.beginObject(fieldCount)
    w.writeField("code"); w.writeInt32(obj.code)
    if (obj.msg != null) { w.writeField("msg"); w.writeString(obj.msg) }
    if (obj.detail != null) { w.writeField("detail"); w.writeString(obj.detail) }
    if (obj.retry != null) { w.writeField("retry"); w.writeBool(obj.retry) }
    w.endObject()
}

val OptCombo10Codec: SpecCodec<OptCombo10> = SpecCodec(
    encode = { w, obj -> writeOptCombo10(w, obj) },
    decode = { r ->
        var codeVal: Int = 0
        var msgVal: String? = null
        var detailVal: String? = null
        var retryVal: Boolean? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "code" -> codeVal = r.readInt32()
                "msg" -> msgVal = r.readString()
                "detail" -> detailVal = r.readString()
                "retry" -> retryVal = r.readBool()
                else -> r.skip()
            }
        }
        r.endObject()
        OptCombo10(code = codeVal, msg = msgVal, detail = detailVal, retry = retryVal)
    }
)
