// Generated by @specodec/typespec-emitter-kotlin. DO NOT EDIT.
package all_types_enums

import specodec.*

data class EnumHolder(
    val color: String,
    val priority: String,
    val status: String,
)

fun writeEnumHolder(w: SpecWriter, obj: EnumHolder) {
    w.beginObject(3)
    w.writeField("color"); w.writeString(obj.color.toString())
    w.writeField("priority"); w.writeString(obj.priority.toString())
    w.writeField("status"); w.writeString(obj.status.toString())
    w.endObject()
}

val EnumHolderCodec: SpecCodec<EnumHolder> = SpecCodec(
    encode = { w, obj -> writeEnumHolder(w, obj) },
    decode = { r ->
        var colorVal: String = "";
        var priorityVal: String = "";
        var statusVal: String = "";
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "color" -> colorVal = r.readString()
                "priority" -> priorityVal = r.readString()
                "status" -> statusVal = r.readString()
                else -> r.skip()
            }
        }
        r.endObject()
        EnumHolder(color = colorVal, priority = priorityVal, status = statusVal)
    }
)

data class OptEnumHolder(
    val color: String? = null,
    val priority: String? = null,
)

fun writeOptEnumHolder(w: SpecWriter, obj: OptEnumHolder) {
    var fieldCount = 0
    if (obj.color != null) fieldCount++
    if (obj.priority != null) fieldCount++
    w.beginObject(fieldCount)
    if (obj.color != null) { w.writeField("color"); w.writeString(obj.color.toString()) }
    if (obj.priority != null) { w.writeField("priority"); w.writeString(obj.priority.toString()) }
    w.endObject()
}

val OptEnumHolderCodec: SpecCodec<OptEnumHolder> = SpecCodec(
    encode = { w, obj -> writeOptEnumHolder(w, obj) },
    decode = { r ->
        var colorVal: String? = null
        var priorityVal: String? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "color" -> colorVal = r.readString()
                "priority" -> priorityVal = r.readString()
                else -> r.skip()
            }
        }
        r.endObject()
        OptEnumHolder(color = colorVal, priority = priorityVal)
    }
)

data class EnumArrayHolder(
    val colors: List<String>,
)

fun writeEnumArrayHolder(w: SpecWriter, obj: EnumArrayHolder) {
    w.beginObject(1)
    w.writeField("colors"); w.beginArray(obj.colors.size)
        for (item in obj.colors) { w.nextElement(); w.writeString(item.toString()) }
        w.endArray()
    w.endObject()
}

val EnumArrayHolderCodec: SpecCodec<EnumArrayHolder> = SpecCodec(
    encode = { w, obj -> writeEnumArrayHolder(w, obj) },
    decode = { r ->
        var colorsVal: List<String> = emptyList()
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "colors" -> colorsVal = run { val list = mutableListOf<String>(); r.beginArray(); while (r.hasNextElement()) { list.add(r.readString()) }; r.endArray(); list }
                else -> r.skip()
            }
        }
        r.endObject()
        EnumArrayHolder(colors = colorsVal)
    }
)

data class EnumMixedHolder(
    val status: String,
    val name: String,
    val count: Int,
    val active: Boolean,
)

fun writeEnumMixedHolder(w: SpecWriter, obj: EnumMixedHolder) {
    w.beginObject(4)
    w.writeField("status"); w.writeString(obj.status.toString())
    w.writeField("name"); w.writeString(obj.name)
    w.writeField("count"); w.writeInt32(obj.count)
    w.writeField("active"); w.writeBool(obj.active)
    w.endObject()
}

val EnumMixedHolderCodec: SpecCodec<EnumMixedHolder> = SpecCodec(
    encode = { w, obj -> writeEnumMixedHolder(w, obj) },
    decode = { r ->
        var statusVal: String = "";
        var nameVal: String = ""
        var countVal: Int = 0
        var activeVal: Boolean = false
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "status" -> statusVal = r.readString()
                "name" -> nameVal = r.readString()
                "count" -> countVal = r.readInt32()
                "active" -> activeVal = r.readBool()
                else -> r.skip()
            }
        }
        r.endObject()
        EnumMixedHolder(status = statusVal, name = nameVal, count = countVal, active = activeVal)
    }
)
