// Generated by @specodec/typespec-emitter-kotlin. DO NOT EDIT.
package all_types_pairs

import specodec.*

data class PairString(
    val a: String,
    val b: String,
)

fun writePairString(w: SpecWriter, obj: PairString) {
    w.beginObject(2)
    w.writeField("a"); w.writeString(obj.a)
    w.writeField("b"); w.writeString(obj.b)
    w.endObject()
}

val PairStringCodec: SpecCodec<PairString> = SpecCodec(
    encode = { w, obj -> writePairString(w, obj) },
    decode = { r ->
        var aVal: String = ""
        var bVal: String = ""
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readString()
                "b" -> bVal = r.readString()
                else -> r.skip()
            }
        }
        r.endObject()
        PairString(a = aVal, b = bVal)
    }
)

data class PairBoolean(
    val a: Boolean,
    val b: Boolean,
)

fun writePairBoolean(w: SpecWriter, obj: PairBoolean) {
    w.beginObject(2)
    w.writeField("a"); w.writeBool(obj.a)
    w.writeField("b"); w.writeBool(obj.b)
    w.endObject()
}

val PairBooleanCodec: SpecCodec<PairBoolean> = SpecCodec(
    encode = { w, obj -> writePairBoolean(w, obj) },
    decode = { r ->
        var aVal: Boolean = false
        var bVal: Boolean = false
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readBool()
                "b" -> bVal = r.readBool()
                else -> r.skip()
            }
        }
        r.endObject()
        PairBoolean(a = aVal, b = bVal)
    }
)

data class PairInt8(
    val a: Byte,
    val b: Byte,
)

fun writePairInt8(w: SpecWriter, obj: PairInt8) {
    w.beginObject(2)
    w.writeField("a"); w.writeInt32(obj.a.toInt())
    w.writeField("b"); w.writeInt32(obj.b.toInt())
    w.endObject()
}

val PairInt8Codec: SpecCodec<PairInt8> = SpecCodec(
    encode = { w, obj -> writePairInt8(w, obj) },
    decode = { r ->
        var aVal: Byte = 0
        var bVal: Byte = 0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readInt32().toByte()
                "b" -> bVal = r.readInt32().toByte()
                else -> r.skip()
            }
        }
        r.endObject()
        PairInt8(a = aVal, b = bVal)
    }
)

data class PairInt16(
    val a: Short,
    val b: Short,
)

fun writePairInt16(w: SpecWriter, obj: PairInt16) {
    w.beginObject(2)
    w.writeField("a"); w.writeInt32(obj.a.toInt())
    w.writeField("b"); w.writeInt32(obj.b.toInt())
    w.endObject()
}

val PairInt16Codec: SpecCodec<PairInt16> = SpecCodec(
    encode = { w, obj -> writePairInt16(w, obj) },
    decode = { r ->
        var aVal: Short = 0
        var bVal: Short = 0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readInt32().toShort()
                "b" -> bVal = r.readInt32().toShort()
                else -> r.skip()
            }
        }
        r.endObject()
        PairInt16(a = aVal, b = bVal)
    }
)

data class PairInt32(
    val a: Int,
    val b: Int,
)

fun writePairInt32(w: SpecWriter, obj: PairInt32) {
    w.beginObject(2)
    w.writeField("a"); w.writeInt32(obj.a)
    w.writeField("b"); w.writeInt32(obj.b)
    w.endObject()
}

val PairInt32Codec: SpecCodec<PairInt32> = SpecCodec(
    encode = { w, obj -> writePairInt32(w, obj) },
    decode = { r ->
        var aVal: Int = 0
        var bVal: Int = 0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readInt32()
                "b" -> bVal = r.readInt32()
                else -> r.skip()
            }
        }
        r.endObject()
        PairInt32(a = aVal, b = bVal)
    }
)

data class PairInt64(
    val a: Long,
    val b: Long,
)

fun writePairInt64(w: SpecWriter, obj: PairInt64) {
    w.beginObject(2)
    w.writeField("a"); w.writeInt64(obj.a)
    w.writeField("b"); w.writeInt64(obj.b)
    w.endObject()
}

val PairInt64Codec: SpecCodec<PairInt64> = SpecCodec(
    encode = { w, obj -> writePairInt64(w, obj) },
    decode = { r ->
        var aVal: Long = 0L
        var bVal: Long = 0L
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readInt64()
                "b" -> bVal = r.readInt64()
                else -> r.skip()
            }
        }
        r.endObject()
        PairInt64(a = aVal, b = bVal)
    }
)

data class PairUint8(
    val a: UByte,
    val b: UByte,
)

fun writePairUint8(w: SpecWriter, obj: PairUint8) {
    w.beginObject(2)
    w.writeField("a"); w.writeUint32(obj.a.toUInt())
    w.writeField("b"); w.writeUint32(obj.b.toUInt())
    w.endObject()
}

val PairUint8Codec: SpecCodec<PairUint8> = SpecCodec(
    encode = { w, obj -> writePairUint8(w, obj) },
    decode = { r ->
        var aVal: UByte = 0u
        var bVal: UByte = 0u
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readUint32().toUByte()
                "b" -> bVal = r.readUint32().toUByte()
                else -> r.skip()
            }
        }
        r.endObject()
        PairUint8(a = aVal, b = bVal)
    }
)

data class PairUint16(
    val a: UShort,
    val b: UShort,
)

fun writePairUint16(w: SpecWriter, obj: PairUint16) {
    w.beginObject(2)
    w.writeField("a"); w.writeUint32(obj.a.toUInt())
    w.writeField("b"); w.writeUint32(obj.b.toUInt())
    w.endObject()
}

val PairUint16Codec: SpecCodec<PairUint16> = SpecCodec(
    encode = { w, obj -> writePairUint16(w, obj) },
    decode = { r ->
        var aVal: UShort = 0u
        var bVal: UShort = 0u
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readUint32().toUShort()
                "b" -> bVal = r.readUint32().toUShort()
                else -> r.skip()
            }
        }
        r.endObject()
        PairUint16(a = aVal, b = bVal)
    }
)

data class PairUint32(
    val a: UInt,
    val b: UInt,
)

fun writePairUint32(w: SpecWriter, obj: PairUint32) {
    w.beginObject(2)
    w.writeField("a"); w.writeUint32(obj.a)
    w.writeField("b"); w.writeUint32(obj.b)
    w.endObject()
}

val PairUint32Codec: SpecCodec<PairUint32> = SpecCodec(
    encode = { w, obj -> writePairUint32(w, obj) },
    decode = { r ->
        var aVal: UInt = 0u
        var bVal: UInt = 0u
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readUint32()
                "b" -> bVal = r.readUint32()
                else -> r.skip()
            }
        }
        r.endObject()
        PairUint32(a = aVal, b = bVal)
    }
)

data class PairUint64(
    val a: ULong,
    val b: ULong,
)

fun writePairUint64(w: SpecWriter, obj: PairUint64) {
    w.beginObject(2)
    w.writeField("a"); w.writeUint64(obj.a)
    w.writeField("b"); w.writeUint64(obj.b)
    w.endObject()
}

val PairUint64Codec: SpecCodec<PairUint64> = SpecCodec(
    encode = { w, obj -> writePairUint64(w, obj) },
    decode = { r ->
        var aVal: ULong = 0uL
        var bVal: ULong = 0uL
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readUint64()
                "b" -> bVal = r.readUint64()
                else -> r.skip()
            }
        }
        r.endObject()
        PairUint64(a = aVal, b = bVal)
    }
)

data class PairFloat32(
    val a: Float,
    val b: Float,
)

fun writePairFloat32(w: SpecWriter, obj: PairFloat32) {
    w.beginObject(2)
    w.writeField("a"); w.writeFloat32(obj.a)
    w.writeField("b"); w.writeFloat32(obj.b)
    w.endObject()
}

val PairFloat32Codec: SpecCodec<PairFloat32> = SpecCodec(
    encode = { w, obj -> writePairFloat32(w, obj) },
    decode = { r ->
        var aVal: Float = 0f
        var bVal: Float = 0f
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readFloat32()
                "b" -> bVal = r.readFloat32()
                else -> r.skip()
            }
        }
        r.endObject()
        PairFloat32(a = aVal, b = bVal)
    }
)

data class PairFloat64(
    val a: Double,
    val b: Double,
)

fun writePairFloat64(w: SpecWriter, obj: PairFloat64) {
    w.beginObject(2)
    w.writeField("a"); w.writeFloat64(obj.a)
    w.writeField("b"); w.writeFloat64(obj.b)
    w.endObject()
}

val PairFloat64Codec: SpecCodec<PairFloat64> = SpecCodec(
    encode = { w, obj -> writePairFloat64(w, obj) },
    decode = { r ->
        var aVal: Double = 0.0
        var bVal: Double = 0.0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readFloat64()
                "b" -> bVal = r.readFloat64()
                else -> r.skip()
            }
        }
        r.endObject()
        PairFloat64(a = aVal, b = bVal)
    }
)

data class PairBytes(
    val a: ByteArray,
    val b: ByteArray,
)

fun writePairBytes(w: SpecWriter, obj: PairBytes) {
    w.beginObject(2)
    w.writeField("a"); w.writeBytes(obj.a)
    w.writeField("b"); w.writeBytes(obj.b)
    w.endObject()
}

val PairBytesCodec: SpecCodec<PairBytes> = SpecCodec(
    encode = { w, obj -> writePairBytes(w, obj) },
    decode = { r ->
        var aVal: ByteArray = byteArrayOf()
        var bVal: ByteArray = byteArrayOf()
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readBytes()
                "b" -> bVal = r.readBytes()
                else -> r.skip()
            }
        }
        r.endObject()
        PairBytes(a = aVal, b = bVal)
    }
)

data class DualStringInt32(
    val a: String,
    val b: Int,
)

fun writeDualStringInt32(w: SpecWriter, obj: DualStringInt32) {
    w.beginObject(2)
    w.writeField("a"); w.writeString(obj.a)
    w.writeField("b"); w.writeInt32(obj.b)
    w.endObject()
}

val DualStringInt32Codec: SpecCodec<DualStringInt32> = SpecCodec(
    encode = { w, obj -> writeDualStringInt32(w, obj) },
    decode = { r ->
        var aVal: String = ""
        var bVal: Int = 0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readString()
                "b" -> bVal = r.readInt32()
                else -> r.skip()
            }
        }
        r.endObject()
        DualStringInt32(a = aVal, b = bVal)
    }
)

data class DualStringBoolean(
    val a: String,
    val b: Boolean,
)

fun writeDualStringBoolean(w: SpecWriter, obj: DualStringBoolean) {
    w.beginObject(2)
    w.writeField("a"); w.writeString(obj.a)
    w.writeField("b"); w.writeBool(obj.b)
    w.endObject()
}

val DualStringBooleanCodec: SpecCodec<DualStringBoolean> = SpecCodec(
    encode = { w, obj -> writeDualStringBoolean(w, obj) },
    decode = { r ->
        var aVal: String = ""
        var bVal: Boolean = false
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readString()
                "b" -> bVal = r.readBool()
                else -> r.skip()
            }
        }
        r.endObject()
        DualStringBoolean(a = aVal, b = bVal)
    }
)

data class DualStringFloat64(
    val a: String,
    val b: Double,
)

fun writeDualStringFloat64(w: SpecWriter, obj: DualStringFloat64) {
    w.beginObject(2)
    w.writeField("a"); w.writeString(obj.a)
    w.writeField("b"); w.writeFloat64(obj.b)
    w.endObject()
}

val DualStringFloat64Codec: SpecCodec<DualStringFloat64> = SpecCodec(
    encode = { w, obj -> writeDualStringFloat64(w, obj) },
    decode = { r ->
        var aVal: String = ""
        var bVal: Double = 0.0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readString()
                "b" -> bVal = r.readFloat64()
                else -> r.skip()
            }
        }
        r.endObject()
        DualStringFloat64(a = aVal, b = bVal)
    }
)

data class DualStringBytes(
    val a: String,
    val b: ByteArray,
)

fun writeDualStringBytes(w: SpecWriter, obj: DualStringBytes) {
    w.beginObject(2)
    w.writeField("a"); w.writeString(obj.a)
    w.writeField("b"); w.writeBytes(obj.b)
    w.endObject()
}

val DualStringBytesCodec: SpecCodec<DualStringBytes> = SpecCodec(
    encode = { w, obj -> writeDualStringBytes(w, obj) },
    decode = { r ->
        var aVal: String = ""
        var bVal: ByteArray = byteArrayOf()
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readString()
                "b" -> bVal = r.readBytes()
                else -> r.skip()
            }
        }
        r.endObject()
        DualStringBytes(a = aVal, b = bVal)
    }
)

data class DualInt32Boolean(
    val a: Int,
    val b: Boolean,
)

fun writeDualInt32Boolean(w: SpecWriter, obj: DualInt32Boolean) {
    w.beginObject(2)
    w.writeField("a"); w.writeInt32(obj.a)
    w.writeField("b"); w.writeBool(obj.b)
    w.endObject()
}

val DualInt32BooleanCodec: SpecCodec<DualInt32Boolean> = SpecCodec(
    encode = { w, obj -> writeDualInt32Boolean(w, obj) },
    decode = { r ->
        var aVal: Int = 0
        var bVal: Boolean = false
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readInt32()
                "b" -> bVal = r.readBool()
                else -> r.skip()
            }
        }
        r.endObject()
        DualInt32Boolean(a = aVal, b = bVal)
    }
)

data class DualInt32Float64(
    val a: Int,
    val b: Double,
)

fun writeDualInt32Float64(w: SpecWriter, obj: DualInt32Float64) {
    w.beginObject(2)
    w.writeField("a"); w.writeInt32(obj.a)
    w.writeField("b"); w.writeFloat64(obj.b)
    w.endObject()
}

val DualInt32Float64Codec: SpecCodec<DualInt32Float64> = SpecCodec(
    encode = { w, obj -> writeDualInt32Float64(w, obj) },
    decode = { r ->
        var aVal: Int = 0
        var bVal: Double = 0.0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readInt32()
                "b" -> bVal = r.readFloat64()
                else -> r.skip()
            }
        }
        r.endObject()
        DualInt32Float64(a = aVal, b = bVal)
    }
)

data class DualInt32Int64(
    val a: Int,
    val b: Long,
)

fun writeDualInt32Int64(w: SpecWriter, obj: DualInt32Int64) {
    w.beginObject(2)
    w.writeField("a"); w.writeInt32(obj.a)
    w.writeField("b"); w.writeInt64(obj.b)
    w.endObject()
}

val DualInt32Int64Codec: SpecCodec<DualInt32Int64> = SpecCodec(
    encode = { w, obj -> writeDualInt32Int64(w, obj) },
    decode = { r ->
        var aVal: Int = 0
        var bVal: Long = 0L
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readInt32()
                "b" -> bVal = r.readInt64()
                else -> r.skip()
            }
        }
        r.endObject()
        DualInt32Int64(a = aVal, b = bVal)
    }
)

data class DualInt32Uint32(
    val a: Int,
    val b: UInt,
)

fun writeDualInt32Uint32(w: SpecWriter, obj: DualInt32Uint32) {
    w.beginObject(2)
    w.writeField("a"); w.writeInt32(obj.a)
    w.writeField("b"); w.writeUint32(obj.b)
    w.endObject()
}

val DualInt32Uint32Codec: SpecCodec<DualInt32Uint32> = SpecCodec(
    encode = { w, obj -> writeDualInt32Uint32(w, obj) },
    decode = { r ->
        var aVal: Int = 0
        var bVal: UInt = 0u
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readInt32()
                "b" -> bVal = r.readUint32()
                else -> r.skip()
            }
        }
        r.endObject()
        DualInt32Uint32(a = aVal, b = bVal)
    }
)

data class DualInt64Uint64(
    val a: Long,
    val b: ULong,
)

fun writeDualInt64Uint64(w: SpecWriter, obj: DualInt64Uint64) {
    w.beginObject(2)
    w.writeField("a"); w.writeInt64(obj.a)
    w.writeField("b"); w.writeUint64(obj.b)
    w.endObject()
}

val DualInt64Uint64Codec: SpecCodec<DualInt64Uint64> = SpecCodec(
    encode = { w, obj -> writeDualInt64Uint64(w, obj) },
    decode = { r ->
        var aVal: Long = 0L
        var bVal: ULong = 0uL
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readInt64()
                "b" -> bVal = r.readUint64()
                else -> r.skip()
            }
        }
        r.endObject()
        DualInt64Uint64(a = aVal, b = bVal)
    }
)

data class DualFloat32Float64(
    val a: Float,
    val b: Double,
)

fun writeDualFloat32Float64(w: SpecWriter, obj: DualFloat32Float64) {
    w.beginObject(2)
    w.writeField("a"); w.writeFloat32(obj.a)
    w.writeField("b"); w.writeFloat64(obj.b)
    w.endObject()
}

val DualFloat32Float64Codec: SpecCodec<DualFloat32Float64> = SpecCodec(
    encode = { w, obj -> writeDualFloat32Float64(w, obj) },
    decode = { r ->
        var aVal: Float = 0f
        var bVal: Double = 0.0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readFloat32()
                "b" -> bVal = r.readFloat64()
                else -> r.skip()
            }
        }
        r.endObject()
        DualFloat32Float64(a = aVal, b = bVal)
    }
)

data class DualFloat64Boolean(
    val a: Double,
    val b: Boolean,
)

fun writeDualFloat64Boolean(w: SpecWriter, obj: DualFloat64Boolean) {
    w.beginObject(2)
    w.writeField("a"); w.writeFloat64(obj.a)
    w.writeField("b"); w.writeBool(obj.b)
    w.endObject()
}

val DualFloat64BooleanCodec: SpecCodec<DualFloat64Boolean> = SpecCodec(
    encode = { w, obj -> writeDualFloat64Boolean(w, obj) },
    decode = { r ->
        var aVal: Double = 0.0
        var bVal: Boolean = false
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readFloat64()
                "b" -> bVal = r.readBool()
                else -> r.skip()
            }
        }
        r.endObject()
        DualFloat64Boolean(a = aVal, b = bVal)
    }
)

data class DualFloat64Bytes(
    val a: Double,
    val b: ByteArray,
)

fun writeDualFloat64Bytes(w: SpecWriter, obj: DualFloat64Bytes) {
    w.beginObject(2)
    w.writeField("a"); w.writeFloat64(obj.a)
    w.writeField("b"); w.writeBytes(obj.b)
    w.endObject()
}

val DualFloat64BytesCodec: SpecCodec<DualFloat64Bytes> = SpecCodec(
    encode = { w, obj -> writeDualFloat64Bytes(w, obj) },
    decode = { r ->
        var aVal: Double = 0.0
        var bVal: ByteArray = byteArrayOf()
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readFloat64()
                "b" -> bVal = r.readBytes()
                else -> r.skip()
            }
        }
        r.endObject()
        DualFloat64Bytes(a = aVal, b = bVal)
    }
)

data class DualUint32Uint64(
    val a: UInt,
    val b: ULong,
)

fun writeDualUint32Uint64(w: SpecWriter, obj: DualUint32Uint64) {
    w.beginObject(2)
    w.writeField("a"); w.writeUint32(obj.a)
    w.writeField("b"); w.writeUint64(obj.b)
    w.endObject()
}

val DualUint32Uint64Codec: SpecCodec<DualUint32Uint64> = SpecCodec(
    encode = { w, obj -> writeDualUint32Uint64(w, obj) },
    decode = { r ->
        var aVal: UInt = 0u
        var bVal: ULong = 0uL
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readUint32()
                "b" -> bVal = r.readUint64()
                else -> r.skip()
            }
        }
        r.endObject()
        DualUint32Uint64(a = aVal, b = bVal)
    }
)

data class DualBooleanBytes(
    val a: Boolean,
    val b: ByteArray,
)

fun writeDualBooleanBytes(w: SpecWriter, obj: DualBooleanBytes) {
    w.beginObject(2)
    w.writeField("a"); w.writeBool(obj.a)
    w.writeField("b"); w.writeBytes(obj.b)
    w.endObject()
}

val DualBooleanBytesCodec: SpecCodec<DualBooleanBytes> = SpecCodec(
    encode = { w, obj -> writeDualBooleanBytes(w, obj) },
    decode = { r ->
        var aVal: Boolean = false
        var bVal: ByteArray = byteArrayOf()
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readBool()
                "b" -> bVal = r.readBytes()
                else -> r.skip()
            }
        }
        r.endObject()
        DualBooleanBytes(a = aVal, b = bVal)
    }
)

data class DualInt8Uint8(
    val a: Byte,
    val b: UByte,
)

fun writeDualInt8Uint8(w: SpecWriter, obj: DualInt8Uint8) {
    w.beginObject(2)
    w.writeField("a"); w.writeInt32(obj.a.toInt())
    w.writeField("b"); w.writeUint32(obj.b.toUInt())
    w.endObject()
}

val DualInt8Uint8Codec: SpecCodec<DualInt8Uint8> = SpecCodec(
    encode = { w, obj -> writeDualInt8Uint8(w, obj) },
    decode = { r ->
        var aVal: Byte = 0
        var bVal: UByte = 0u
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readInt32().toByte()
                "b" -> bVal = r.readUint32().toUByte()
                else -> r.skip()
            }
        }
        r.endObject()
        DualInt8Uint8(a = aVal, b = bVal)
    }
)

data class DualInt16Uint16(
    val a: Short,
    val b: UShort,
)

fun writeDualInt16Uint16(w: SpecWriter, obj: DualInt16Uint16) {
    w.beginObject(2)
    w.writeField("a"); w.writeInt32(obj.a.toInt())
    w.writeField("b"); w.writeUint32(obj.b.toUInt())
    w.endObject()
}

val DualInt16Uint16Codec: SpecCodec<DualInt16Uint16> = SpecCodec(
    encode = { w, obj -> writeDualInt16Uint16(w, obj) },
    decode = { r ->
        var aVal: Short = 0
        var bVal: UShort = 0u
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readInt32().toShort()
                "b" -> bVal = r.readUint32().toUShort()
                else -> r.skip()
            }
        }
        r.endObject()
        DualInt16Uint16(a = aVal, b = bVal)
    }
)

data class DualStringInt64(
    val a: String,
    val b: Long,
)

fun writeDualStringInt64(w: SpecWriter, obj: DualStringInt64) {
    w.beginObject(2)
    w.writeField("a"); w.writeString(obj.a)
    w.writeField("b"); w.writeInt64(obj.b)
    w.endObject()
}

val DualStringInt64Codec: SpecCodec<DualStringInt64> = SpecCodec(
    encode = { w, obj -> writeDualStringInt64(w, obj) },
    decode = { r ->
        var aVal: String = ""
        var bVal: Long = 0L
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readString()
                "b" -> bVal = r.readInt64()
                else -> r.skip()
            }
        }
        r.endObject()
        DualStringInt64(a = aVal, b = bVal)
    }
)

data class DualStringUint64(
    val a: String,
    val b: ULong,
)

fun writeDualStringUint64(w: SpecWriter, obj: DualStringUint64) {
    w.beginObject(2)
    w.writeField("a"); w.writeString(obj.a)
    w.writeField("b"); w.writeUint64(obj.b)
    w.endObject()
}

val DualStringUint64Codec: SpecCodec<DualStringUint64> = SpecCodec(
    encode = { w, obj -> writeDualStringUint64(w, obj) },
    decode = { r ->
        var aVal: String = ""
        var bVal: ULong = 0uL
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readString()
                "b" -> bVal = r.readUint64()
                else -> r.skip()
            }
        }
        r.endObject()
        DualStringUint64(a = aVal, b = bVal)
    }
)

data class DualInt32Bytes(
    val a: Int,
    val b: ByteArray,
)

fun writeDualInt32Bytes(w: SpecWriter, obj: DualInt32Bytes) {
    w.beginObject(2)
    w.writeField("a"); w.writeInt32(obj.a)
    w.writeField("b"); w.writeBytes(obj.b)
    w.endObject()
}

val DualInt32BytesCodec: SpecCodec<DualInt32Bytes> = SpecCodec(
    encode = { w, obj -> writeDualInt32Bytes(w, obj) },
    decode = { r ->
        var aVal: Int = 0
        var bVal: ByteArray = byteArrayOf()
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readInt32()
                "b" -> bVal = r.readBytes()
                else -> r.skip()
            }
        }
        r.endObject()
        DualInt32Bytes(a = aVal, b = bVal)
    }
)

data class DualFloat64Int32(
    val a: Double,
    val b: Int,
)

fun writeDualFloat64Int32(w: SpecWriter, obj: DualFloat64Int32) {
    w.beginObject(2)
    w.writeField("a"); w.writeFloat64(obj.a)
    w.writeField("b"); w.writeInt32(obj.b)
    w.endObject()
}

val DualFloat64Int32Codec: SpecCodec<DualFloat64Int32> = SpecCodec(
    encode = { w, obj -> writeDualFloat64Int32(w, obj) },
    decode = { r ->
        var aVal: Double = 0.0
        var bVal: Int = 0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readFloat64()
                "b" -> bVal = r.readInt32()
                else -> r.skip()
            }
        }
        r.endObject()
        DualFloat64Int32(a = aVal, b = bVal)
    }
)

data class DualBooleanInt32(
    val a: Boolean,
    val b: Int,
)

fun writeDualBooleanInt32(w: SpecWriter, obj: DualBooleanInt32) {
    w.beginObject(2)
    w.writeField("a"); w.writeBool(obj.a)
    w.writeField("b"); w.writeInt32(obj.b)
    w.endObject()
}

val DualBooleanInt32Codec: SpecCodec<DualBooleanInt32> = SpecCodec(
    encode = { w, obj -> writeDualBooleanInt32(w, obj) },
    decode = { r ->
        var aVal: Boolean = false
        var bVal: Int = 0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readBool()
                "b" -> bVal = r.readInt32()
                else -> r.skip()
            }
        }
        r.endObject()
        DualBooleanInt32(a = aVal, b = bVal)
    }
)

data class DualBytesInt64(
    val a: ByteArray,
    val b: Long,
)

fun writeDualBytesInt64(w: SpecWriter, obj: DualBytesInt64) {
    w.beginObject(2)
    w.writeField("a"); w.writeBytes(obj.a)
    w.writeField("b"); w.writeInt64(obj.b)
    w.endObject()
}

val DualBytesInt64Codec: SpecCodec<DualBytesInt64> = SpecCodec(
    encode = { w, obj -> writeDualBytesInt64(w, obj) },
    decode = { r ->
        var aVal: ByteArray = byteArrayOf()
        var bVal: Long = 0L
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readBytes()
                "b" -> bVal = r.readInt64()
                else -> r.skip()
            }
        }
        r.endObject()
        DualBytesInt64(a = aVal, b = bVal)
    }
)

data class DualInt8Float32(
    val a: Byte,
    val b: Float,
)

fun writeDualInt8Float32(w: SpecWriter, obj: DualInt8Float32) {
    w.beginObject(2)
    w.writeField("a"); w.writeInt32(obj.a.toInt())
    w.writeField("b"); w.writeFloat32(obj.b)
    w.endObject()
}

val DualInt8Float32Codec: SpecCodec<DualInt8Float32> = SpecCodec(
    encode = { w, obj -> writeDualInt8Float32(w, obj) },
    decode = { r ->
        var aVal: Byte = 0
        var bVal: Float = 0f
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readInt32().toByte()
                "b" -> bVal = r.readFloat32()
                else -> r.skip()
            }
        }
        r.endObject()
        DualInt8Float32(a = aVal, b = bVal)
    }
)

data class DualUint8Int16(
    val a: UByte,
    val b: Short,
)

fun writeDualUint8Int16(w: SpecWriter, obj: DualUint8Int16) {
    w.beginObject(2)
    w.writeField("a"); w.writeUint32(obj.a.toUInt())
    w.writeField("b"); w.writeInt32(obj.b.toInt())
    w.endObject()
}

val DualUint8Int16Codec: SpecCodec<DualUint8Int16> = SpecCodec(
    encode = { w, obj -> writeDualUint8Int16(w, obj) },
    decode = { r ->
        var aVal: UByte = 0u
        var bVal: Short = 0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readUint32().toUByte()
                "b" -> bVal = r.readInt32().toShort()
                else -> r.skip()
            }
        }
        r.endObject()
        DualUint8Int16(a = aVal, b = bVal)
    }
)

data class DualInt64Float64(
    val a: Long,
    val b: Double,
)

fun writeDualInt64Float64(w: SpecWriter, obj: DualInt64Float64) {
    w.beginObject(2)
    w.writeField("a"); w.writeInt64(obj.a)
    w.writeField("b"); w.writeFloat64(obj.b)
    w.endObject()
}

val DualInt64Float64Codec: SpecCodec<DualInt64Float64> = SpecCodec(
    encode = { w, obj -> writeDualInt64Float64(w, obj) },
    decode = { r ->
        var aVal: Long = 0L
        var bVal: Double = 0.0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readInt64()
                "b" -> bVal = r.readFloat64()
                else -> r.skip()
            }
        }
        r.endObject()
        DualInt64Float64(a = aVal, b = bVal)
    }
)

data class DualUint64String(
    val a: ULong,
    val b: String,
)

fun writeDualUint64String(w: SpecWriter, obj: DualUint64String) {
    w.beginObject(2)
    w.writeField("a"); w.writeUint64(obj.a)
    w.writeField("b"); w.writeString(obj.b)
    w.endObject()
}

val DualUint64StringCodec: SpecCodec<DualUint64String> = SpecCodec(
    encode = { w, obj -> writeDualUint64String(w, obj) },
    decode = { r ->
        var aVal: ULong = 0uL
        var bVal: String = ""
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readUint64()
                "b" -> bVal = r.readString()
                else -> r.skip()
            }
        }
        r.endObject()
        DualUint64String(a = aVal, b = bVal)
    }
)

data class Triple01(
    val a: String,
    val b: Int,
    val c: Boolean,
)

fun writeTriple01(w: SpecWriter, obj: Triple01) {
    w.beginObject(3)
    w.writeField("a"); w.writeString(obj.a)
    w.writeField("b"); w.writeInt32(obj.b)
    w.writeField("c"); w.writeBool(obj.c)
    w.endObject()
}

val Triple01Codec: SpecCodec<Triple01> = SpecCodec(
    encode = { w, obj -> writeTriple01(w, obj) },
    decode = { r ->
        var aVal: String = ""
        var bVal: Int = 0
        var cVal: Boolean = false
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readString()
                "b" -> bVal = r.readInt32()
                "c" -> cVal = r.readBool()
                else -> r.skip()
            }
        }
        r.endObject()
        Triple01(a = aVal, b = bVal, c = cVal)
    }
)

data class Triple02(
    val a: Double,
    val b: Double,
    val c: Double,
)

fun writeTriple02(w: SpecWriter, obj: Triple02) {
    w.beginObject(3)
    w.writeField("a"); w.writeFloat64(obj.a)
    w.writeField("b"); w.writeFloat64(obj.b)
    w.writeField("c"); w.writeFloat64(obj.c)
    w.endObject()
}

val Triple02Codec: SpecCodec<Triple02> = SpecCodec(
    encode = { w, obj -> writeTriple02(w, obj) },
    decode = { r ->
        var aVal: Double = 0.0
        var bVal: Double = 0.0
        var cVal: Double = 0.0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readFloat64()
                "b" -> bVal = r.readFloat64()
                "c" -> cVal = r.readFloat64()
                else -> r.skip()
            }
        }
        r.endObject()
        Triple02(a = aVal, b = bVal, c = cVal)
    }
)

data class Triple03(
    val a: Int,
    val b: Int,
    val c: Int,
)

fun writeTriple03(w: SpecWriter, obj: Triple03) {
    w.beginObject(3)
    w.writeField("a"); w.writeInt32(obj.a)
    w.writeField("b"); w.writeInt32(obj.b)
    w.writeField("c"); w.writeInt32(obj.c)
    w.endObject()
}

val Triple03Codec: SpecCodec<Triple03> = SpecCodec(
    encode = { w, obj -> writeTriple03(w, obj) },
    decode = { r ->
        var aVal: Int = 0
        var bVal: Int = 0
        var cVal: Int = 0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readInt32()
                "b" -> bVal = r.readInt32()
                "c" -> cVal = r.readInt32()
                else -> r.skip()
            }
        }
        r.endObject()
        Triple03(a = aVal, b = bVal, c = cVal)
    }
)

data class Triple04(
    val a: String,
    val b: String,
    val c: Int,
)

fun writeTriple04(w: SpecWriter, obj: Triple04) {
    w.beginObject(3)
    w.writeField("a"); w.writeString(obj.a)
    w.writeField("b"); w.writeString(obj.b)
    w.writeField("c"); w.writeInt32(obj.c)
    w.endObject()
}

val Triple04Codec: SpecCodec<Triple04> = SpecCodec(
    encode = { w, obj -> writeTriple04(w, obj) },
    decode = { r ->
        var aVal: String = ""
        var bVal: String = ""
        var cVal: Int = 0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readString()
                "b" -> bVal = r.readString()
                "c" -> cVal = r.readInt32()
                else -> r.skip()
            }
        }
        r.endObject()
        Triple04(a = aVal, b = bVal, c = cVal)
    }
)

data class Triple05(
    val a: Long,
    val b: String,
    val c: Boolean,
)

fun writeTriple05(w: SpecWriter, obj: Triple05) {
    w.beginObject(3)
    w.writeField("a"); w.writeInt64(obj.a)
    w.writeField("b"); w.writeString(obj.b)
    w.writeField("c"); w.writeBool(obj.c)
    w.endObject()
}

val Triple05Codec: SpecCodec<Triple05> = SpecCodec(
    encode = { w, obj -> writeTriple05(w, obj) },
    decode = { r ->
        var aVal: Long = 0L
        var bVal: String = ""
        var cVal: Boolean = false
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readInt64()
                "b" -> bVal = r.readString()
                "c" -> cVal = r.readBool()
                else -> r.skip()
            }
        }
        r.endObject()
        Triple05(a = aVal, b = bVal, c = cVal)
    }
)

data class Triple06(
    val a: UInt,
    val b: ULong,
    val c: String,
)

fun writeTriple06(w: SpecWriter, obj: Triple06) {
    w.beginObject(3)
    w.writeField("a"); w.writeUint32(obj.a)
    w.writeField("b"); w.writeUint64(obj.b)
    w.writeField("c"); w.writeString(obj.c)
    w.endObject()
}

val Triple06Codec: SpecCodec<Triple06> = SpecCodec(
    encode = { w, obj -> writeTriple06(w, obj) },
    decode = { r ->
        var aVal: UInt = 0u
        var bVal: ULong = 0uL
        var cVal: String = ""
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readUint32()
                "b" -> bVal = r.readUint64()
                "c" -> cVal = r.readString()
                else -> r.skip()
            }
        }
        r.endObject()
        Triple06(a = aVal, b = bVal, c = cVal)
    }
)

data class Triple07(
    val a: ByteArray,
    val b: String,
    val c: Int,
)

fun writeTriple07(w: SpecWriter, obj: Triple07) {
    w.beginObject(3)
    w.writeField("a"); w.writeBytes(obj.a)
    w.writeField("b"); w.writeString(obj.b)
    w.writeField("c"); w.writeInt32(obj.c)
    w.endObject()
}

val Triple07Codec: SpecCodec<Triple07> = SpecCodec(
    encode = { w, obj -> writeTriple07(w, obj) },
    decode = { r ->
        var aVal: ByteArray = byteArrayOf()
        var bVal: String = ""
        var cVal: Int = 0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readBytes()
                "b" -> bVal = r.readString()
                "c" -> cVal = r.readInt32()
                else -> r.skip()
            }
        }
        r.endObject()
        Triple07(a = aVal, b = bVal, c = cVal)
    }
)

data class Triple08(
    val a: Float,
    val b: Int,
    val c: Boolean,
)

fun writeTriple08(w: SpecWriter, obj: Triple08) {
    w.beginObject(3)
    w.writeField("a"); w.writeFloat32(obj.a)
    w.writeField("b"); w.writeInt32(obj.b)
    w.writeField("c"); w.writeBool(obj.c)
    w.endObject()
}

val Triple08Codec: SpecCodec<Triple08> = SpecCodec(
    encode = { w, obj -> writeTriple08(w, obj) },
    decode = { r ->
        var aVal: Float = 0f
        var bVal: Int = 0
        var cVal: Boolean = false
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readFloat32()
                "b" -> bVal = r.readInt32()
                "c" -> cVal = r.readBool()
                else -> r.skip()
            }
        }
        r.endObject()
        Triple08(a = aVal, b = bVal, c = cVal)
    }
)

data class Triple09(
    val a: String,
    val b: Long,
    val c: Double,
)

fun writeTriple09(w: SpecWriter, obj: Triple09) {
    w.beginObject(3)
    w.writeField("a"); w.writeString(obj.a)
    w.writeField("b"); w.writeInt64(obj.b)
    w.writeField("c"); w.writeFloat64(obj.c)
    w.endObject()
}

val Triple09Codec: SpecCodec<Triple09> = SpecCodec(
    encode = { w, obj -> writeTriple09(w, obj) },
    decode = { r ->
        var aVal: String = ""
        var bVal: Long = 0L
        var cVal: Double = 0.0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readString()
                "b" -> bVal = r.readInt64()
                "c" -> cVal = r.readFloat64()
                else -> r.skip()
            }
        }
        r.endObject()
        Triple09(a = aVal, b = bVal, c = cVal)
    }
)

data class Triple10(
    val a: Boolean,
    val b: Boolean,
    val c: Boolean,
)

fun writeTriple10(w: SpecWriter, obj: Triple10) {
    w.beginObject(3)
    w.writeField("a"); w.writeBool(obj.a)
    w.writeField("b"); w.writeBool(obj.b)
    w.writeField("c"); w.writeBool(obj.c)
    w.endObject()
}

val Triple10Codec: SpecCodec<Triple10> = SpecCodec(
    encode = { w, obj -> writeTriple10(w, obj) },
    decode = { r ->
        var aVal: Boolean = false
        var bVal: Boolean = false
        var cVal: Boolean = false
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readBool()
                "b" -> bVal = r.readBool()
                "c" -> cVal = r.readBool()
                else -> r.skip()
            }
        }
        r.endObject()
        Triple10(a = aVal, b = bVal, c = cVal)
    }
)

data class Triple11(
    val a: Byte,
    val b: Short,
    val c: Int,
)

fun writeTriple11(w: SpecWriter, obj: Triple11) {
    w.beginObject(3)
    w.writeField("a"); w.writeInt32(obj.a.toInt())
    w.writeField("b"); w.writeInt32(obj.b.toInt())
    w.writeField("c"); w.writeInt32(obj.c)
    w.endObject()
}

val Triple11Codec: SpecCodec<Triple11> = SpecCodec(
    encode = { w, obj -> writeTriple11(w, obj) },
    decode = { r ->
        var aVal: Byte = 0
        var bVal: Short = 0
        var cVal: Int = 0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readInt32().toByte()
                "b" -> bVal = r.readInt32().toShort()
                "c" -> cVal = r.readInt32()
                else -> r.skip()
            }
        }
        r.endObject()
        Triple11(a = aVal, b = bVal, c = cVal)
    }
)

data class Triple12(
    val a: UByte,
    val b: UShort,
    val c: UInt,
)

fun writeTriple12(w: SpecWriter, obj: Triple12) {
    w.beginObject(3)
    w.writeField("a"); w.writeUint32(obj.a.toUInt())
    w.writeField("b"); w.writeUint32(obj.b.toUInt())
    w.writeField("c"); w.writeUint32(obj.c)
    w.endObject()
}

val Triple12Codec: SpecCodec<Triple12> = SpecCodec(
    encode = { w, obj -> writeTriple12(w, obj) },
    decode = { r ->
        var aVal: UByte = 0u
        var bVal: UShort = 0u
        var cVal: UInt = 0u
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readUint32().toUByte()
                "b" -> bVal = r.readUint32().toUShort()
                "c" -> cVal = r.readUint32()
                else -> r.skip()
            }
        }
        r.endObject()
        Triple12(a = aVal, b = bVal, c = cVal)
    }
)

data class Triple13(
    val a: String,
    val b: ByteArray,
    val c: Double,
)

fun writeTriple13(w: SpecWriter, obj: Triple13) {
    w.beginObject(3)
    w.writeField("a"); w.writeString(obj.a)
    w.writeField("b"); w.writeBytes(obj.b)
    w.writeField("c"); w.writeFloat64(obj.c)
    w.endObject()
}

val Triple13Codec: SpecCodec<Triple13> = SpecCodec(
    encode = { w, obj -> writeTriple13(w, obj) },
    decode = { r ->
        var aVal: String = ""
        var bVal: ByteArray = byteArrayOf()
        var cVal: Double = 0.0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readString()
                "b" -> bVal = r.readBytes()
                "c" -> cVal = r.readFloat64()
                else -> r.skip()
            }
        }
        r.endObject()
        Triple13(a = aVal, b = bVal, c = cVal)
    }
)

data class Triple14(
    val a: Long,
    val b: ULong,
    val c: Boolean,
)

fun writeTriple14(w: SpecWriter, obj: Triple14) {
    w.beginObject(3)
    w.writeField("a"); w.writeInt64(obj.a)
    w.writeField("b"); w.writeUint64(obj.b)
    w.writeField("c"); w.writeBool(obj.c)
    w.endObject()
}

val Triple14Codec: SpecCodec<Triple14> = SpecCodec(
    encode = { w, obj -> writeTriple14(w, obj) },
    decode = { r ->
        var aVal: Long = 0L
        var bVal: ULong = 0uL
        var cVal: Boolean = false
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readInt64()
                "b" -> bVal = r.readUint64()
                "c" -> cVal = r.readBool()
                else -> r.skip()
            }
        }
        r.endObject()
        Triple14(a = aVal, b = bVal, c = cVal)
    }
)

data class Triple15(
    val a: Double,
    val b: String,
    val c: ByteArray,
)

fun writeTriple15(w: SpecWriter, obj: Triple15) {
    w.beginObject(3)
    w.writeField("a"); w.writeFloat64(obj.a)
    w.writeField("b"); w.writeString(obj.b)
    w.writeField("c"); w.writeBytes(obj.c)
    w.endObject()
}

val Triple15Codec: SpecCodec<Triple15> = SpecCodec(
    encode = { w, obj -> writeTriple15(w, obj) },
    decode = { r ->
        var aVal: Double = 0.0
        var bVal: String = ""
        var cVal: ByteArray = byteArrayOf()
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readFloat64()
                "b" -> bVal = r.readString()
                "c" -> cVal = r.readBytes()
                else -> r.skip()
            }
        }
        r.endObject()
        Triple15(a = aVal, b = bVal, c = cVal)
    }
)
