// Generated by @specodec/typespec-emitter-kotlin. DO NOT EDIT.
package all_types_opt

import specodec.*

data class OptSingleString(
    val v: String? = null,
)

fun writeOptSingleString(w: SpecWriter, obj: OptSingleString) {
    var fieldCount = 0
    if (obj.v != null) fieldCount++
    w.beginObject(fieldCount)
    if (obj.v != null) { w.writeField("v"); w.writeString(obj.v) }
    w.endObject()
}

val OptSingleStringCodec: SpecCodec<OptSingleString> = SpecCodec(
    encode = { w, obj -> writeOptSingleString(w, obj) },
    decode = { r ->
        var vVal: String? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "v" -> vVal = r.readString()
                else -> r.skip()
            }
        }
        r.endObject()
        OptSingleString(v = vVal)
    }
)

data class OptSingleBoolean(
    val v: Boolean? = null,
)

fun writeOptSingleBoolean(w: SpecWriter, obj: OptSingleBoolean) {
    var fieldCount = 0
    if (obj.v != null) fieldCount++
    w.beginObject(fieldCount)
    if (obj.v != null) { w.writeField("v"); w.writeBool(obj.v) }
    w.endObject()
}

val OptSingleBooleanCodec: SpecCodec<OptSingleBoolean> = SpecCodec(
    encode = { w, obj -> writeOptSingleBoolean(w, obj) },
    decode = { r ->
        var vVal: Boolean? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "v" -> vVal = r.readBool()
                else -> r.skip()
            }
        }
        r.endObject()
        OptSingleBoolean(v = vVal)
    }
)

data class OptSingleInt8(
    val v: Byte? = null,
)

fun writeOptSingleInt8(w: SpecWriter, obj: OptSingleInt8) {
    var fieldCount = 0
    if (obj.v != null) fieldCount++
    w.beginObject(fieldCount)
    if (obj.v != null) { w.writeField("v"); w.writeInt32(obj.v.toInt()) }
    w.endObject()
}

val OptSingleInt8Codec: SpecCodec<OptSingleInt8> = SpecCodec(
    encode = { w, obj -> writeOptSingleInt8(w, obj) },
    decode = { r ->
        var vVal: Byte? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "v" -> vVal = r.readInt32().toByte()
                else -> r.skip()
            }
        }
        r.endObject()
        OptSingleInt8(v = vVal)
    }
)

data class OptSingleInt16(
    val v: Short? = null,
)

fun writeOptSingleInt16(w: SpecWriter, obj: OptSingleInt16) {
    var fieldCount = 0
    if (obj.v != null) fieldCount++
    w.beginObject(fieldCount)
    if (obj.v != null) { w.writeField("v"); w.writeInt32(obj.v.toInt()) }
    w.endObject()
}

val OptSingleInt16Codec: SpecCodec<OptSingleInt16> = SpecCodec(
    encode = { w, obj -> writeOptSingleInt16(w, obj) },
    decode = { r ->
        var vVal: Short? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "v" -> vVal = r.readInt32().toShort()
                else -> r.skip()
            }
        }
        r.endObject()
        OptSingleInt16(v = vVal)
    }
)

data class OptSingleInt32(
    val v: Int? = null,
)

fun writeOptSingleInt32(w: SpecWriter, obj: OptSingleInt32) {
    var fieldCount = 0
    if (obj.v != null) fieldCount++
    w.beginObject(fieldCount)
    if (obj.v != null) { w.writeField("v"); w.writeInt32(obj.v) }
    w.endObject()
}

val OptSingleInt32Codec: SpecCodec<OptSingleInt32> = SpecCodec(
    encode = { w, obj -> writeOptSingleInt32(w, obj) },
    decode = { r ->
        var vVal: Int? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "v" -> vVal = r.readInt32()
                else -> r.skip()
            }
        }
        r.endObject()
        OptSingleInt32(v = vVal)
    }
)

data class OptSingleInt64(
    val v: Long? = null,
)

fun writeOptSingleInt64(w: SpecWriter, obj: OptSingleInt64) {
    var fieldCount = 0
    if (obj.v != null) fieldCount++
    w.beginObject(fieldCount)
    if (obj.v != null) { w.writeField("v"); w.writeInt64(obj.v) }
    w.endObject()
}

val OptSingleInt64Codec: SpecCodec<OptSingleInt64> = SpecCodec(
    encode = { w, obj -> writeOptSingleInt64(w, obj) },
    decode = { r ->
        var vVal: Long? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "v" -> vVal = r.readInt64()
                else -> r.skip()
            }
        }
        r.endObject()
        OptSingleInt64(v = vVal)
    }
)

data class OptSingleUint8(
    val v: UByte? = null,
)

fun writeOptSingleUint8(w: SpecWriter, obj: OptSingleUint8) {
    var fieldCount = 0
    if (obj.v != null) fieldCount++
    w.beginObject(fieldCount)
    if (obj.v != null) { w.writeField("v"); w.writeUint32(obj.v.toUInt()) }
    w.endObject()
}

val OptSingleUint8Codec: SpecCodec<OptSingleUint8> = SpecCodec(
    encode = { w, obj -> writeOptSingleUint8(w, obj) },
    decode = { r ->
        var vVal: UByte? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "v" -> vVal = r.readUint32().toUByte()
                else -> r.skip()
            }
        }
        r.endObject()
        OptSingleUint8(v = vVal)
    }
)

data class OptSingleUint16(
    val v: UShort? = null,
)

fun writeOptSingleUint16(w: SpecWriter, obj: OptSingleUint16) {
    var fieldCount = 0
    if (obj.v != null) fieldCount++
    w.beginObject(fieldCount)
    if (obj.v != null) { w.writeField("v"); w.writeUint32(obj.v.toUInt()) }
    w.endObject()
}

val OptSingleUint16Codec: SpecCodec<OptSingleUint16> = SpecCodec(
    encode = { w, obj -> writeOptSingleUint16(w, obj) },
    decode = { r ->
        var vVal: UShort? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "v" -> vVal = r.readUint32().toUShort()
                else -> r.skip()
            }
        }
        r.endObject()
        OptSingleUint16(v = vVal)
    }
)

data class OptSingleUint32(
    val v: UInt? = null,
)

fun writeOptSingleUint32(w: SpecWriter, obj: OptSingleUint32) {
    var fieldCount = 0
    if (obj.v != null) fieldCount++
    w.beginObject(fieldCount)
    if (obj.v != null) { w.writeField("v"); w.writeUint32(obj.v) }
    w.endObject()
}

val OptSingleUint32Codec: SpecCodec<OptSingleUint32> = SpecCodec(
    encode = { w, obj -> writeOptSingleUint32(w, obj) },
    decode = { r ->
        var vVal: UInt? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "v" -> vVal = r.readUint32()
                else -> r.skip()
            }
        }
        r.endObject()
        OptSingleUint32(v = vVal)
    }
)

data class OptSingleUint64(
    val v: ULong? = null,
)

fun writeOptSingleUint64(w: SpecWriter, obj: OptSingleUint64) {
    var fieldCount = 0
    if (obj.v != null) fieldCount++
    w.beginObject(fieldCount)
    if (obj.v != null) { w.writeField("v"); w.writeUint64(obj.v) }
    w.endObject()
}

val OptSingleUint64Codec: SpecCodec<OptSingleUint64> = SpecCodec(
    encode = { w, obj -> writeOptSingleUint64(w, obj) },
    decode = { r ->
        var vVal: ULong? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "v" -> vVal = r.readUint64()
                else -> r.skip()
            }
        }
        r.endObject()
        OptSingleUint64(v = vVal)
    }
)

data class OptSingleFloat32(
    val v: Float? = null,
)

fun writeOptSingleFloat32(w: SpecWriter, obj: OptSingleFloat32) {
    var fieldCount = 0
    if (obj.v != null) fieldCount++
    w.beginObject(fieldCount)
    if (obj.v != null) { w.writeField("v"); w.writeFloat32(obj.v) }
    w.endObject()
}

val OptSingleFloat32Codec: SpecCodec<OptSingleFloat32> = SpecCodec(
    encode = { w, obj -> writeOptSingleFloat32(w, obj) },
    decode = { r ->
        var vVal: Float? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "v" -> vVal = r.readFloat32()
                else -> r.skip()
            }
        }
        r.endObject()
        OptSingleFloat32(v = vVal)
    }
)

data class OptSingleFloat64(
    val v: Double? = null,
)

fun writeOptSingleFloat64(w: SpecWriter, obj: OptSingleFloat64) {
    var fieldCount = 0
    if (obj.v != null) fieldCount++
    w.beginObject(fieldCount)
    if (obj.v != null) { w.writeField("v"); w.writeFloat64(obj.v) }
    w.endObject()
}

val OptSingleFloat64Codec: SpecCodec<OptSingleFloat64> = SpecCodec(
    encode = { w, obj -> writeOptSingleFloat64(w, obj) },
    decode = { r ->
        var vVal: Double? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "v" -> vVal = r.readFloat64()
                else -> r.skip()
            }
        }
        r.endObject()
        OptSingleFloat64(v = vVal)
    }
)

data class OptSingleBytes(
    val v: ByteArray? = null,
)

fun writeOptSingleBytes(w: SpecWriter, obj: OptSingleBytes) {
    var fieldCount = 0
    if (obj.v != null) fieldCount++
    w.beginObject(fieldCount)
    if (obj.v != null) { w.writeField("v"); w.writeBytes(obj.v) }
    w.endObject()
}

val OptSingleBytesCodec: SpecCodec<OptSingleBytes> = SpecCodec(
    encode = { w, obj -> writeOptSingleBytes(w, obj) },
    decode = { r ->
        var vVal: ByteArray? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "v" -> vVal = r.readBytes()
                else -> r.skip()
            }
        }
        r.endObject()
        OptSingleBytes(v = vVal)
    }
)
