// Generated by @specodec/typespec-emitter-kotlin. DO NOT EDIT.
package all_types_edge

import specodec.*
import all_types.*

class EdgeEmpty

fun writeEdgeEmpty(w: SpecWriter, obj: EdgeEmpty) {
    w.beginObject(0)
    w.endObject()
}

val EdgeEmptyCodec: SpecCodec<EdgeEmpty> = SpecCodec(
    encode = { w, obj -> writeEdgeEmpty(w, obj) },
    decode = { r ->
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                else -> r.skip()
            }
        }
        r.endObject()
        EdgeEmpty()
    }
)

data class EdgeOneOpt(
    val maybe: String? = null,
)

fun writeEdgeOneOpt(w: SpecWriter, obj: EdgeOneOpt) {
    var fieldCount = 0
    if (obj.maybe != null) fieldCount++
    w.beginObject(fieldCount)
    if (obj.maybe != null) { w.writeField("maybe"); w.writeString(obj.maybe) }
    w.endObject()
}

val EdgeOneOptCodec: SpecCodec<EdgeOneOpt> = SpecCodec(
    encode = { w, obj -> writeEdgeOneOpt(w, obj) },
    decode = { r ->
        var maybeVal: String? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "maybe" -> maybeVal = r.readString()
                else -> r.skip()
            }
        }
        r.endObject()
        EdgeOneOpt(maybe = maybeVal)
    }
)

data class EdgeBigNums(
    val i8: Byte,
    val i16: Short,
    val i32: Int,
    val i64: Long,
    val u8: UByte,
    val u16: UShort,
    val u32: UInt,
    val u64: ULong,
)

fun writeEdgeBigNums(w: SpecWriter, obj: EdgeBigNums) {
    w.beginObject(8)
    w.writeField("i8"); w.writeInt32(obj.i8.toInt())
    w.writeField("i16"); w.writeInt32(obj.i16.toInt())
    w.writeField("i32"); w.writeInt32(obj.i32)
    w.writeField("i64"); w.writeInt64(obj.i64)
    w.writeField("u8"); w.writeUint32(obj.u8.toUInt())
    w.writeField("u16"); w.writeUint32(obj.u16.toUInt())
    w.writeField("u32"); w.writeUint32(obj.u32)
    w.writeField("u64"); w.writeUint64(obj.u64)
    w.endObject()
}

val EdgeBigNumsCodec: SpecCodec<EdgeBigNums> = SpecCodec(
    encode = { w, obj -> writeEdgeBigNums(w, obj) },
    decode = { r ->
        var i8Val: Byte = 0
        var i16Val: Short = 0
        var i32Val: Int = 0
        var i64Val: Long = 0L
        var u8Val: UByte = 0u
        var u16Val: UShort = 0u
        var u32Val: UInt = 0u
        var u64Val: ULong = 0uL
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "i8" -> i8Val = r.readInt32().toByte()
                "i16" -> i16Val = r.readInt32().toShort()
                "i32" -> i32Val = r.readInt32()
                "i64" -> i64Val = r.readInt64()
                "u8" -> u8Val = r.readUint32().toUByte()
                "u16" -> u16Val = r.readUint32().toUShort()
                "u32" -> u32Val = r.readUint32()
                "u64" -> u64Val = r.readUint64()
                else -> r.skip()
            }
        }
        r.endObject()
        EdgeBigNums(i8 = i8Val, i16 = i16Val, i32 = i32Val, i64 = i64Val, u8 = u8Val, u16 = u16Val, u32 = u32Val, u64 = u64Val)
    }
)

data class EdgeZeroVals(
    val s: String,
    val i: Int,
    val f: Double,
    val b: Boolean,
    val byField: ByteArray,
)

fun writeEdgeZeroVals(w: SpecWriter, obj: EdgeZeroVals) {
    w.beginObject(5)
    w.writeField("s"); w.writeString(obj.s)
    w.writeField("i"); w.writeInt32(obj.i)
    w.writeField("f"); w.writeFloat64(obj.f)
    w.writeField("b"); w.writeBool(obj.b)
    w.writeField("by_field"); w.writeBytes(obj.byField)
    w.endObject()
}

val EdgeZeroValsCodec: SpecCodec<EdgeZeroVals> = SpecCodec(
    encode = { w, obj -> writeEdgeZeroVals(w, obj) },
    decode = { r ->
        var sVal: String = ""
        var iVal: Int = 0
        var fVal: Double = 0.0
        var bVal: Boolean = false
        var byFieldVal: ByteArray = byteArrayOf()
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "s" -> sVal = r.readString()
                "i" -> iVal = r.readInt32()
                "f" -> fVal = r.readFloat64()
                "b" -> bVal = r.readBool()
                "by_field" -> byFieldVal = r.readBytes()
                else -> r.skip()
            }
        }
        r.endObject()
        EdgeZeroVals(s = sVal, i = iVal, f = fVal, b = bVal, byField = byFieldVal)
    }
)

data class EdgeNullable(
    val a: String? = null,
    val b: Int? = null,
    val c: Inner? = null,
    val d: List<String>? = null,
)

fun writeEdgeNullable(w: SpecWriter, obj: EdgeNullable) {
    var fieldCount = 0
    if (obj.a != null) fieldCount++
    if (obj.b != null) fieldCount++
    if (obj.c != null) fieldCount++
    if (obj.d != null) fieldCount++
    w.beginObject(fieldCount)
    if (obj.a != null) { w.writeField("a"); w.writeString(obj.a) }
    if (obj.b != null) { w.writeField("b"); w.writeInt32(obj.b) }
    if (obj.c != null) { w.writeField("c"); writeInner(w, obj.c) }
    if (obj.d != null) { w.writeField("d"); w.beginArray(obj.d.size)
        for (item in obj.d) { w.nextElement(); w.writeString(item) }
        w.endArray() }
    w.endObject()
}

val EdgeNullableCodec: SpecCodec<EdgeNullable> = SpecCodec(
    encode = { w, obj -> writeEdgeNullable(w, obj) },
    decode = { r ->
        var aVal: String? = null
        var bVal: Int? = null
        var cVal: Inner? = null
        var dVal: List<String>? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readString()
                "b" -> bVal = r.readInt32()
                "c" -> cVal = if (r.isNull()) { r.readNull(); null } else { InnerCodec.decode(r) }
                "d" -> dVal = run { val list = mutableListOf<String>(); r.beginArray(); while (r.hasNextElement()) { list.add(r.readString()) }; r.endArray(); list }
                else -> r.skip()
            }
        }
        r.endObject()
        EdgeNullable(a = aVal, b = bVal, c = cVal, d = dVal)
    }
)

data class EdgeNegZero(
    val v: Double,
)

fun writeEdgeNegZero(w: SpecWriter, obj: EdgeNegZero) {
    w.beginObject(1)
    w.writeField("v"); w.writeFloat64(obj.v)
    w.endObject()
}

val EdgeNegZeroCodec: SpecCodec<EdgeNegZero> = SpecCodec(
    encode = { w, obj -> writeEdgeNegZero(w, obj) },
    decode = { r ->
        var vVal: Double = 0.0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "v" -> vVal = r.readFloat64()
                else -> r.skip()
            }
        }
        r.endObject()
        EdgeNegZero(v = vVal)
    }
)

data class EdgeNullByte(
    val s: String,
    val b: ByteArray,
)

fun writeEdgeNullByte(w: SpecWriter, obj: EdgeNullByte) {
    w.beginObject(2)
    w.writeField("s"); w.writeString(obj.s)
    w.writeField("b"); w.writeBytes(obj.b)
    w.endObject()
}

val EdgeNullByteCodec: SpecCodec<EdgeNullByte> = SpecCodec(
    encode = { w, obj -> writeEdgeNullByte(w, obj) },
    decode = { r ->
        var sVal: String = ""
        var bVal: ByteArray = byteArrayOf()
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "s" -> sVal = r.readString()
                "b" -> bVal = r.readBytes()
                else -> r.skip()
            }
        }
        r.endObject()
        EdgeNullByte(s = sVal, b = bVal)
    }
)

data class EdgeBoundary(
    val i32Neg129: Int,
    val i32128: Int,
    val i32256: Int,
    val i3265536: Int,
    val i32Neg32769: Int,
    val u3265536: UInt,
)

fun writeEdgeBoundary(w: SpecWriter, obj: EdgeBoundary) {
    w.beginObject(6)
    w.writeField("i32_neg129"); w.writeInt32(obj.i32Neg129)
    w.writeField("i32_128"); w.writeInt32(obj.i32128)
    w.writeField("i32_256"); w.writeInt32(obj.i32256)
    w.writeField("i32_65536"); w.writeInt32(obj.i3265536)
    w.writeField("i32_neg32769"); w.writeInt32(obj.i32Neg32769)
    w.writeField("u32_65536"); w.writeUint32(obj.u3265536)
    w.endObject()
}

val EdgeBoundaryCodec: SpecCodec<EdgeBoundary> = SpecCodec(
    encode = { w, obj -> writeEdgeBoundary(w, obj) },
    decode = { r ->
        var i32Neg129Val: Int = 0
        var i32128Val: Int = 0
        var i32256Val: Int = 0
        var i3265536Val: Int = 0
        var i32Neg32769Val: Int = 0
        var u3265536Val: UInt = 0u
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "i32_neg129" -> i32Neg129Val = r.readInt32()
                "i32_128" -> i32128Val = r.readInt32()
                "i32_256" -> i32256Val = r.readInt32()
                "i32_65536" -> i3265536Val = r.readInt32()
                "i32_neg32769" -> i32Neg32769Val = r.readInt32()
                "u32_65536" -> u3265536Val = r.readUint32()
                else -> r.skip()
            }
        }
        r.endObject()
        EdgeBoundary(i32Neg129 = i32Neg129Val, i32128 = i32128Val, i32256 = i32256Val, i3265536 = i3265536Val, i32Neg32769 = i32Neg32769Val, u3265536 = u3265536Val)
    }
)

data class EdgeStrLen(
    val s31: String,
    val s32: String,
    val s255: String,
    val s256: String,
)

fun writeEdgeStrLen(w: SpecWriter, obj: EdgeStrLen) {
    w.beginObject(4)
    w.writeField("s31"); w.writeString(obj.s31)
    w.writeField("s32"); w.writeString(obj.s32)
    w.writeField("s255"); w.writeString(obj.s255)
    w.writeField("s256"); w.writeString(obj.s256)
    w.endObject()
}

val EdgeStrLenCodec: SpecCodec<EdgeStrLen> = SpecCodec(
    encode = { w, obj -> writeEdgeStrLen(w, obj) },
    decode = { r ->
        var s31Val: String = ""
        var s32Val: String = ""
        var s255Val: String = ""
        var s256Val: String = ""
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "s31" -> s31Val = r.readString()
                "s32" -> s32Val = r.readString()
                "s255" -> s255Val = r.readString()
                "s256" -> s256Val = r.readString()
                else -> r.skip()
            }
        }
        r.endObject()
        EdgeStrLen(s31 = s31Val, s32 = s32Val, s255 = s255Val, s256 = s256Val)
    }
)

data class EdgeBytesLen(
    val b31: ByteArray,
    val b32: ByteArray,
    val b255: ByteArray,
    val b256: ByteArray,
)

fun writeEdgeBytesLen(w: SpecWriter, obj: EdgeBytesLen) {
    w.beginObject(4)
    w.writeField("b31"); w.writeBytes(obj.b31)
    w.writeField("b32"); w.writeBytes(obj.b32)
    w.writeField("b255"); w.writeBytes(obj.b255)
    w.writeField("b256"); w.writeBytes(obj.b256)
    w.endObject()
}

val EdgeBytesLenCodec: SpecCodec<EdgeBytesLen> = SpecCodec(
    encode = { w, obj -> writeEdgeBytesLen(w, obj) },
    decode = { r ->
        var b31Val: ByteArray = byteArrayOf()
        var b32Val: ByteArray = byteArrayOf()
        var b255Val: ByteArray = byteArrayOf()
        var b256Val: ByteArray = byteArrayOf()
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "b31" -> b31Val = r.readBytes()
                "b32" -> b32Val = r.readBytes()
                "b255" -> b255Val = r.readBytes()
                "b256" -> b256Val = r.readBytes()
                else -> r.skip()
            }
        }
        r.endObject()
        EdgeBytesLen(b31 = b31Val, b32 = b32Val, b255 = b255Val, b256 = b256Val)
    }
)

data class EdgeArrEmpty(
    val items: List<String>,
)

fun writeEdgeArrEmpty(w: SpecWriter, obj: EdgeArrEmpty) {
    w.beginObject(1)
    w.writeField("items"); w.beginArray(obj.items.size)
        for (item in obj.items) { w.nextElement(); w.writeString(item) }
        w.endArray()
    w.endObject()
}

val EdgeArrEmptyCodec: SpecCodec<EdgeArrEmpty> = SpecCodec(
    encode = { w, obj -> writeEdgeArrEmpty(w, obj) },
    decode = { r ->
        var itemsVal: List<String> = emptyList()
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "items" -> itemsVal = run { val list = mutableListOf<String>(); r.beginArray(); while (r.hasNextElement()) { list.add(r.readString()) }; r.endArray(); list }
                else -> r.skip()
            }
        }
        r.endObject()
        EdgeArrEmpty(items = itemsVal)
    }
)

data class EdgeArrBoundary(
    val a15: List<Int>,
    val a16: List<Int>,
)

fun writeEdgeArrBoundary(w: SpecWriter, obj: EdgeArrBoundary) {
    w.beginObject(2)
    w.writeField("a15"); w.beginArray(obj.a15.size)
        for (item in obj.a15) { w.nextElement(); w.writeInt32(item) }
        w.endArray()
    w.writeField("a16"); w.beginArray(obj.a16.size)
        for (item in obj.a16) { w.nextElement(); w.writeInt32(item) }
        w.endArray()
    w.endObject()
}

val EdgeArrBoundaryCodec: SpecCodec<EdgeArrBoundary> = SpecCodec(
    encode = { w, obj -> writeEdgeArrBoundary(w, obj) },
    decode = { r ->
        var a15Val: List<Int> = emptyList()
        var a16Val: List<Int> = emptyList()
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a15" -> a15Val = run { val list = mutableListOf<Int>(); r.beginArray(); while (r.hasNextElement()) { list.add(r.readInt32()) }; r.endArray(); list }
                "a16" -> a16Val = run { val list = mutableListOf<Int>(); r.beginArray(); while (r.hasNextElement()) { list.add(r.readInt32()) }; r.endArray(); list }
                else -> r.skip()
            }
        }
        r.endObject()
        EdgeArrBoundary(a15 = a15Val, a16 = a16Val)
    }
)
