// Generated by @specodec/typespec-emitter-kotlin. DO NOT EDIT.
package all_types_wide

import specodec.*

data class Wide20(
    val f1: String,
    val f2: Boolean,
    val f3: Byte,
    val f4: Short,
    val f5: Int,
    val f6: Long,
    val f7: UByte,
    val f8: UShort,
    val f9: UInt,
    val f10: ULong,
    val f11: Float,
    val f12: Double,
    val f13: ByteArray,
    val f14: String,
    val f15: Boolean,
    val f16: Byte,
    val f17: Short,
    val f18: Int,
    val f19: Long,
    val f20: UByte,
)

fun writeWide20(w: SpecWriter, obj: Wide20) {
    w.beginObject(20)
    w.writeField("f1"); w.writeString(obj.f1)
    w.writeField("f2"); w.writeBool(obj.f2)
    w.writeField("f3"); w.writeInt32(obj.f3.toInt())
    w.writeField("f4"); w.writeInt32(obj.f4.toInt())
    w.writeField("f5"); w.writeInt32(obj.f5)
    w.writeField("f6"); w.writeInt64(obj.f6)
    w.writeField("f7"); w.writeUint32(obj.f7.toUInt())
    w.writeField("f8"); w.writeUint32(obj.f8.toUInt())
    w.writeField("f9"); w.writeUint32(obj.f9)
    w.writeField("f10"); w.writeUint64(obj.f10)
    w.writeField("f11"); w.writeFloat32(obj.f11)
    w.writeField("f12"); w.writeFloat64(obj.f12)
    w.writeField("f13"); w.writeBytes(obj.f13)
    w.writeField("f14"); w.writeString(obj.f14)
    w.writeField("f15"); w.writeBool(obj.f15)
    w.writeField("f16"); w.writeInt32(obj.f16.toInt())
    w.writeField("f17"); w.writeInt32(obj.f17.toInt())
    w.writeField("f18"); w.writeInt32(obj.f18)
    w.writeField("f19"); w.writeInt64(obj.f19)
    w.writeField("f20"); w.writeUint32(obj.f20.toUInt())
    w.endObject()
}

val Wide20Codec: SpecCodec<Wide20> = SpecCodec(
    encode = { w, obj -> writeWide20(w, obj) },
    decode = { r ->
        var f1Val: String = ""
        var f2Val: Boolean = false
        var f3Val: Byte = 0
        var f4Val: Short = 0
        var f5Val: Int = 0
        var f6Val: Long = 0L
        var f7Val: UByte = 0u
        var f8Val: UShort = 0u
        var f9Val: UInt = 0u
        var f10Val: ULong = 0uL
        var f11Val: Float = 0f
        var f12Val: Double = 0.0
        var f13Val: ByteArray = byteArrayOf()
        var f14Val: String = ""
        var f15Val: Boolean = false
        var f16Val: Byte = 0
        var f17Val: Short = 0
        var f18Val: Int = 0
        var f19Val: Long = 0L
        var f20Val: UByte = 0u
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "f1" -> f1Val = r.readString()
                "f2" -> f2Val = r.readBool()
                "f3" -> f3Val = r.readInt32().toByte()
                "f4" -> f4Val = r.readInt32().toShort()
                "f5" -> f5Val = r.readInt32()
                "f6" -> f6Val = r.readInt64()
                "f7" -> f7Val = r.readUint32().toUByte()
                "f8" -> f8Val = r.readUint32().toUShort()
                "f9" -> f9Val = r.readUint32()
                "f10" -> f10Val = r.readUint64()
                "f11" -> f11Val = r.readFloat32()
                "f12" -> f12Val = r.readFloat64()
                "f13" -> f13Val = r.readBytes()
                "f14" -> f14Val = r.readString()
                "f15" -> f15Val = r.readBool()
                "f16" -> f16Val = r.readInt32().toByte()
                "f17" -> f17Val = r.readInt32().toShort()
                "f18" -> f18Val = r.readInt32()
                "f19" -> f19Val = r.readInt64()
                "f20" -> f20Val = r.readUint32().toUByte()
                else -> r.skip()
            }
        }
        r.endObject()
        Wide20(f1 = f1Val, f2 = f2Val, f3 = f3Val, f4 = f4Val, f5 = f5Val, f6 = f6Val, f7 = f7Val, f8 = f8Val, f9 = f9Val, f10 = f10Val, f11 = f11Val, f12 = f12Val, f13 = f13Val, f14 = f14Val, f15 = f15Val, f16 = f16Val, f17 = f17Val, f18 = f18Val, f19 = f19Val, f20 = f20Val)
    }
)

data class Wide25(
    val f1: UShort,
    val f2: UInt,
    val f3: ULong,
    val f4: Float,
    val f5: Double,
    val f6: ByteArray,
    val f7: String,
    val f8: Boolean,
    val f9: Byte,
    val f10: Short,
    val f11: Int,
    val f12: Long,
    val f13: UByte,
    val f14: UShort,
    val f15: UInt,
    val f16: ULong,
    val f17: Float,
    val f18: Double,
    val f19: ByteArray,
    val f20: String,
    val f21: Boolean,
    val f22: Byte,
    val f23: Short,
    val f24: Int,
    val f25: Long,
)

fun writeWide25(w: SpecWriter, obj: Wide25) {
    w.beginObject(25)
    w.writeField("f1"); w.writeUint32(obj.f1.toUInt())
    w.writeField("f2"); w.writeUint32(obj.f2)
    w.writeField("f3"); w.writeUint64(obj.f3)
    w.writeField("f4"); w.writeFloat32(obj.f4)
    w.writeField("f5"); w.writeFloat64(obj.f5)
    w.writeField("f6"); w.writeBytes(obj.f6)
    w.writeField("f7"); w.writeString(obj.f7)
    w.writeField("f8"); w.writeBool(obj.f8)
    w.writeField("f9"); w.writeInt32(obj.f9.toInt())
    w.writeField("f10"); w.writeInt32(obj.f10.toInt())
    w.writeField("f11"); w.writeInt32(obj.f11)
    w.writeField("f12"); w.writeInt64(obj.f12)
    w.writeField("f13"); w.writeUint32(obj.f13.toUInt())
    w.writeField("f14"); w.writeUint32(obj.f14.toUInt())
    w.writeField("f15"); w.writeUint32(obj.f15)
    w.writeField("f16"); w.writeUint64(obj.f16)
    w.writeField("f17"); w.writeFloat32(obj.f17)
    w.writeField("f18"); w.writeFloat64(obj.f18)
    w.writeField("f19"); w.writeBytes(obj.f19)
    w.writeField("f20"); w.writeString(obj.f20)
    w.writeField("f21"); w.writeBool(obj.f21)
    w.writeField("f22"); w.writeInt32(obj.f22.toInt())
    w.writeField("f23"); w.writeInt32(obj.f23.toInt())
    w.writeField("f24"); w.writeInt32(obj.f24)
    w.writeField("f25"); w.writeInt64(obj.f25)
    w.endObject()
}

val Wide25Codec: SpecCodec<Wide25> = SpecCodec(
    encode = { w, obj -> writeWide25(w, obj) },
    decode = { r ->
        var f1Val: UShort = 0u
        var f2Val: UInt = 0u
        var f3Val: ULong = 0uL
        var f4Val: Float = 0f
        var f5Val: Double = 0.0
        var f6Val: ByteArray = byteArrayOf()
        var f7Val: String = ""
        var f8Val: Boolean = false
        var f9Val: Byte = 0
        var f10Val: Short = 0
        var f11Val: Int = 0
        var f12Val: Long = 0L
        var f13Val: UByte = 0u
        var f14Val: UShort = 0u
        var f15Val: UInt = 0u
        var f16Val: ULong = 0uL
        var f17Val: Float = 0f
        var f18Val: Double = 0.0
        var f19Val: ByteArray = byteArrayOf()
        var f20Val: String = ""
        var f21Val: Boolean = false
        var f22Val: Byte = 0
        var f23Val: Short = 0
        var f24Val: Int = 0
        var f25Val: Long = 0L
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "f1" -> f1Val = r.readUint32().toUShort()
                "f2" -> f2Val = r.readUint32()
                "f3" -> f3Val = r.readUint64()
                "f4" -> f4Val = r.readFloat32()
                "f5" -> f5Val = r.readFloat64()
                "f6" -> f6Val = r.readBytes()
                "f7" -> f7Val = r.readString()
                "f8" -> f8Val = r.readBool()
                "f9" -> f9Val = r.readInt32().toByte()
                "f10" -> f10Val = r.readInt32().toShort()
                "f11" -> f11Val = r.readInt32()
                "f12" -> f12Val = r.readInt64()
                "f13" -> f13Val = r.readUint32().toUByte()
                "f14" -> f14Val = r.readUint32().toUShort()
                "f15" -> f15Val = r.readUint32()
                "f16" -> f16Val = r.readUint64()
                "f17" -> f17Val = r.readFloat32()
                "f18" -> f18Val = r.readFloat64()
                "f19" -> f19Val = r.readBytes()
                "f20" -> f20Val = r.readString()
                "f21" -> f21Val = r.readBool()
                "f22" -> f22Val = r.readInt32().toByte()
                "f23" -> f23Val = r.readInt32().toShort()
                "f24" -> f24Val = r.readInt32()
                "f25" -> f25Val = r.readInt64()
                else -> r.skip()
            }
        }
        r.endObject()
        Wide25(f1 = f1Val, f2 = f2Val, f3 = f3Val, f4 = f4Val, f5 = f5Val, f6 = f6Val, f7 = f7Val, f8 = f8Val, f9 = f9Val, f10 = f10Val, f11 = f11Val, f12 = f12Val, f13 = f13Val, f14 = f14Val, f15 = f15Val, f16 = f16Val, f17 = f17Val, f18 = f18Val, f19 = f19Val, f20 = f20Val, f21 = f21Val, f22 = f22Val, f23 = f23Val, f24 = f24Val, f25 = f25Val)
    }
)

data class Wide30(
    val f1: Boolean,
    val f2: Byte,
    val f3: Short,
    val f4: Int,
    val f5: Long,
    val f6: UByte,
    val f7: UShort,
    val f8: UInt,
    val f9: ULong,
    val f10: Float,
    val f11: Double,
    val f12: ByteArray,
    val f13: String,
    val f14: Boolean,
    val f15: Byte,
    val f16: Short,
    val f17: Int,
    val f18: Long,
    val f19: UByte,
    val f20: UShort,
    val f21: UInt,
    val f22: ULong,
    val f23: Float,
    val f24: Double,
    val f25: ByteArray,
    val f26: String,
    val f27: Boolean,
    val f28: Byte,
    val f29: Short,
    val f30: Int,
)

fun writeWide30(w: SpecWriter, obj: Wide30) {
    w.beginObject(30)
    w.writeField("f1"); w.writeBool(obj.f1)
    w.writeField("f2"); w.writeInt32(obj.f2.toInt())
    w.writeField("f3"); w.writeInt32(obj.f3.toInt())
    w.writeField("f4"); w.writeInt32(obj.f4)
    w.writeField("f5"); w.writeInt64(obj.f5)
    w.writeField("f6"); w.writeUint32(obj.f6.toUInt())
    w.writeField("f7"); w.writeUint32(obj.f7.toUInt())
    w.writeField("f8"); w.writeUint32(obj.f8)
    w.writeField("f9"); w.writeUint64(obj.f9)
    w.writeField("f10"); w.writeFloat32(obj.f10)
    w.writeField("f11"); w.writeFloat64(obj.f11)
    w.writeField("f12"); w.writeBytes(obj.f12)
    w.writeField("f13"); w.writeString(obj.f13)
    w.writeField("f14"); w.writeBool(obj.f14)
    w.writeField("f15"); w.writeInt32(obj.f15.toInt())
    w.writeField("f16"); w.writeInt32(obj.f16.toInt())
    w.writeField("f17"); w.writeInt32(obj.f17)
    w.writeField("f18"); w.writeInt64(obj.f18)
    w.writeField("f19"); w.writeUint32(obj.f19.toUInt())
    w.writeField("f20"); w.writeUint32(obj.f20.toUInt())
    w.writeField("f21"); w.writeUint32(obj.f21)
    w.writeField("f22"); w.writeUint64(obj.f22)
    w.writeField("f23"); w.writeFloat32(obj.f23)
    w.writeField("f24"); w.writeFloat64(obj.f24)
    w.writeField("f25"); w.writeBytes(obj.f25)
    w.writeField("f26"); w.writeString(obj.f26)
    w.writeField("f27"); w.writeBool(obj.f27)
    w.writeField("f28"); w.writeInt32(obj.f28.toInt())
    w.writeField("f29"); w.writeInt32(obj.f29.toInt())
    w.writeField("f30"); w.writeInt32(obj.f30)
    w.endObject()
}

val Wide30Codec: SpecCodec<Wide30> = SpecCodec(
    encode = { w, obj -> writeWide30(w, obj) },
    decode = { r ->
        var f1Val: Boolean = false
        var f2Val: Byte = 0
        var f3Val: Short = 0
        var f4Val: Int = 0
        var f5Val: Long = 0L
        var f6Val: UByte = 0u
        var f7Val: UShort = 0u
        var f8Val: UInt = 0u
        var f9Val: ULong = 0uL
        var f10Val: Float = 0f
        var f11Val: Double = 0.0
        var f12Val: ByteArray = byteArrayOf()
        var f13Val: String = ""
        var f14Val: Boolean = false
        var f15Val: Byte = 0
        var f16Val: Short = 0
        var f17Val: Int = 0
        var f18Val: Long = 0L
        var f19Val: UByte = 0u
        var f20Val: UShort = 0u
        var f21Val: UInt = 0u
        var f22Val: ULong = 0uL
        var f23Val: Float = 0f
        var f24Val: Double = 0.0
        var f25Val: ByteArray = byteArrayOf()
        var f26Val: String = ""
        var f27Val: Boolean = false
        var f28Val: Byte = 0
        var f29Val: Short = 0
        var f30Val: Int = 0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "f1" -> f1Val = r.readBool()
                "f2" -> f2Val = r.readInt32().toByte()
                "f3" -> f3Val = r.readInt32().toShort()
                "f4" -> f4Val = r.readInt32()
                "f5" -> f5Val = r.readInt64()
                "f6" -> f6Val = r.readUint32().toUByte()
                "f7" -> f7Val = r.readUint32().toUShort()
                "f8" -> f8Val = r.readUint32()
                "f9" -> f9Val = r.readUint64()
                "f10" -> f10Val = r.readFloat32()
                "f11" -> f11Val = r.readFloat64()
                "f12" -> f12Val = r.readBytes()
                "f13" -> f13Val = r.readString()
                "f14" -> f14Val = r.readBool()
                "f15" -> f15Val = r.readInt32().toByte()
                "f16" -> f16Val = r.readInt32().toShort()
                "f17" -> f17Val = r.readInt32()
                "f18" -> f18Val = r.readInt64()
                "f19" -> f19Val = r.readUint32().toUByte()
                "f20" -> f20Val = r.readUint32().toUShort()
                "f21" -> f21Val = r.readUint32()
                "f22" -> f22Val = r.readUint64()
                "f23" -> f23Val = r.readFloat32()
                "f24" -> f24Val = r.readFloat64()
                "f25" -> f25Val = r.readBytes()
                "f26" -> f26Val = r.readString()
                "f27" -> f27Val = r.readBool()
                "f28" -> f28Val = r.readInt32().toByte()
                "f29" -> f29Val = r.readInt32().toShort()
                "f30" -> f30Val = r.readInt32()
                else -> r.skip()
            }
        }
        r.endObject()
        Wide30(f1 = f1Val, f2 = f2Val, f3 = f3Val, f4 = f4Val, f5 = f5Val, f6 = f6Val, f7 = f7Val, f8 = f8Val, f9 = f9Val, f10 = f10Val, f11 = f11Val, f12 = f12Val, f13 = f13Val, f14 = f14Val, f15 = f15Val, f16 = f16Val, f17 = f17Val, f18 = f18Val, f19 = f19Val, f20 = f20Val, f21 = f21Val, f22 = f22Val, f23 = f23Val, f24 = f24Val, f25 = f25Val, f26 = f26Val, f27 = f27Val, f28 = f28Val, f29 = f29Val, f30 = f30Val)
    }
)

data class Wide35(
    val f1: UInt,
    val f2: ULong,
    val f3: Float,
    val f4: Double,
    val f5: ByteArray,
    val f6: String,
    val f7: Boolean,
    val f8: Byte,
    val f9: Short,
    val f10: Int,
    val f11: Long,
    val f12: UByte,
    val f13: UShort,
    val f14: UInt,
    val f15: ULong,
    val f16: Float,
    val f17: Double,
    val f18: ByteArray,
    val f19: String,
    val f20: Boolean,
    val f21: Byte,
    val f22: Short,
    val f23: Int,
    val f24: Long,
    val f25: UByte,
    val f26: UShort,
    val f27: UInt,
    val f28: ULong,
    val f29: Float,
    val f30: Double,
    val f31: ByteArray,
    val f32: String,
    val f33: Boolean,
    val f34: Byte,
    val f35: Short,
)

fun writeWide35(w: SpecWriter, obj: Wide35) {
    w.beginObject(35)
    w.writeField("f1"); w.writeUint32(obj.f1)
    w.writeField("f2"); w.writeUint64(obj.f2)
    w.writeField("f3"); w.writeFloat32(obj.f3)
    w.writeField("f4"); w.writeFloat64(obj.f4)
    w.writeField("f5"); w.writeBytes(obj.f5)
    w.writeField("f6"); w.writeString(obj.f6)
    w.writeField("f7"); w.writeBool(obj.f7)
    w.writeField("f8"); w.writeInt32(obj.f8.toInt())
    w.writeField("f9"); w.writeInt32(obj.f9.toInt())
    w.writeField("f10"); w.writeInt32(obj.f10)
    w.writeField("f11"); w.writeInt64(obj.f11)
    w.writeField("f12"); w.writeUint32(obj.f12.toUInt())
    w.writeField("f13"); w.writeUint32(obj.f13.toUInt())
    w.writeField("f14"); w.writeUint32(obj.f14)
    w.writeField("f15"); w.writeUint64(obj.f15)
    w.writeField("f16"); w.writeFloat32(obj.f16)
    w.writeField("f17"); w.writeFloat64(obj.f17)
    w.writeField("f18"); w.writeBytes(obj.f18)
    w.writeField("f19"); w.writeString(obj.f19)
    w.writeField("f20"); w.writeBool(obj.f20)
    w.writeField("f21"); w.writeInt32(obj.f21.toInt())
    w.writeField("f22"); w.writeInt32(obj.f22.toInt())
    w.writeField("f23"); w.writeInt32(obj.f23)
    w.writeField("f24"); w.writeInt64(obj.f24)
    w.writeField("f25"); w.writeUint32(obj.f25.toUInt())
    w.writeField("f26"); w.writeUint32(obj.f26.toUInt())
    w.writeField("f27"); w.writeUint32(obj.f27)
    w.writeField("f28"); w.writeUint64(obj.f28)
    w.writeField("f29"); w.writeFloat32(obj.f29)
    w.writeField("f30"); w.writeFloat64(obj.f30)
    w.writeField("f31"); w.writeBytes(obj.f31)
    w.writeField("f32"); w.writeString(obj.f32)
    w.writeField("f33"); w.writeBool(obj.f33)
    w.writeField("f34"); w.writeInt32(obj.f34.toInt())
    w.writeField("f35"); w.writeInt32(obj.f35.toInt())
    w.endObject()
}

val Wide35Codec: SpecCodec<Wide35> = SpecCodec(
    encode = { w, obj -> writeWide35(w, obj) },
    decode = { r ->
        var f1Val: UInt = 0u
        var f2Val: ULong = 0uL
        var f3Val: Float = 0f
        var f4Val: Double = 0.0
        var f5Val: ByteArray = byteArrayOf()
        var f6Val: String = ""
        var f7Val: Boolean = false
        var f8Val: Byte = 0
        var f9Val: Short = 0
        var f10Val: Int = 0
        var f11Val: Long = 0L
        var f12Val: UByte = 0u
        var f13Val: UShort = 0u
        var f14Val: UInt = 0u
        var f15Val: ULong = 0uL
        var f16Val: Float = 0f
        var f17Val: Double = 0.0
        var f18Val: ByteArray = byteArrayOf()
        var f19Val: String = ""
        var f20Val: Boolean = false
        var f21Val: Byte = 0
        var f22Val: Short = 0
        var f23Val: Int = 0
        var f24Val: Long = 0L
        var f25Val: UByte = 0u
        var f26Val: UShort = 0u
        var f27Val: UInt = 0u
        var f28Val: ULong = 0uL
        var f29Val: Float = 0f
        var f30Val: Double = 0.0
        var f31Val: ByteArray = byteArrayOf()
        var f32Val: String = ""
        var f33Val: Boolean = false
        var f34Val: Byte = 0
        var f35Val: Short = 0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "f1" -> f1Val = r.readUint32()
                "f2" -> f2Val = r.readUint64()
                "f3" -> f3Val = r.readFloat32()
                "f4" -> f4Val = r.readFloat64()
                "f5" -> f5Val = r.readBytes()
                "f6" -> f6Val = r.readString()
                "f7" -> f7Val = r.readBool()
                "f8" -> f8Val = r.readInt32().toByte()
                "f9" -> f9Val = r.readInt32().toShort()
                "f10" -> f10Val = r.readInt32()
                "f11" -> f11Val = r.readInt64()
                "f12" -> f12Val = r.readUint32().toUByte()
                "f13" -> f13Val = r.readUint32().toUShort()
                "f14" -> f14Val = r.readUint32()
                "f15" -> f15Val = r.readUint64()
                "f16" -> f16Val = r.readFloat32()
                "f17" -> f17Val = r.readFloat64()
                "f18" -> f18Val = r.readBytes()
                "f19" -> f19Val = r.readString()
                "f20" -> f20Val = r.readBool()
                "f21" -> f21Val = r.readInt32().toByte()
                "f22" -> f22Val = r.readInt32().toShort()
                "f23" -> f23Val = r.readInt32()
                "f24" -> f24Val = r.readInt64()
                "f25" -> f25Val = r.readUint32().toUByte()
                "f26" -> f26Val = r.readUint32().toUShort()
                "f27" -> f27Val = r.readUint32()
                "f28" -> f28Val = r.readUint64()
                "f29" -> f29Val = r.readFloat32()
                "f30" -> f30Val = r.readFloat64()
                "f31" -> f31Val = r.readBytes()
                "f32" -> f32Val = r.readString()
                "f33" -> f33Val = r.readBool()
                "f34" -> f34Val = r.readInt32().toByte()
                "f35" -> f35Val = r.readInt32().toShort()
                else -> r.skip()
            }
        }
        r.endObject()
        Wide35(f1 = f1Val, f2 = f2Val, f3 = f3Val, f4 = f4Val, f5 = f5Val, f6 = f6Val, f7 = f7Val, f8 = f8Val, f9 = f9Val, f10 = f10Val, f11 = f11Val, f12 = f12Val, f13 = f13Val, f14 = f14Val, f15 = f15Val, f16 = f16Val, f17 = f17Val, f18 = f18Val, f19 = f19Val, f20 = f20Val, f21 = f21Val, f22 = f22Val, f23 = f23Val, f24 = f24Val, f25 = f25Val, f26 = f26Val, f27 = f27Val, f28 = f28Val, f29 = f29Val, f30 = f30Val, f31 = f31Val, f32 = f32Val, f33 = f33Val, f34 = f34Val, f35 = f35Val)
    }
)

data class Wide40(
    val f1: Byte,
    val f2: Short,
    val f3: Int,
    val f4: Long,
    val f5: UByte,
    val f6: UShort,
    val f7: UInt,
    val f8: ULong,
    val f9: Float,
    val f10: Double,
    val f11: ByteArray,
    val f12: String,
    val f13: Boolean,
    val f14: Byte,
    val f15: Short,
    val f16: Int,
    val f17: Long,
    val f18: UByte,
    val f19: UShort,
    val f20: UInt,
    val f21: ULong,
    val f22: Float,
    val f23: Double,
    val f24: ByteArray,
    val f25: String,
    val f26: Boolean,
    val f27: Byte,
    val f28: Short,
    val f29: Int,
    val f30: Long,
    val f31: UByte,
    val f32: UShort,
    val f33: UInt,
    val f34: ULong,
    val f35: Float,
    val f36: Double,
    val f37: ByteArray,
    val f38: String,
    val f39: Boolean,
    val f40: Byte,
)

fun writeWide40(w: SpecWriter, obj: Wide40) {
    w.beginObject(40)
    w.writeField("f1"); w.writeInt32(obj.f1.toInt())
    w.writeField("f2"); w.writeInt32(obj.f2.toInt())
    w.writeField("f3"); w.writeInt32(obj.f3)
    w.writeField("f4"); w.writeInt64(obj.f4)
    w.writeField("f5"); w.writeUint32(obj.f5.toUInt())
    w.writeField("f6"); w.writeUint32(obj.f6.toUInt())
    w.writeField("f7"); w.writeUint32(obj.f7)
    w.writeField("f8"); w.writeUint64(obj.f8)
    w.writeField("f9"); w.writeFloat32(obj.f9)
    w.writeField("f10"); w.writeFloat64(obj.f10)
    w.writeField("f11"); w.writeBytes(obj.f11)
    w.writeField("f12"); w.writeString(obj.f12)
    w.writeField("f13"); w.writeBool(obj.f13)
    w.writeField("f14"); w.writeInt32(obj.f14.toInt())
    w.writeField("f15"); w.writeInt32(obj.f15.toInt())
    w.writeField("f16"); w.writeInt32(obj.f16)
    w.writeField("f17"); w.writeInt64(obj.f17)
    w.writeField("f18"); w.writeUint32(obj.f18.toUInt())
    w.writeField("f19"); w.writeUint32(obj.f19.toUInt())
    w.writeField("f20"); w.writeUint32(obj.f20)
    w.writeField("f21"); w.writeUint64(obj.f21)
    w.writeField("f22"); w.writeFloat32(obj.f22)
    w.writeField("f23"); w.writeFloat64(obj.f23)
    w.writeField("f24"); w.writeBytes(obj.f24)
    w.writeField("f25"); w.writeString(obj.f25)
    w.writeField("f26"); w.writeBool(obj.f26)
    w.writeField("f27"); w.writeInt32(obj.f27.toInt())
    w.writeField("f28"); w.writeInt32(obj.f28.toInt())
    w.writeField("f29"); w.writeInt32(obj.f29)
    w.writeField("f30"); w.writeInt64(obj.f30)
    w.writeField("f31"); w.writeUint32(obj.f31.toUInt())
    w.writeField("f32"); w.writeUint32(obj.f32.toUInt())
    w.writeField("f33"); w.writeUint32(obj.f33)
    w.writeField("f34"); w.writeUint64(obj.f34)
    w.writeField("f35"); w.writeFloat32(obj.f35)
    w.writeField("f36"); w.writeFloat64(obj.f36)
    w.writeField("f37"); w.writeBytes(obj.f37)
    w.writeField("f38"); w.writeString(obj.f38)
    w.writeField("f39"); w.writeBool(obj.f39)
    w.writeField("f40"); w.writeInt32(obj.f40.toInt())
    w.endObject()
}

val Wide40Codec: SpecCodec<Wide40> = SpecCodec(
    encode = { w, obj -> writeWide40(w, obj) },
    decode = { r ->
        var f1Val: Byte = 0
        var f2Val: Short = 0
        var f3Val: Int = 0
        var f4Val: Long = 0L
        var f5Val: UByte = 0u
        var f6Val: UShort = 0u
        var f7Val: UInt = 0u
        var f8Val: ULong = 0uL
        var f9Val: Float = 0f
        var f10Val: Double = 0.0
        var f11Val: ByteArray = byteArrayOf()
        var f12Val: String = ""
        var f13Val: Boolean = false
        var f14Val: Byte = 0
        var f15Val: Short = 0
        var f16Val: Int = 0
        var f17Val: Long = 0L
        var f18Val: UByte = 0u
        var f19Val: UShort = 0u
        var f20Val: UInt = 0u
        var f21Val: ULong = 0uL
        var f22Val: Float = 0f
        var f23Val: Double = 0.0
        var f24Val: ByteArray = byteArrayOf()
        var f25Val: String = ""
        var f26Val: Boolean = false
        var f27Val: Byte = 0
        var f28Val: Short = 0
        var f29Val: Int = 0
        var f30Val: Long = 0L
        var f31Val: UByte = 0u
        var f32Val: UShort = 0u
        var f33Val: UInt = 0u
        var f34Val: ULong = 0uL
        var f35Val: Float = 0f
        var f36Val: Double = 0.0
        var f37Val: ByteArray = byteArrayOf()
        var f38Val: String = ""
        var f39Val: Boolean = false
        var f40Val: Byte = 0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "f1" -> f1Val = r.readInt32().toByte()
                "f2" -> f2Val = r.readInt32().toShort()
                "f3" -> f3Val = r.readInt32()
                "f4" -> f4Val = r.readInt64()
                "f5" -> f5Val = r.readUint32().toUByte()
                "f6" -> f6Val = r.readUint32().toUShort()
                "f7" -> f7Val = r.readUint32()
                "f8" -> f8Val = r.readUint64()
                "f9" -> f9Val = r.readFloat32()
                "f10" -> f10Val = r.readFloat64()
                "f11" -> f11Val = r.readBytes()
                "f12" -> f12Val = r.readString()
                "f13" -> f13Val = r.readBool()
                "f14" -> f14Val = r.readInt32().toByte()
                "f15" -> f15Val = r.readInt32().toShort()
                "f16" -> f16Val = r.readInt32()
                "f17" -> f17Val = r.readInt64()
                "f18" -> f18Val = r.readUint32().toUByte()
                "f19" -> f19Val = r.readUint32().toUShort()
                "f20" -> f20Val = r.readUint32()
                "f21" -> f21Val = r.readUint64()
                "f22" -> f22Val = r.readFloat32()
                "f23" -> f23Val = r.readFloat64()
                "f24" -> f24Val = r.readBytes()
                "f25" -> f25Val = r.readString()
                "f26" -> f26Val = r.readBool()
                "f27" -> f27Val = r.readInt32().toByte()
                "f28" -> f28Val = r.readInt32().toShort()
                "f29" -> f29Val = r.readInt32()
                "f30" -> f30Val = r.readInt64()
                "f31" -> f31Val = r.readUint32().toUByte()
                "f32" -> f32Val = r.readUint32().toUShort()
                "f33" -> f33Val = r.readUint32()
                "f34" -> f34Val = r.readUint64()
                "f35" -> f35Val = r.readFloat32()
                "f36" -> f36Val = r.readFloat64()
                "f37" -> f37Val = r.readBytes()
                "f38" -> f38Val = r.readString()
                "f39" -> f39Val = r.readBool()
                "f40" -> f40Val = r.readInt32().toByte()
                else -> r.skip()
            }
        }
        r.endObject()
        Wide40(f1 = f1Val, f2 = f2Val, f3 = f3Val, f4 = f4Val, f5 = f5Val, f6 = f6Val, f7 = f7Val, f8 = f8Val, f9 = f9Val, f10 = f10Val, f11 = f11Val, f12 = f12Val, f13 = f13Val, f14 = f14Val, f15 = f15Val, f16 = f16Val, f17 = f17Val, f18 = f18Val, f19 = f19Val, f20 = f20Val, f21 = f21Val, f22 = f22Val, f23 = f23Val, f24 = f24Val, f25 = f25Val, f26 = f26Val, f27 = f27Val, f28 = f28Val, f29 = f29Val, f30 = f30Val, f31 = f31Val, f32 = f32Val, f33 = f33Val, f34 = f34Val, f35 = f35Val, f36 = f36Val, f37 = f37Val, f38 = f38Val, f39 = f39Val, f40 = f40Val)
    }
)
