// Generated by @specodec/typespec-emitter-kotlin. DO NOT EDIT.
package all_types_nests

import specodec.*
import all_types.*

data class NestInner(
    val nested: Inner,
)

fun writeNestInner(w: SpecWriter, obj: NestInner) {
    w.beginObject(1)
    w.writeField("nested"); writeInner(w, obj.nested)
    w.endObject()
}

val NestInnerCodec: SpecCodec<NestInner> = SpecCodec(
    encode = { w, obj -> writeNestInner(w, obj) },
    decode = { r ->
        var nestedVal: Inner? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "nested" -> nestedVal = InnerCodec.decode(r)
                else -> r.skip()
            }
        }
        r.endObject()
        NestInner(nested = nestedVal!!)
    }
)

data class NestCoord(
    val nested: Coord,
)

fun writeNestCoord(w: SpecWriter, obj: NestCoord) {
    w.beginObject(1)
    w.writeField("nested"); writeCoord(w, obj.nested)
    w.endObject()
}

val NestCoordCodec: SpecCodec<NestCoord> = SpecCodec(
    encode = { w, obj -> writeNestCoord(w, obj) },
    decode = { r ->
        var nestedVal: Coord? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "nested" -> nestedVal = CoordCodec.decode(r)
                else -> r.skip()
            }
        }
        r.endObject()
        NestCoord(nested = nestedVal!!)
    }
)

data class NestIdVal(
    val nested: IdVal,
)

fun writeNestIdVal(w: SpecWriter, obj: NestIdVal) {
    w.beginObject(1)
    w.writeField("nested"); writeIdVal(w, obj.nested)
    w.endObject()
}

val NestIdValCodec: SpecCodec<NestIdVal> = SpecCodec(
    encode = { w, obj -> writeNestIdVal(w, obj) },
    decode = { r ->
        var nestedVal: IdVal? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "nested" -> nestedVal = IdValCodec.decode(r)
                else -> r.skip()
            }
        }
        r.endObject()
        NestIdVal(nested = nestedVal!!)
    }
)

data class NestLabel(
    val nested: Label,
)

fun writeNestLabel(w: SpecWriter, obj: NestLabel) {
    w.beginObject(1)
    w.writeField("nested"); writeLabel(w, obj.nested)
    w.endObject()
}

val NestLabelCodec: SpecCodec<NestLabel> = SpecCodec(
    encode = { w, obj -> writeNestLabel(w, obj) },
    decode = { r ->
        var nestedVal: Label? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "nested" -> nestedVal = LabelCodec.decode(r)
                else -> r.skip()
            }
        }
        r.endObject()
        NestLabel(nested = nestedVal!!)
    }
)

data class NestMoney(
    val nested: Money,
)

fun writeNestMoney(w: SpecWriter, obj: NestMoney) {
    w.beginObject(1)
    w.writeField("nested"); writeMoney(w, obj.nested)
    w.endObject()
}

val NestMoneyCodec: SpecCodec<NestMoney> = SpecCodec(
    encode = { w, obj -> writeNestMoney(w, obj) },
    decode = { r ->
        var nestedVal: Money? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "nested" -> nestedVal = MoneyCodec.decode(r)
                else -> r.skip()
            }
        }
        r.endObject()
        NestMoney(nested = nestedVal!!)
    }
)

data class NestRange32(
    val nested: Range32,
)

fun writeNestRange32(w: SpecWriter, obj: NestRange32) {
    w.beginObject(1)
    w.writeField("nested"); writeRange32(w, obj.nested)
    w.endObject()
}

val NestRange32Codec: SpecCodec<NestRange32> = SpecCodec(
    encode = { w, obj -> writeNestRange32(w, obj) },
    decode = { r ->
        var nestedVal: Range32? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "nested" -> nestedVal = Range32Codec.decode(r)
                else -> r.skip()
            }
        }
        r.endObject()
        NestRange32(nested = nestedVal!!)
    }
)

data class NestAddr(
    val nested: Addr,
)

fun writeNestAddr(w: SpecWriter, obj: NestAddr) {
    w.beginObject(1)
    w.writeField("nested"); writeAddr(w, obj.nested)
    w.endObject()
}

val NestAddrCodec: SpecCodec<NestAddr> = SpecCodec(
    encode = { w, obj -> writeNestAddr(w, obj) },
    decode = { r ->
        var nestedVal: Addr? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "nested" -> nestedVal = AddrCodec.decode(r)
                else -> r.skip()
            }
        }
        r.endObject()
        NestAddr(nested = nestedVal!!)
    }
)

data class NestPoint3(
    val nested: Point3,
)

fun writeNestPoint3(w: SpecWriter, obj: NestPoint3) {
    w.beginObject(1)
    w.writeField("nested"); writePoint3(w, obj.nested)
    w.endObject()
}

val NestPoint3Codec: SpecCodec<NestPoint3> = SpecCodec(
    encode = { w, obj -> writeNestPoint3(w, obj) },
    decode = { r ->
        var nestedVal: Point3? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "nested" -> nestedVal = Point3Codec.decode(r)
                else -> r.skip()
            }
        }
        r.endObject()
        NestPoint3(nested = nestedVal!!)
    }
)

data class OptNestInner(
    val label: String,
    val nested: Inner? = null,
)

fun writeOptNestInner(w: SpecWriter, obj: OptNestInner) {
    var fieldCount = 1
    if (obj.nested != null) fieldCount++
    w.beginObject(fieldCount)
    w.writeField("label"); w.writeString(obj.label)
    if (obj.nested != null) { w.writeField("nested"); writeInner(w, obj.nested) }
    w.endObject()
}

val OptNestInnerCodec: SpecCodec<OptNestInner> = SpecCodec(
    encode = { w, obj -> writeOptNestInner(w, obj) },
    decode = { r ->
        var labelVal: String = ""
        var nestedVal: Inner? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "label" -> labelVal = r.readString()
                "nested" -> nestedVal = if (r.isNull()) { r.readNull(); null } else { InnerCodec.decode(r) }
                else -> r.skip()
            }
        }
        r.endObject()
        OptNestInner(label = labelVal, nested = nestedVal)
    }
)

data class OptNestCoord(
    val label: String,
    val nested: Coord? = null,
)

fun writeOptNestCoord(w: SpecWriter, obj: OptNestCoord) {
    var fieldCount = 1
    if (obj.nested != null) fieldCount++
    w.beginObject(fieldCount)
    w.writeField("label"); w.writeString(obj.label)
    if (obj.nested != null) { w.writeField("nested"); writeCoord(w, obj.nested) }
    w.endObject()
}

val OptNestCoordCodec: SpecCodec<OptNestCoord> = SpecCodec(
    encode = { w, obj -> writeOptNestCoord(w, obj) },
    decode = { r ->
        var labelVal: String = ""
        var nestedVal: Coord? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "label" -> labelVal = r.readString()
                "nested" -> nestedVal = if (r.isNull()) { r.readNull(); null } else { CoordCodec.decode(r) }
                else -> r.skip()
            }
        }
        r.endObject()
        OptNestCoord(label = labelVal, nested = nestedVal)
    }
)

data class OptNestIdVal(
    val label: String,
    val nested: IdVal? = null,
)

fun writeOptNestIdVal(w: SpecWriter, obj: OptNestIdVal) {
    var fieldCount = 1
    if (obj.nested != null) fieldCount++
    w.beginObject(fieldCount)
    w.writeField("label"); w.writeString(obj.label)
    if (obj.nested != null) { w.writeField("nested"); writeIdVal(w, obj.nested) }
    w.endObject()
}

val OptNestIdValCodec: SpecCodec<OptNestIdVal> = SpecCodec(
    encode = { w, obj -> writeOptNestIdVal(w, obj) },
    decode = { r ->
        var labelVal: String = ""
        var nestedVal: IdVal? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "label" -> labelVal = r.readString()
                "nested" -> nestedVal = if (r.isNull()) { r.readNull(); null } else { IdValCodec.decode(r) }
                else -> r.skip()
            }
        }
        r.endObject()
        OptNestIdVal(label = labelVal, nested = nestedVal)
    }
)

data class OptNestLabel(
    val label: String,
    val nested: Label? = null,
)

fun writeOptNestLabel(w: SpecWriter, obj: OptNestLabel) {
    var fieldCount = 1
    if (obj.nested != null) fieldCount++
    w.beginObject(fieldCount)
    w.writeField("label"); w.writeString(obj.label)
    if (obj.nested != null) { w.writeField("nested"); writeLabel(w, obj.nested) }
    w.endObject()
}

val OptNestLabelCodec: SpecCodec<OptNestLabel> = SpecCodec(
    encode = { w, obj -> writeOptNestLabel(w, obj) },
    decode = { r ->
        var labelVal: String = ""
        var nestedVal: Label? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "label" -> labelVal = r.readString()
                "nested" -> nestedVal = if (r.isNull()) { r.readNull(); null } else { LabelCodec.decode(r) }
                else -> r.skip()
            }
        }
        r.endObject()
        OptNestLabel(label = labelVal, nested = nestedVal)
    }
)

data class OptNestMoney(
    val label: String,
    val nested: Money? = null,
)

fun writeOptNestMoney(w: SpecWriter, obj: OptNestMoney) {
    var fieldCount = 1
    if (obj.nested != null) fieldCount++
    w.beginObject(fieldCount)
    w.writeField("label"); w.writeString(obj.label)
    if (obj.nested != null) { w.writeField("nested"); writeMoney(w, obj.nested) }
    w.endObject()
}

val OptNestMoneyCodec: SpecCodec<OptNestMoney> = SpecCodec(
    encode = { w, obj -> writeOptNestMoney(w, obj) },
    decode = { r ->
        var labelVal: String = ""
        var nestedVal: Money? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "label" -> labelVal = r.readString()
                "nested" -> nestedVal = if (r.isNull()) { r.readNull(); null } else { MoneyCodec.decode(r) }
                else -> r.skip()
            }
        }
        r.endObject()
        OptNestMoney(label = labelVal, nested = nestedVal)
    }
)

data class OptNestRange32(
    val label: String,
    val nested: Range32? = null,
)

fun writeOptNestRange32(w: SpecWriter, obj: OptNestRange32) {
    var fieldCount = 1
    if (obj.nested != null) fieldCount++
    w.beginObject(fieldCount)
    w.writeField("label"); w.writeString(obj.label)
    if (obj.nested != null) { w.writeField("nested"); writeRange32(w, obj.nested) }
    w.endObject()
}

val OptNestRange32Codec: SpecCodec<OptNestRange32> = SpecCodec(
    encode = { w, obj -> writeOptNestRange32(w, obj) },
    decode = { r ->
        var labelVal: String = ""
        var nestedVal: Range32? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "label" -> labelVal = r.readString()
                "nested" -> nestedVal = if (r.isNull()) { r.readNull(); null } else { Range32Codec.decode(r) }
                else -> r.skip()
            }
        }
        r.endObject()
        OptNestRange32(label = labelVal, nested = nestedVal)
    }
)

data class OptNestAddr(
    val label: String,
    val nested: Addr? = null,
)

fun writeOptNestAddr(w: SpecWriter, obj: OptNestAddr) {
    var fieldCount = 1
    if (obj.nested != null) fieldCount++
    w.beginObject(fieldCount)
    w.writeField("label"); w.writeString(obj.label)
    if (obj.nested != null) { w.writeField("nested"); writeAddr(w, obj.nested) }
    w.endObject()
}

val OptNestAddrCodec: SpecCodec<OptNestAddr> = SpecCodec(
    encode = { w, obj -> writeOptNestAddr(w, obj) },
    decode = { r ->
        var labelVal: String = ""
        var nestedVal: Addr? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "label" -> labelVal = r.readString()
                "nested" -> nestedVal = if (r.isNull()) { r.readNull(); null } else { AddrCodec.decode(r) }
                else -> r.skip()
            }
        }
        r.endObject()
        OptNestAddr(label = labelVal, nested = nestedVal)
    }
)

data class OptNestPoint3(
    val label: String,
    val nested: Point3? = null,
)

fun writeOptNestPoint3(w: SpecWriter, obj: OptNestPoint3) {
    var fieldCount = 1
    if (obj.nested != null) fieldCount++
    w.beginObject(fieldCount)
    w.writeField("label"); w.writeString(obj.label)
    if (obj.nested != null) { w.writeField("nested"); writePoint3(w, obj.nested) }
    w.endObject()
}

val OptNestPoint3Codec: SpecCodec<OptNestPoint3> = SpecCodec(
    encode = { w, obj -> writeOptNestPoint3(w, obj) },
    decode = { r ->
        var labelVal: String = ""
        var nestedVal: Point3? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "label" -> labelVal = r.readString()
                "nested" -> nestedVal = if (r.isNull()) { r.readNull(); null } else { Point3Codec.decode(r) }
                else -> r.skip()
            }
        }
        r.endObject()
        OptNestPoint3(label = labelVal, nested = nestedVal)
    }
)
