// Generated by @specodec/typespec-emitter-kotlin. DO NOT EDIT.
package all_types_nested

import specodec.*

data class NestedSimple(
    val name: String,
    val value: Int,
)

private fun writeNestedSimple(w: SpecWriter, obj: NestedSimple) {
    w.beginObject(2)
    w.writeField("name"); w.writeString(obj.name)
    w.writeField("value"); w.writeInt32(obj.value)
    w.endObject()
}

val NestedSimpleCodec: SpecCodec<NestedSimple> = SpecCodec(
    encode = { w, obj -> writeNestedSimple(w, obj) },
    decode = { r ->
        var nameVal: String = ""
        var valueVal: Int = 0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "name" -> nameVal = r.readString()
                "value" -> valueVal = r.readInt32()
                else -> r.skip()
            }
        }
        r.endObject()
        NestedSimple(name = nameVal, value = valueVal)
    }
)
