// Generated by @specodec/typespec-emitter-kotlin. DO NOT EDIT.
package all_types_scalars

import specodec.*

data class SingleString(
    val v: String,
)

fun writeSingleString(w: SpecWriter, obj: SingleString) {
    w.beginObject(1)
    w.writeField("v"); w.writeString(obj.v)
    w.endObject()
}

val SingleStringCodec: SpecCodec<SingleString> = SpecCodec(
    encode = { w, obj -> writeSingleString(w, obj) },
    decode = { r ->
        var vVal: String = ""
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "v" -> vVal = r.readString()
                else -> r.skip()
            }
        }
        r.endObject()
        SingleString(v = vVal)
    }
)

data class SingleBoolean(
    val v: Boolean,
)

fun writeSingleBoolean(w: SpecWriter, obj: SingleBoolean) {
    w.beginObject(1)
    w.writeField("v"); w.writeBool(obj.v)
    w.endObject()
}

val SingleBooleanCodec: SpecCodec<SingleBoolean> = SpecCodec(
    encode = { w, obj -> writeSingleBoolean(w, obj) },
    decode = { r ->
        var vVal: Boolean = false
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "v" -> vVal = r.readBool()
                else -> r.skip()
            }
        }
        r.endObject()
        SingleBoolean(v = vVal)
    }
)

data class SingleInt8(
    val v: Byte,
)

fun writeSingleInt8(w: SpecWriter, obj: SingleInt8) {
    w.beginObject(1)
    w.writeField("v"); w.writeInt32(obj.v.toInt())
    w.endObject()
}

val SingleInt8Codec: SpecCodec<SingleInt8> = SpecCodec(
    encode = { w, obj -> writeSingleInt8(w, obj) },
    decode = { r ->
        var vVal: Byte = 0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "v" -> vVal = r.readInt32().toByte()
                else -> r.skip()
            }
        }
        r.endObject()
        SingleInt8(v = vVal)
    }
)

data class SingleInt16(
    val v: Short,
)

fun writeSingleInt16(w: SpecWriter, obj: SingleInt16) {
    w.beginObject(1)
    w.writeField("v"); w.writeInt32(obj.v.toInt())
    w.endObject()
}

val SingleInt16Codec: SpecCodec<SingleInt16> = SpecCodec(
    encode = { w, obj -> writeSingleInt16(w, obj) },
    decode = { r ->
        var vVal: Short = 0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "v" -> vVal = r.readInt32().toShort()
                else -> r.skip()
            }
        }
        r.endObject()
        SingleInt16(v = vVal)
    }
)

data class SingleInt32(
    val v: Int,
)

fun writeSingleInt32(w: SpecWriter, obj: SingleInt32) {
    w.beginObject(1)
    w.writeField("v"); w.writeInt32(obj.v)
    w.endObject()
}

val SingleInt32Codec: SpecCodec<SingleInt32> = SpecCodec(
    encode = { w, obj -> writeSingleInt32(w, obj) },
    decode = { r ->
        var vVal: Int = 0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "v" -> vVal = r.readInt32()
                else -> r.skip()
            }
        }
        r.endObject()
        SingleInt32(v = vVal)
    }
)

data class SingleInt64(
    val v: Long,
)

fun writeSingleInt64(w: SpecWriter, obj: SingleInt64) {
    w.beginObject(1)
    w.writeField("v"); w.writeInt64(obj.v)
    w.endObject()
}

val SingleInt64Codec: SpecCodec<SingleInt64> = SpecCodec(
    encode = { w, obj -> writeSingleInt64(w, obj) },
    decode = { r ->
        var vVal: Long = 0L
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "v" -> vVal = r.readInt64()
                else -> r.skip()
            }
        }
        r.endObject()
        SingleInt64(v = vVal)
    }
)

data class SingleUint8(
    val v: UByte,
)

fun writeSingleUint8(w: SpecWriter, obj: SingleUint8) {
    w.beginObject(1)
    w.writeField("v"); w.writeUint32(obj.v.toUInt())
    w.endObject()
}

val SingleUint8Codec: SpecCodec<SingleUint8> = SpecCodec(
    encode = { w, obj -> writeSingleUint8(w, obj) },
    decode = { r ->
        var vVal: UByte = 0u
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "v" -> vVal = r.readUint32().toUByte()
                else -> r.skip()
            }
        }
        r.endObject()
        SingleUint8(v = vVal)
    }
)

data class SingleUint16(
    val v: UShort,
)

fun writeSingleUint16(w: SpecWriter, obj: SingleUint16) {
    w.beginObject(1)
    w.writeField("v"); w.writeUint32(obj.v.toUInt())
    w.endObject()
}

val SingleUint16Codec: SpecCodec<SingleUint16> = SpecCodec(
    encode = { w, obj -> writeSingleUint16(w, obj) },
    decode = { r ->
        var vVal: UShort = 0u
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "v" -> vVal = r.readUint32().toUShort()
                else -> r.skip()
            }
        }
        r.endObject()
        SingleUint16(v = vVal)
    }
)

data class SingleUint32(
    val v: UInt,
)

fun writeSingleUint32(w: SpecWriter, obj: SingleUint32) {
    w.beginObject(1)
    w.writeField("v"); w.writeUint32(obj.v)
    w.endObject()
}

val SingleUint32Codec: SpecCodec<SingleUint32> = SpecCodec(
    encode = { w, obj -> writeSingleUint32(w, obj) },
    decode = { r ->
        var vVal: UInt = 0u
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "v" -> vVal = r.readUint32()
                else -> r.skip()
            }
        }
        r.endObject()
        SingleUint32(v = vVal)
    }
)

data class SingleUint64(
    val v: ULong,
)

fun writeSingleUint64(w: SpecWriter, obj: SingleUint64) {
    w.beginObject(1)
    w.writeField("v"); w.writeUint64(obj.v)
    w.endObject()
}

val SingleUint64Codec: SpecCodec<SingleUint64> = SpecCodec(
    encode = { w, obj -> writeSingleUint64(w, obj) },
    decode = { r ->
        var vVal: ULong = 0uL
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "v" -> vVal = r.readUint64()
                else -> r.skip()
            }
        }
        r.endObject()
        SingleUint64(v = vVal)
    }
)

data class SingleFloat32(
    val v: Float,
)

fun writeSingleFloat32(w: SpecWriter, obj: SingleFloat32) {
    w.beginObject(1)
    w.writeField("v"); w.writeFloat32(obj.v)
    w.endObject()
}

val SingleFloat32Codec: SpecCodec<SingleFloat32> = SpecCodec(
    encode = { w, obj -> writeSingleFloat32(w, obj) },
    decode = { r ->
        var vVal: Float = 0f
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "v" -> vVal = r.readFloat32()
                else -> r.skip()
            }
        }
        r.endObject()
        SingleFloat32(v = vVal)
    }
)

data class SingleFloat64(
    val v: Double,
)

fun writeSingleFloat64(w: SpecWriter, obj: SingleFloat64) {
    w.beginObject(1)
    w.writeField("v"); w.writeFloat64(obj.v)
    w.endObject()
}

val SingleFloat64Codec: SpecCodec<SingleFloat64> = SpecCodec(
    encode = { w, obj -> writeSingleFloat64(w, obj) },
    decode = { r ->
        var vVal: Double = 0.0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "v" -> vVal = r.readFloat64()
                else -> r.skip()
            }
        }
        r.endObject()
        SingleFloat64(v = vVal)
    }
)

data class SingleBytes(
    val v: ByteArray,
)

fun writeSingleBytes(w: SpecWriter, obj: SingleBytes) {
    w.beginObject(1)
    w.writeField("v"); w.writeBytes(obj.v)
    w.endObject()
}

val SingleBytesCodec: SpecCodec<SingleBytes> = SpecCodec(
    encode = { w, obj -> writeSingleBytes(w, obj) },
    decode = { r ->
        var vVal: ByteArray = byteArrayOf()
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "v" -> vVal = r.readBytes()
                else -> r.skip()
            }
        }
        r.endObject()
        SingleBytes(v = vVal)
    }
)
