// Generated by @specodec/typespec-emitter-kotlin. DO NOT EDIT.
package all_types_recursive

import specodec.*

data class RecList(
    val value: Int,
    val next: RecList? = null,
)

fun writeRecList(w: SpecWriter, obj: RecList) {
    var fieldCount = 1
    if (obj.next != null) fieldCount++
    w.beginObject(fieldCount)
    w.writeField("value"); w.writeInt32(obj.value)
    if (obj.next != null) { w.writeField("next"); writeRecList(w, obj.next) }
    w.endObject()
}

val RecListCodec: SpecCodec<RecList> = SpecCodec(
    encode = { w, obj -> writeRecList(w, obj) },
    decode = { r ->
        var valueVal: Int = 0
        var nextVal: RecList? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "value" -> valueVal = r.readInt32()
                "next" -> nextVal = if (r.isNull()) { r.readNull(); null } else { RecListCodec.decode(r) }
                else -> r.skip()
            }
        }
        r.endObject()
        RecList(value = valueVal, next = nextVal)
    }
)

data class RecTree(
    val value: String,
    val leftNode: RecTree? = null,
    val rightNode: RecTree? = null,
)

fun writeRecTree(w: SpecWriter, obj: RecTree) {
    var fieldCount = 1
    if (obj.leftNode != null) fieldCount++
    if (obj.rightNode != null) fieldCount++
    w.beginObject(fieldCount)
    w.writeField("value"); w.writeString(obj.value)
    if (obj.leftNode != null) { w.writeField("left_node"); writeRecTree(w, obj.leftNode) }
    if (obj.rightNode != null) { w.writeField("right_node"); writeRecTree(w, obj.rightNode) }
    w.endObject()
}

val RecTreeCodec: SpecCodec<RecTree> = SpecCodec(
    encode = { w, obj -> writeRecTree(w, obj) },
    decode = { r ->
        var valueVal: String = ""
        var leftNodeVal: RecTree? = null
        var rightNodeVal: RecTree? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "value" -> valueVal = r.readString()
                "left_node" -> leftNodeVal = if (r.isNull()) { r.readNull(); null } else { RecTreeCodec.decode(r) }
                "right_node" -> rightNodeVal = if (r.isNull()) { r.readNull(); null } else { RecTreeCodec.decode(r) }
                else -> r.skip()
            }
        }
        r.endObject()
        RecTree(value = valueVal, leftNode = leftNodeVal, rightNode = rightNodeVal)
    }
)

data class RecChain(
    val id: Int,
    val label: String,
    val next: RecChain? = null,
)

fun writeRecChain(w: SpecWriter, obj: RecChain) {
    var fieldCount = 2
    if (obj.next != null) fieldCount++
    w.beginObject(fieldCount)
    w.writeField("id"); w.writeInt32(obj.id)
    w.writeField("label"); w.writeString(obj.label)
    if (obj.next != null) { w.writeField("next"); writeRecChain(w, obj.next) }
    w.endObject()
}

val RecChainCodec: SpecCodec<RecChain> = SpecCodec(
    encode = { w, obj -> writeRecChain(w, obj) },
    decode = { r ->
        var idVal: Int = 0
        var labelVal: String = ""
        var nextVal: RecChain? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "id" -> idVal = r.readInt32()
                "label" -> labelVal = r.readString()
                "next" -> nextVal = if (r.isNull()) { r.readNull(); null } else { RecChainCodec.decode(r) }
                else -> r.skip()
            }
        }
        r.endObject()
        RecChain(id = idVal, label = labelVal, next = nextVal)
    }
)

data class RecWrap(
    val payload: ByteArray,
    val nested: RecWrap? = null,
)

fun writeRecWrap(w: SpecWriter, obj: RecWrap) {
    var fieldCount = 1
    if (obj.nested != null) fieldCount++
    w.beginObject(fieldCount)
    w.writeField("payload"); w.writeBytes(obj.payload)
    if (obj.nested != null) { w.writeField("nested"); writeRecWrap(w, obj.nested) }
    w.endObject()
}

val RecWrapCodec: SpecCodec<RecWrap> = SpecCodec(
    encode = { w, obj -> writeRecWrap(w, obj) },
    decode = { r ->
        var payloadVal: ByteArray = byteArrayOf()
        var nestedVal: RecWrap? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "payload" -> payloadVal = r.readBytes()
                "nested" -> nestedVal = if (r.isNull()) { r.readNull(); null } else { RecWrapCodec.decode(r) }
                else -> r.skip()
            }
        }
        r.endObject()
        RecWrap(payload = payloadVal, nested = nestedVal)
    }
)

data class RecWide(
    val a: Int,
    val b: String,
    val c: Double,
    val child: RecWide? = null,
)

fun writeRecWide(w: SpecWriter, obj: RecWide) {
    var fieldCount = 3
    if (obj.child != null) fieldCount++
    w.beginObject(fieldCount)
    w.writeField("a"); w.writeInt32(obj.a)
    w.writeField("b"); w.writeString(obj.b)
    w.writeField("c"); w.writeFloat64(obj.c)
    if (obj.child != null) { w.writeField("child"); writeRecWide(w, obj.child) }
    w.endObject()
}

val RecWideCodec: SpecCodec<RecWide> = SpecCodec(
    encode = { w, obj -> writeRecWide(w, obj) },
    decode = { r ->
        var aVal: Int = 0
        var bVal: String = ""
        var cVal: Double = 0.0
        var childVal: RecWide? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readInt32()
                "b" -> bVal = r.readString()
                "c" -> cVal = r.readFloat64()
                "child" -> childVal = if (r.isNull()) { r.readNull(); null } else { RecWideCodec.decode(r) }
                else -> r.skip()
            }
        }
        r.endObject()
        RecWide(a = aVal, b = bVal, c = cVal, child = childVal)
    }
)
