// Generated by @specodec/typespec-emitter-kotlin. DO NOT EDIT.
package all_types_unions

import specodec.*
import all_types.*

data class UnionFieldHolder(
    val shape: Shape,
    val id: Ident,
)

fun writeUnionFieldHolder(w: SpecWriter, obj: UnionFieldHolder) {
    w.beginObject(2)
    w.writeField("shape"); writeShape(w, obj.shape)
    w.writeField("id"); writeIdent(w, obj.id)
    w.endObject()
}

val UnionFieldHolderCodec: SpecCodec<UnionFieldHolder> = SpecCodec(
    encode = { w, obj -> writeUnionFieldHolder(w, obj) },
    decode = { r ->
        var shapeVal: Shape? = null
        var idVal: Ident? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "shape" -> shapeVal = ShapeCodec.decode(r)
                "id" -> idVal = IdentCodec.decode(r)
                else -> r.skip()
            }
        }
        r.endObject()
        UnionFieldHolder(shape = shapeVal!!, id = idVal!!)
    }
)

data class OptUnionFieldHolder(
    val shape: Shape? = null,
    val name: String,
)

fun writeOptUnionFieldHolder(w: SpecWriter, obj: OptUnionFieldHolder) {
    var fieldCount = 1
    if (obj.shape != null) fieldCount++
    w.beginObject(fieldCount)
    if (obj.shape != null) { w.writeField("shape"); writeShape(w, obj.shape) }
    w.writeField("name"); w.writeString(obj.name)
    w.endObject()
}

val OptUnionFieldHolderCodec: SpecCodec<OptUnionFieldHolder> = SpecCodec(
    encode = { w, obj -> writeOptUnionFieldHolder(w, obj) },
    decode = { r ->
        var shapeVal: Shape? = null
        var nameVal: String = ""
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "shape" -> shapeVal = ShapeCodec.decode(r)
                "name" -> nameVal = r.readString()
                else -> r.skip()
            }
        }
        r.endObject()
        OptUnionFieldHolder(shape = shapeVal, name = nameVal)
    }
)

data class UnionArrayHolder(
    val shapes: List<Shape>,
)

fun writeUnionArrayHolder(w: SpecWriter, obj: UnionArrayHolder) {
    w.beginObject(1)
    w.writeField("shapes"); w.beginArray(obj.shapes.size)
        for (item in obj.shapes) { w.nextElement(); writeShape(w, item) }
        w.endArray()
    w.endObject()
}

val UnionArrayHolderCodec: SpecCodec<UnionArrayHolder> = SpecCodec(
    encode = { w, obj -> writeUnionArrayHolder(w, obj) },
    decode = { r ->
        var shapesVal: List<Shape> = emptyList()
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "shapes" -> shapesVal = run { val list = mutableListOf<Shape>(); r.beginArray(); while (r.hasNextElement()) { list.add(ShapeCodec.decode(r)) }; r.endArray(); list }
                else -> r.skip()
            }
        }
        r.endObject()
        UnionArrayHolder(shapes = shapesVal)
    }
)

data class UnionMixedHolder(
    val result: ResultMsg,
    val tag: Tagged,
    val count: Int,
)

fun writeUnionMixedHolder(w: SpecWriter, obj: UnionMixedHolder) {
    w.beginObject(3)
    w.writeField("result"); writeResultMsg(w, obj.result)
    w.writeField("tag"); writeTagged(w, obj.tag)
    w.writeField("count"); w.writeInt32(obj.count)
    w.endObject()
}

val UnionMixedHolderCodec: SpecCodec<UnionMixedHolder> = SpecCodec(
    encode = { w, obj -> writeUnionMixedHolder(w, obj) },
    decode = { r ->
        var resultVal: ResultMsg? = null
        var tagVal: Tagged? = null
        var countVal: Int = 0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "result" -> resultVal = ResultMsgCodec.decode(r)
                "tag" -> tagVal = TaggedCodec.decode(r)
                "count" -> countVal = r.readInt32()
                else -> r.skip()
            }
        }
        r.endObject()
        UnionMixedHolder(result = resultVal!!, tag = tagVal!!, count = countVal)
    }
)

data class UnionScalarHolder(
    val id: Ident,
    val sc: ScalarUnion,
    val label: String,
)

fun writeUnionScalarHolder(w: SpecWriter, obj: UnionScalarHolder) {
    w.beginObject(3)
    w.writeField("id"); writeIdent(w, obj.id)
    w.writeField("sc"); writeScalarUnion(w, obj.sc)
    w.writeField("label"); w.writeString(obj.label)
    w.endObject()
}

val UnionScalarHolderCodec: SpecCodec<UnionScalarHolder> = SpecCodec(
    encode = { w, obj -> writeUnionScalarHolder(w, obj) },
    decode = { r ->
        var idVal: Ident? = null
        var scVal: ScalarUnion? = null
        var labelVal: String = ""
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "id" -> idVal = IdentCodec.decode(r)
                "sc" -> scVal = ScalarUnionCodec.decode(r)
                "label" -> labelVal = r.readString()
                else -> r.skip()
            }
        }
        r.endObject()
        UnionScalarHolder(id = idVal!!, sc = scVal!!, label = labelVal)
    }
)

sealed class Shape {
    data class CircleV(val value: Coord) : Shape()
    data class RectV(val value: Range32) : Shape()
}

fun writeShape(w: SpecWriter, obj: Shape) {
    w.beginObject(1)
    when (obj) {
        is Shape.CircleV -> { w.writeField("circle"); writeCoord(w, obj.value) }
        is Shape.RectV -> { w.writeField("rect"); writeRange32(w, obj.value) }
    }
    w.endObject()
}

fun decodeShape(r: SpecReader): Shape {
    r.beginObject()
    if (!r.hasNextField()) { r.endObject(); throw IllegalArgumentException("empty union") }
    val field = r.readFieldName()
    val result = when (field) {
        "circle" -> Shape.CircleV(CoordCodec.decode(r))
        "rect" -> Shape.RectV(Range32Codec.decode(r))
        else -> throw IllegalArgumentException("unknown variant $field")
    }
    while (r.hasNextField()) { r.readFieldName(); r.skip() }
    r.endObject()
    return result
}

val ShapeCodec = SpecCodec<Shape>(::writeShape, ::decodeShape)

sealed class Ident {
    data class NameV(val value: String) : Ident()
    data class NumberV(val value: Int) : Ident()
}

fun writeIdent(w: SpecWriter, obj: Ident) {
    w.beginObject(1)
    when (obj) {
        is Ident.NameV -> { w.writeField("name"); w.writeString(obj.value) }
        is Ident.NumberV -> { w.writeField("number"); w.writeInt32(obj.value) }
    }
    w.endObject()
}

fun decodeIdent(r: SpecReader): Ident {
    r.beginObject()
    if (!r.hasNextField()) { r.endObject(); throw IllegalArgumentException("empty union") }
    val field = r.readFieldName()
    val result = when (field) {
        "name" -> Ident.NameV(r.readString())
        "number" -> Ident.NumberV(r.readInt32())
        else -> throw IllegalArgumentException("unknown variant $field")
    }
    while (r.hasNextField()) { r.readFieldName(); r.skip() }
    r.endObject()
    return result
}

val IdentCodec = SpecCodec<Ident>(::writeIdent, ::decodeIdent)

sealed class ResultMsg {
    data class OkV(val value: String) : ResultMsg()
    data class ErrV(val value: Label) : ResultMsg()
}

fun writeResultMsg(w: SpecWriter, obj: ResultMsg) {
    w.beginObject(1)
    when (obj) {
        is ResultMsg.OkV -> { w.writeField("ok"); w.writeString(obj.value) }
        is ResultMsg.ErrV -> { w.writeField("err"); writeLabel(w, obj.value) }
    }
    w.endObject()
}

fun decodeResultMsg(r: SpecReader): ResultMsg {
    r.beginObject()
    if (!r.hasNextField()) { r.endObject(); throw IllegalArgumentException("empty union") }
    val field = r.readFieldName()
    val result = when (field) {
        "ok" -> ResultMsg.OkV(r.readString())
        "err" -> ResultMsg.ErrV(LabelCodec.decode(r))
        else -> throw IllegalArgumentException("unknown variant $field")
    }
    while (r.hasNextField()) { r.readFieldName(); r.skip() }
    r.endObject()
    return result
}

val ResultMsgCodec = SpecCodec<ResultMsg>(::writeResultMsg, ::decodeResultMsg)

sealed class Tagged {
    data class TagV(val value: String) : Tagged()
    data class ScoreV(val value: Double) : Tagged()
    data class ActiveV(val value: Boolean) : Tagged()
}

fun writeTagged(w: SpecWriter, obj: Tagged) {
    w.beginObject(1)
    when (obj) {
        is Tagged.TagV -> { w.writeField("tag"); w.writeString(obj.value) }
        is Tagged.ScoreV -> { w.writeField("score"); w.writeFloat64(obj.value) }
        is Tagged.ActiveV -> { w.writeField("active"); w.writeBool(obj.value) }
    }
    w.endObject()
}

fun decodeTagged(r: SpecReader): Tagged {
    r.beginObject()
    if (!r.hasNextField()) { r.endObject(); throw IllegalArgumentException("empty union") }
    val field = r.readFieldName()
    val result = when (field) {
        "tag" -> Tagged.TagV(r.readString())
        "score" -> Tagged.ScoreV(r.readFloat64())
        "active" -> Tagged.ActiveV(r.readBool())
        else -> throw IllegalArgumentException("unknown variant $field")
    }
    while (r.hasNextField()) { r.readFieldName(); r.skip() }
    r.endObject()
    return result
}

val TaggedCodec = SpecCodec<Tagged>(::writeTagged, ::decodeTagged)

sealed class ScalarUnion {
    data class SV(val value: String) : ScalarUnion()
    data class IV(val value: Int) : ScalarUnion()
    data class FV(val value: Double) : ScalarUnion()
    data class BV(val value: Boolean) : ScalarUnion()
}

fun writeScalarUnion(w: SpecWriter, obj: ScalarUnion) {
    w.beginObject(1)
    when (obj) {
        is ScalarUnion.SV -> { w.writeField("s"); w.writeString(obj.value) }
        is ScalarUnion.IV -> { w.writeField("i"); w.writeInt32(obj.value) }
        is ScalarUnion.FV -> { w.writeField("f"); w.writeFloat64(obj.value) }
        is ScalarUnion.BV -> { w.writeField("b"); w.writeBool(obj.value) }
    }
    w.endObject()
}

fun decodeScalarUnion(r: SpecReader): ScalarUnion {
    r.beginObject()
    if (!r.hasNextField()) { r.endObject(); throw IllegalArgumentException("empty union") }
    val field = r.readFieldName()
    val result = when (field) {
        "s" -> ScalarUnion.SV(r.readString())
        "i" -> ScalarUnion.IV(r.readInt32())
        "f" -> ScalarUnion.FV(r.readFloat64())
        "b" -> ScalarUnion.BV(r.readBool())
        else -> throw IllegalArgumentException("unknown variant $field")
    }
    while (r.hasNextField()) { r.readFieldName(); r.skip() }
    r.endObject()
    return result
}

val ScalarUnionCodec = SpecCodec<ScalarUnion>(::writeScalarUnion, ::decodeScalarUnion)

sealed class OptUnionHolder {
    data class ShapeV(val value: Shape) : OptUnionHolder()
    data class IdV(val value: Ident) : OptUnionHolder()
}

fun writeOptUnionHolder(w: SpecWriter, obj: OptUnionHolder) {
    w.beginObject(1)
    when (obj) {
        is OptUnionHolder.ShapeV -> { w.writeField("shape"); writeShape(w, obj.value) }
        is OptUnionHolder.IdV -> { w.writeField("id"); writeIdent(w, obj.value) }
    }
    w.endObject()
}

fun decodeOptUnionHolder(r: SpecReader): OptUnionHolder {
    r.beginObject()
    if (!r.hasNextField()) { r.endObject(); throw IllegalArgumentException("empty union") }
    val field = r.readFieldName()
    val result = when (field) {
        "shape" -> OptUnionHolder.ShapeV(ShapeCodec.decode(r))
        "id" -> OptUnionHolder.IdV(IdentCodec.decode(r))
        else -> throw IllegalArgumentException("unknown variant $field")
    }
    while (r.hasNextField()) { r.readFieldName(); r.skip() }
    r.endObject()
    return result
}

val OptUnionHolderCodec = SpecCodec<OptUnionHolder>(::writeOptUnionHolder, ::decodeOptUnionHolder)

sealed class MixedUnion {
    data class PointV(val value: Coord) : MixedUnion()
    data class LabelV(val value: String) : MixedUnion()
    data class CountV(val value: Int) : MixedUnion()
}

fun writeMixedUnion(w: SpecWriter, obj: MixedUnion) {
    w.beginObject(1)
    when (obj) {
        is MixedUnion.PointV -> { w.writeField("point"); writeCoord(w, obj.value) }
        is MixedUnion.LabelV -> { w.writeField("label"); w.writeString(obj.value) }
        is MixedUnion.CountV -> { w.writeField("count"); w.writeInt32(obj.value) }
    }
    w.endObject()
}

fun decodeMixedUnion(r: SpecReader): MixedUnion {
    r.beginObject()
    if (!r.hasNextField()) { r.endObject(); throw IllegalArgumentException("empty union") }
    val field = r.readFieldName()
    val result = when (field) {
        "point" -> MixedUnion.PointV(CoordCodec.decode(r))
        "label" -> MixedUnion.LabelV(r.readString())
        "count" -> MixedUnion.CountV(r.readInt32())
        else -> throw IllegalArgumentException("unknown variant $field")
    }
    while (r.hasNextField()) { r.readFieldName(); r.skip() }
    r.endObject()
    return result
}

val MixedUnionCodec = SpecCodec<MixedUnion>(::writeMixedUnion, ::decodeMixedUnion)

sealed class NestedUnion {
    data class ResultV(val value: ResultMsg) : NestedUnion()
    data class ShapeV(val value: Shape) : NestedUnion()
}

fun writeNestedUnion(w: SpecWriter, obj: NestedUnion) {
    w.beginObject(1)
    when (obj) {
        is NestedUnion.ResultV -> { w.writeField("result"); writeResultMsg(w, obj.value) }
        is NestedUnion.ShapeV -> { w.writeField("shape"); writeShape(w, obj.value) }
    }
    w.endObject()
}

fun decodeNestedUnion(r: SpecReader): NestedUnion {
    r.beginObject()
    if (!r.hasNextField()) { r.endObject(); throw IllegalArgumentException("empty union") }
    val field = r.readFieldName()
    val result = when (field) {
        "result" -> NestedUnion.ResultV(ResultMsgCodec.decode(r))
        "shape" -> NestedUnion.ShapeV(ShapeCodec.decode(r))
        else -> throw IllegalArgumentException("unknown variant $field")
    }
    while (r.hasNextField()) { r.readFieldName(); r.skip() }
    r.endObject()
    return result
}

val NestedUnionCodec = SpecCodec<NestedUnion>(::writeNestedUnion, ::decodeNestedUnion)
