// Generated by @specodec/typespec-emitter-kotlin. DO NOT EDIT.
package all_types_extra

import specodec.*
import all_types.*

data class OptArr1(
    val req: String,
    val items: List<Int>? = null,
)

fun writeOptArr1(w: SpecWriter, obj: OptArr1) {
    var fieldCount = 1
    if (obj.items != null) fieldCount++
    w.beginObject(fieldCount)
    w.writeField("req"); w.writeString(obj.req)
    if (obj.items != null) { w.writeField("items"); w.beginArray(obj.items.size)
        for (item in obj.items) { w.nextElement(); w.writeInt32(item) }
        w.endArray() }
    w.endObject()
}

val OptArr1Codec: SpecCodec<OptArr1> = SpecCodec(
    encode = { w, obj -> writeOptArr1(w, obj) },
    decode = { r ->
        var reqVal: String = ""
        var itemsVal: List<Int>? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "req" -> reqVal = r.readString()
                "items" -> itemsVal = run { val list = mutableListOf<Int>(); r.beginArray(); while (r.hasNextElement()) { list.add(r.readInt32()) }; r.endArray(); list }
                else -> r.skip()
            }
        }
        r.endObject()
        OptArr1(req = reqVal, items = itemsVal)
    }
)

data class OptArr2(
    val id: Int,
    val names: List<String>? = null,
    val flags: List<Boolean>? = null,
)

fun writeOptArr2(w: SpecWriter, obj: OptArr2) {
    var fieldCount = 1
    if (obj.names != null) fieldCount++
    if (obj.flags != null) fieldCount++
    w.beginObject(fieldCount)
    w.writeField("id"); w.writeInt32(obj.id)
    if (obj.names != null) { w.writeField("names"); w.beginArray(obj.names.size)
        for (item in obj.names) { w.nextElement(); w.writeString(item) }
        w.endArray() }
    if (obj.flags != null) { w.writeField("flags"); w.beginArray(obj.flags.size)
        for (item in obj.flags) { w.nextElement(); w.writeBool(item) }
        w.endArray() }
    w.endObject()
}

val OptArr2Codec: SpecCodec<OptArr2> = SpecCodec(
    encode = { w, obj -> writeOptArr2(w, obj) },
    decode = { r ->
        var idVal: Int = 0
        var namesVal: List<String>? = null
        var flagsVal: List<Boolean>? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "id" -> idVal = r.readInt32()
                "names" -> namesVal = run { val list = mutableListOf<String>(); r.beginArray(); while (r.hasNextElement()) { list.add(r.readString()) }; r.endArray(); list }
                "flags" -> flagsVal = run { val list = mutableListOf<Boolean>(); r.beginArray(); while (r.hasNextElement()) { list.add(r.readBool()) }; r.endArray(); list }
                else -> r.skip()
            }
        }
        r.endObject()
        OptArr2(id = idVal, names = namesVal, flags = flagsVal)
    }
)

data class OptArr3(
    val a: List<String>? = null,
    val b: List<Double>? = null,
)

fun writeOptArr3(w: SpecWriter, obj: OptArr3) {
    var fieldCount = 0
    if (obj.a != null) fieldCount++
    if (obj.b != null) fieldCount++
    w.beginObject(fieldCount)
    if (obj.a != null) { w.writeField("a"); w.beginArray(obj.a.size)
        for (item in obj.a) { w.nextElement(); w.writeString(item) }
        w.endArray() }
    if (obj.b != null) { w.writeField("b"); w.beginArray(obj.b.size)
        for (item in obj.b) { w.nextElement(); w.writeFloat64(item) }
        w.endArray() }
    w.endObject()
}

val OptArr3Codec: SpecCodec<OptArr3> = SpecCodec(
    encode = { w, obj -> writeOptArr3(w, obj) },
    decode = { r ->
        var aVal: List<String>? = null
        var bVal: List<Double>? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = run { val list = mutableListOf<String>(); r.beginArray(); while (r.hasNextElement()) { list.add(r.readString()) }; r.endArray(); list }
                "b" -> bVal = run { val list = mutableListOf<Double>(); r.beginArray(); while (r.hasNextElement()) { list.add(r.readFloat64()) }; r.endArray(); list }
                else -> r.skip()
            }
        }
        r.endObject()
        OptArr3(a = aVal, b = bVal)
    }
)

data class OptArr4(
    val payload: ByteArray,
    val chunks: List<ByteArray>? = null,
)

fun writeOptArr4(w: SpecWriter, obj: OptArr4) {
    var fieldCount = 1
    if (obj.chunks != null) fieldCount++
    w.beginObject(fieldCount)
    w.writeField("payload"); w.writeBytes(obj.payload)
    if (obj.chunks != null) { w.writeField("chunks"); w.beginArray(obj.chunks.size)
        for (item in obj.chunks) { w.nextElement(); w.writeBytes(item) }
        w.endArray() }
    w.endObject()
}

val OptArr4Codec: SpecCodec<OptArr4> = SpecCodec(
    encode = { w, obj -> writeOptArr4(w, obj) },
    decode = { r ->
        var payloadVal: ByteArray = byteArrayOf()
        var chunksVal: List<ByteArray>? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "payload" -> payloadVal = r.readBytes()
                "chunks" -> chunksVal = run { val list = mutableListOf<ByteArray>(); r.beginArray(); while (r.hasNextElement()) { list.add(r.readBytes()) }; r.endArray(); list }
                else -> r.skip()
            }
        }
        r.endObject()
        OptArr4(payload = payloadVal, chunks = chunksVal)
    }
)

data class OptArr5(
    val models: List<Inner>? = null,
    val name: String,
)

fun writeOptArr5(w: SpecWriter, obj: OptArr5) {
    var fieldCount = 1
    if (obj.models != null) fieldCount++
    w.beginObject(fieldCount)
    if (obj.models != null) { w.writeField("models"); w.beginArray(obj.models.size)
        for (item in obj.models) { w.nextElement(); writeInner(w, item) }
        w.endArray() }
    w.writeField("name"); w.writeString(obj.name)
    w.endObject()
}

val OptArr5Codec: SpecCodec<OptArr5> = SpecCodec(
    encode = { w, obj -> writeOptArr5(w, obj) },
    decode = { r ->
        var modelsVal: List<Inner>? = null
        var nameVal: String = ""
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "models" -> modelsVal = run { val list = mutableListOf<Inner>(); r.beginArray(); while (r.hasNextElement()) { list.add(InnerCodec.decode(r)) }; r.endArray(); list }
                "name" -> nameVal = r.readString()
                else -> r.skip()
            }
        }
        r.endObject()
        OptArr5(models = modelsVal, name = nameVal)
    }
)

data class NestOpt1(
    val outer: Label,
    val name: String,
)

fun writeNestOpt1(w: SpecWriter, obj: NestOpt1) {
    w.beginObject(2)
    w.writeField("outer"); writeLabel(w, obj.outer)
    w.writeField("name"); w.writeString(obj.name)
    w.endObject()
}

val NestOpt1Codec: SpecCodec<NestOpt1> = SpecCodec(
    encode = { w, obj -> writeNestOpt1(w, obj) },
    decode = { r ->
        var outerVal: Label? = null
        var nameVal: String = ""
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "outer" -> outerVal = LabelCodec.decode(r)
                "name" -> nameVal = r.readString()
                else -> r.skip()
            }
        }
        r.endObject()
        NestOpt1(outer = outerVal!!, name = nameVal)
    }
)

data class NestOpt2(
    val a: IdVal? = null,
    val b: IdVal? = null,
    val c: IdVal? = null,
)

fun writeNestOpt2(w: SpecWriter, obj: NestOpt2) {
    var fieldCount = 0
    if (obj.a != null) fieldCount++
    if (obj.b != null) fieldCount++
    if (obj.c != null) fieldCount++
    w.beginObject(fieldCount)
    if (obj.a != null) { w.writeField("a"); writeIdVal(w, obj.a) }
    if (obj.b != null) { w.writeField("b"); writeIdVal(w, obj.b) }
    if (obj.c != null) { w.writeField("c"); writeIdVal(w, obj.c) }
    w.endObject()
}

val NestOpt2Codec: SpecCodec<NestOpt2> = SpecCodec(
    encode = { w, obj -> writeNestOpt2(w, obj) },
    decode = { r ->
        var aVal: IdVal? = null
        var bVal: IdVal? = null
        var cVal: IdVal? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = if (r.isNull()) { r.readNull(); null } else { IdValCodec.decode(r) }
                "b" -> bVal = if (r.isNull()) { r.readNull(); null } else { IdValCodec.decode(r) }
                "c" -> cVal = if (r.isNull()) { r.readNull(); null } else { IdValCodec.decode(r) }
                else -> r.skip()
            }
        }
        r.endObject()
        NestOpt2(a = aVal, b = bVal, c = cVal)
    }
)

data class NestOpt3(
    val money: Money,
    val valueRange: Range32? = null,
)

fun writeNestOpt3(w: SpecWriter, obj: NestOpt3) {
    var fieldCount = 1
    if (obj.valueRange != null) fieldCount++
    w.beginObject(fieldCount)
    w.writeField("money"); writeMoney(w, obj.money)
    if (obj.valueRange != null) { w.writeField("value_range"); writeRange32(w, obj.valueRange) }
    w.endObject()
}

val NestOpt3Codec: SpecCodec<NestOpt3> = SpecCodec(
    encode = { w, obj -> writeNestOpt3(w, obj) },
    decode = { r ->
        var moneyVal: Money? = null
        var valueRangeVal: Range32? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "money" -> moneyVal = MoneyCodec.decode(r)
                "value_range" -> valueRangeVal = if (r.isNull()) { r.readNull(); null } else { Range32Codec.decode(r) }
                else -> r.skip()
            }
        }
        r.endObject()
        NestOpt3(money = moneyVal!!, valueRange = valueRangeVal)
    }
)

data class NestOpt4(
    val addr: Addr? = null,
    val coord: Coord? = null,
    val name: String,
)

fun writeNestOpt4(w: SpecWriter, obj: NestOpt4) {
    var fieldCount = 1
    if (obj.addr != null) fieldCount++
    if (obj.coord != null) fieldCount++
    w.beginObject(fieldCount)
    if (obj.addr != null) { w.writeField("addr"); writeAddr(w, obj.addr) }
    if (obj.coord != null) { w.writeField("coord"); writeCoord(w, obj.coord) }
    w.writeField("name"); w.writeString(obj.name)
    w.endObject()
}

val NestOpt4Codec: SpecCodec<NestOpt4> = SpecCodec(
    encode = { w, obj -> writeNestOpt4(w, obj) },
    decode = { r ->
        var addrVal: Addr? = null
        var coordVal: Coord? = null
        var nameVal: String = ""
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "addr" -> addrVal = if (r.isNull()) { r.readNull(); null } else { AddrCodec.decode(r) }
                "coord" -> coordVal = if (r.isNull()) { r.readNull(); null } else { CoordCodec.decode(r) }
                "name" -> nameVal = r.readString()
                else -> r.skip()
            }
        }
        r.endObject()
        NestOpt4(addr = addrVal, coord = coordVal, name = nameVal)
    }
)

data class NestOpt5(
    val point: Point3,
    val addr: Addr,
    val label: Label? = null,
)

fun writeNestOpt5(w: SpecWriter, obj: NestOpt5) {
    var fieldCount = 2
    if (obj.label != null) fieldCount++
    w.beginObject(fieldCount)
    w.writeField("point"); writePoint3(w, obj.point)
    w.writeField("addr"); writeAddr(w, obj.addr)
    if (obj.label != null) { w.writeField("label"); writeLabel(w, obj.label) }
    w.endObject()
}

val NestOpt5Codec: SpecCodec<NestOpt5> = SpecCodec(
    encode = { w, obj -> writeNestOpt5(w, obj) },
    decode = { r ->
        var pointVal: Point3? = null
        var addrVal: Addr? = null
        var labelVal: Label? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "point" -> pointVal = Point3Codec.decode(r)
                "addr" -> addrVal = AddrCodec.decode(r)
                "label" -> labelVal = if (r.isNull()) { r.readNull(); null } else { LabelCodec.decode(r) }
                else -> r.skip()
            }
        }
        r.endObject()
        NestOpt5(point = pointVal!!, addr = addrVal!!, label = labelVal)
    }
)

data class NestOptInner1(
    val tag: String,
    val nested: OptInner? = null,
)

fun writeNestOptInner1(w: SpecWriter, obj: NestOptInner1) {
    var fieldCount = 1
    if (obj.nested != null) fieldCount++
    w.beginObject(fieldCount)
    w.writeField("tag"); w.writeString(obj.tag)
    if (obj.nested != null) { w.writeField("nested"); writeOptInner(w, obj.nested) }
    w.endObject()
}

val NestOptInner1Codec: SpecCodec<NestOptInner1> = SpecCodec(
    encode = { w, obj -> writeNestOptInner1(w, obj) },
    decode = { r ->
        var tagVal: String = ""
        var nestedVal: OptInner? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "tag" -> tagVal = r.readString()
                "nested" -> nestedVal = if (r.isNull()) { r.readNull(); null } else { OptInnerCodec.decode(r) }
                else -> r.skip()
            }
        }
        r.endObject()
        NestOptInner1(tag = tagVal, nested = nestedVal)
    }
)

data class NestOptInner2(
    val tag: String,
    val nested: OptInner,
)

fun writeNestOptInner2(w: SpecWriter, obj: NestOptInner2) {
    w.beginObject(2)
    w.writeField("tag"); w.writeString(obj.tag)
    w.writeField("nested"); writeOptInner(w, obj.nested)
    w.endObject()
}

val NestOptInner2Codec: SpecCodec<NestOptInner2> = SpecCodec(
    encode = { w, obj -> writeNestOptInner2(w, obj) },
    decode = { r ->
        var tagVal: String = ""
        var nestedVal: OptInner? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "tag" -> tagVal = r.readString()
                "nested" -> nestedVal = OptInnerCodec.decode(r)
                else -> r.skip()
            }
        }
        r.endObject()
        NestOptInner2(tag = tagVal, nested = nestedVal!!)
    }
)

data class NestOptInner3(
    val outer: OptInner? = null,
    val nested: OptInner? = null,
)

fun writeNestOptInner3(w: SpecWriter, obj: NestOptInner3) {
    var fieldCount = 0
    if (obj.outer != null) fieldCount++
    if (obj.nested != null) fieldCount++
    w.beginObject(fieldCount)
    if (obj.outer != null) { w.writeField("outer"); writeOptInner(w, obj.outer) }
    if (obj.nested != null) { w.writeField("nested"); writeOptInner(w, obj.nested) }
    w.endObject()
}

val NestOptInner3Codec: SpecCodec<NestOptInner3> = SpecCodec(
    encode = { w, obj -> writeNestOptInner3(w, obj) },
    decode = { r ->
        var outerVal: OptInner? = null
        var nestedVal: OptInner? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "outer" -> outerVal = if (r.isNull()) { r.readNull(); null } else { OptInnerCodec.decode(r) }
                "nested" -> nestedVal = if (r.isNull()) { r.readNull(); null } else { OptInnerCodec.decode(r) }
                else -> r.skip()
            }
        }
        r.endObject()
        NestOptInner3(outer = outerVal, nested = nestedVal)
    }
)

data class DeepNest1(
    val label: String,
    val nested: Addr,
)

fun writeDeepNest1(w: SpecWriter, obj: DeepNest1) {
    w.beginObject(2)
    w.writeField("label"); w.writeString(obj.label)
    w.writeField("nested"); writeAddr(w, obj.nested)
    w.endObject()
}

val DeepNest1Codec: SpecCodec<DeepNest1> = SpecCodec(
    encode = { w, obj -> writeDeepNest1(w, obj) },
    decode = { r ->
        var labelVal: String = ""
        var nestedVal: Addr? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "label" -> labelVal = r.readString()
                "nested" -> nestedVal = AddrCodec.decode(r)
                else -> r.skip()
            }
        }
        r.endObject()
        DeepNest1(label = labelVal, nested = nestedVal!!)
    }
)

data class DeepNest2(
    val name: String,
    val money: Money,
    val addr: Addr,
)

fun writeDeepNest2(w: SpecWriter, obj: DeepNest2) {
    w.beginObject(3)
    w.writeField("name"); w.writeString(obj.name)
    w.writeField("money"); writeMoney(w, obj.money)
    w.writeField("addr"); writeAddr(w, obj.addr)
    w.endObject()
}

val DeepNest2Codec: SpecCodec<DeepNest2> = SpecCodec(
    encode = { w, obj -> writeDeepNest2(w, obj) },
    decode = { r ->
        var nameVal: String = ""
        var moneyVal: Money? = null
        var addrVal: Addr? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "name" -> nameVal = r.readString()
                "money" -> moneyVal = MoneyCodec.decode(r)
                "addr" -> addrVal = AddrCodec.decode(r)
                else -> r.skip()
            }
        }
        r.endObject()
        DeepNest2(name = nameVal, money = moneyVal!!, addr = addrVal!!)
    }
)

data class DeepNest3(
    val title: String,
    val point: Point3,
    val valueRange: Range32,
    val money: Money,
)

fun writeDeepNest3(w: SpecWriter, obj: DeepNest3) {
    w.beginObject(4)
    w.writeField("title"); w.writeString(obj.title)
    w.writeField("point"); writePoint3(w, obj.point)
    w.writeField("value_range"); writeRange32(w, obj.valueRange)
    w.writeField("money"); writeMoney(w, obj.money)
    w.endObject()
}

val DeepNest3Codec: SpecCodec<DeepNest3> = SpecCodec(
    encode = { w, obj -> writeDeepNest3(w, obj) },
    decode = { r ->
        var titleVal: String = ""
        var pointVal: Point3? = null
        var valueRangeVal: Range32? = null
        var moneyVal: Money? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "title" -> titleVal = r.readString()
                "point" -> pointVal = Point3Codec.decode(r)
                "value_range" -> valueRangeVal = Range32Codec.decode(r)
                "money" -> moneyVal = MoneyCodec.decode(r)
                else -> r.skip()
            }
        }
        r.endObject()
        DeepNest3(title = titleVal, point = pointVal!!, valueRange = valueRangeVal!!, money = moneyVal!!)
    }
)

data class DeepNest4(
    val coords: List<Coord>,
    val nested: Inner,
    val tag: String,
)

fun writeDeepNest4(w: SpecWriter, obj: DeepNest4) {
    w.beginObject(3)
    w.writeField("coords"); w.beginArray(obj.coords.size)
        for (item in obj.coords) { w.nextElement(); writeCoord(w, item) }
        w.endArray()
    w.writeField("nested"); writeInner(w, obj.nested)
    w.writeField("tag"); w.writeString(obj.tag)
    w.endObject()
}

val DeepNest4Codec: SpecCodec<DeepNest4> = SpecCodec(
    encode = { w, obj -> writeDeepNest4(w, obj) },
    decode = { r ->
        var coordsVal: List<Coord> = emptyList()
        var nestedVal: Inner? = null
        var tagVal: String = ""
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "coords" -> coordsVal = run { val list = mutableListOf<Coord>(); r.beginArray(); while (r.hasNextElement()) { list.add(CoordCodec.decode(r)) }; r.endArray(); list }
                "nested" -> nestedVal = InnerCodec.decode(r)
                "tag" -> tagVal = r.readString()
                else -> r.skip()
            }
        }
        r.endObject()
        DeepNest4(coords = coordsVal, nested = nestedVal!!, tag = tagVal)
    }
)

data class DeepNest5(
    val labels: List<Label>,
    val money: Money,
    val name: String,
)

fun writeDeepNest5(w: SpecWriter, obj: DeepNest5) {
    w.beginObject(3)
    w.writeField("labels"); w.beginArray(obj.labels.size)
        for (item in obj.labels) { w.nextElement(); writeLabel(w, item) }
        w.endArray()
    w.writeField("money"); writeMoney(w, obj.money)
    w.writeField("name"); w.writeString(obj.name)
    w.endObject()
}

val DeepNest5Codec: SpecCodec<DeepNest5> = SpecCodec(
    encode = { w, obj -> writeDeepNest5(w, obj) },
    decode = { r ->
        var labelsVal: List<Label> = emptyList()
        var moneyVal: Money? = null
        var nameVal: String = ""
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "labels" -> labelsVal = run { val list = mutableListOf<Label>(); r.beginArray(); while (r.hasNextElement()) { list.add(LabelCodec.decode(r)) }; r.endArray(); list }
                "money" -> moneyVal = MoneyCodec.decode(r)
                "name" -> nameVal = r.readString()
                else -> r.skip()
            }
        }
        r.endObject()
        DeepNest5(labels = labelsVal, money = moneyVal!!, name = nameVal)
    }
)

data class DeepNest6(
    val items: List<IdVal>,
    val addr: Addr? = null,
    val coord: Coord,
)

fun writeDeepNest6(w: SpecWriter, obj: DeepNest6) {
    var fieldCount = 2
    if (obj.addr != null) fieldCount++
    w.beginObject(fieldCount)
    w.writeField("items"); w.beginArray(obj.items.size)
        for (item in obj.items) { w.nextElement(); writeIdVal(w, item) }
        w.endArray()
    if (obj.addr != null) { w.writeField("addr"); writeAddr(w, obj.addr) }
    w.writeField("coord"); writeCoord(w, obj.coord)
    w.endObject()
}

val DeepNest6Codec: SpecCodec<DeepNest6> = SpecCodec(
    encode = { w, obj -> writeDeepNest6(w, obj) },
    decode = { r ->
        var itemsVal: List<IdVal> = emptyList()
        var addrVal: Addr? = null
        var coordVal: Coord? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "items" -> itemsVal = run { val list = mutableListOf<IdVal>(); r.beginArray(); while (r.hasNextElement()) { list.add(IdValCodec.decode(r)) }; r.endArray(); list }
                "addr" -> addrVal = if (r.isNull()) { r.readNull(); null } else { AddrCodec.decode(r) }
                "coord" -> coordVal = CoordCodec.decode(r)
                else -> r.skip()
            }
        }
        r.endObject()
        DeepNest6(items = itemsVal, addr = addrVal, coord = coordVal!!)
    }
)

data class DeepNest7(
    val a: Addr,
    val b: Addr,
    val c: Addr,
)

fun writeDeepNest7(w: SpecWriter, obj: DeepNest7) {
    w.beginObject(3)
    w.writeField("a"); writeAddr(w, obj.a)
    w.writeField("b"); writeAddr(w, obj.b)
    w.writeField("c"); writeAddr(w, obj.c)
    w.endObject()
}

val DeepNest7Codec: SpecCodec<DeepNest7> = SpecCodec(
    encode = { w, obj -> writeDeepNest7(w, obj) },
    decode = { r ->
        var aVal: Addr? = null
        var bVal: Addr? = null
        var cVal: Addr? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = AddrCodec.decode(r)
                "b" -> bVal = AddrCodec.decode(r)
                "c" -> cVal = AddrCodec.decode(r)
                else -> r.skip()
            }
        }
        r.endObject()
        DeepNest7(a = aVal!!, b = bVal!!, c = cVal!!)
    }
)

data class TimestampEntry(
    val ts: Long,
    val event: String,
    val payload: ByteArray? = null,
)

fun writeTimestampEntry(w: SpecWriter, obj: TimestampEntry) {
    var fieldCount = 2
    if (obj.payload != null) fieldCount++
    w.beginObject(fieldCount)
    w.writeField("ts"); w.writeInt64(obj.ts)
    w.writeField("event"); w.writeString(obj.event)
    if (obj.payload != null) { w.writeField("payload"); w.writeBytes(obj.payload) }
    w.endObject()
}

val TimestampEntryCodec: SpecCodec<TimestampEntry> = SpecCodec(
    encode = { w, obj -> writeTimestampEntry(w, obj) },
    decode = { r ->
        var tsVal: Long = 0L
        var eventVal: String = ""
        var payloadVal: ByteArray? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "ts" -> tsVal = r.readInt64()
                "event" -> eventVal = r.readString()
                "payload" -> payloadVal = r.readBytes()
                else -> r.skip()
            }
        }
        r.endObject()
        TimestampEntry(ts = tsVal, event = eventVal, payload = payloadVal)
    }
)

data class ConfigEntry(
    val key: String,
    val intValue: Int? = null,
    val strValue: String? = null,
    val boolValue: Boolean? = null,
    val floatValue: Double? = null,
)

fun writeConfigEntry(w: SpecWriter, obj: ConfigEntry) {
    var fieldCount = 1
    if (obj.intValue != null) fieldCount++
    if (obj.strValue != null) fieldCount++
    if (obj.boolValue != null) fieldCount++
    if (obj.floatValue != null) fieldCount++
    w.beginObject(fieldCount)
    w.writeField("key"); w.writeString(obj.key)
    if (obj.intValue != null) { w.writeField("intValue"); w.writeInt32(obj.intValue) }
    if (obj.strValue != null) { w.writeField("strValue"); w.writeString(obj.strValue) }
    if (obj.boolValue != null) { w.writeField("boolValue"); w.writeBool(obj.boolValue) }
    if (obj.floatValue != null) { w.writeField("floatValue"); w.writeFloat64(obj.floatValue) }
    w.endObject()
}

val ConfigEntryCodec: SpecCodec<ConfigEntry> = SpecCodec(
    encode = { w, obj -> writeConfigEntry(w, obj) },
    decode = { r ->
        var keyVal: String = ""
        var intValueVal: Int? = null
        var strValueVal: String? = null
        var boolValueVal: Boolean? = null
        var floatValueVal: Double? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "key" -> keyVal = r.readString()
                "intValue" -> intValueVal = r.readInt32()
                "strValue" -> strValueVal = r.readString()
                "boolValue" -> boolValueVal = r.readBool()
                "floatValue" -> floatValueVal = r.readFloat64()
                else -> r.skip()
            }
        }
        r.endObject()
        ConfigEntry(key = keyVal, intValue = intValueVal, strValue = strValueVal, boolValue = boolValueVal, floatValue = floatValueVal)
    }
)
