// Generated by @specodec/typespec-emitter-kotlin. DO NOT EDIT.
package all_types_many

import specodec.*

data class Five01(
    val f1: String,
    val f2: Int,
    val f3: Boolean,
    val f4: Double,
    val f5: ByteArray,
)

fun writeFive01(w: SpecWriter, obj: Five01) {
    w.beginObject(5)
    w.writeField("f1"); w.writeString(obj.f1)
    w.writeField("f2"); w.writeInt32(obj.f2)
    w.writeField("f3"); w.writeBool(obj.f3)
    w.writeField("f4"); w.writeFloat64(obj.f4)
    w.writeField("f5"); w.writeBytes(obj.f5)
    w.endObject()
}

val Five01Codec: SpecCodec<Five01> = SpecCodec(
    encode = { w, obj -> writeFive01(w, obj) },
    decode = { r ->
        var f1Val: String = ""
        var f2Val: Int = 0
        var f3Val: Boolean = false
        var f4Val: Double = 0.0
        var f5Val: ByteArray = byteArrayOf()
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "f1" -> f1Val = r.readString()
                "f2" -> f2Val = r.readInt32()
                "f3" -> f3Val = r.readBool()
                "f4" -> f4Val = r.readFloat64()
                "f5" -> f5Val = r.readBytes()
                else -> r.skip()
            }
        }
        r.endObject()
        Five01(f1 = f1Val, f2 = f2Val, f3 = f3Val, f4 = f4Val, f5 = f5Val)
    }
)

data class Five02(
    val f1: Int,
    val f2: Int,
    val f3: Int,
    val f4: Int,
    val f5: Int,
)

fun writeFive02(w: SpecWriter, obj: Five02) {
    w.beginObject(5)
    w.writeField("f1"); w.writeInt32(obj.f1)
    w.writeField("f2"); w.writeInt32(obj.f2)
    w.writeField("f3"); w.writeInt32(obj.f3)
    w.writeField("f4"); w.writeInt32(obj.f4)
    w.writeField("f5"); w.writeInt32(obj.f5)
    w.endObject()
}

val Five02Codec: SpecCodec<Five02> = SpecCodec(
    encode = { w, obj -> writeFive02(w, obj) },
    decode = { r ->
        var f1Val: Int = 0
        var f2Val: Int = 0
        var f3Val: Int = 0
        var f4Val: Int = 0
        var f5Val: Int = 0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "f1" -> f1Val = r.readInt32()
                "f2" -> f2Val = r.readInt32()
                "f3" -> f3Val = r.readInt32()
                "f4" -> f4Val = r.readInt32()
                "f5" -> f5Val = r.readInt32()
                else -> r.skip()
            }
        }
        r.endObject()
        Five02(f1 = f1Val, f2 = f2Val, f3 = f3Val, f4 = f4Val, f5 = f5Val)
    }
)

data class Five03(
    val f1: String,
    val f2: String,
    val f3: String,
    val f4: String,
    val f5: String,
)

fun writeFive03(w: SpecWriter, obj: Five03) {
    w.beginObject(5)
    w.writeField("f1"); w.writeString(obj.f1)
    w.writeField("f2"); w.writeString(obj.f2)
    w.writeField("f3"); w.writeString(obj.f3)
    w.writeField("f4"); w.writeString(obj.f4)
    w.writeField("f5"); w.writeString(obj.f5)
    w.endObject()
}

val Five03Codec: SpecCodec<Five03> = SpecCodec(
    encode = { w, obj -> writeFive03(w, obj) },
    decode = { r ->
        var f1Val: String = ""
        var f2Val: String = ""
        var f3Val: String = ""
        var f4Val: String = ""
        var f5Val: String = ""
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "f1" -> f1Val = r.readString()
                "f2" -> f2Val = r.readString()
                "f3" -> f3Val = r.readString()
                "f4" -> f4Val = r.readString()
                "f5" -> f5Val = r.readString()
                else -> r.skip()
            }
        }
        r.endObject()
        Five03(f1 = f1Val, f2 = f2Val, f3 = f3Val, f4 = f4Val, f5 = f5Val)
    }
)

data class Five04(
    val f1: Double,
    val f2: Int,
    val f3: String,
    val f4: Boolean,
    val f5: ByteArray,
)

fun writeFive04(w: SpecWriter, obj: Five04) {
    w.beginObject(5)
    w.writeField("f1"); w.writeFloat64(obj.f1)
    w.writeField("f2"); w.writeInt32(obj.f2)
    w.writeField("f3"); w.writeString(obj.f3)
    w.writeField("f4"); w.writeBool(obj.f4)
    w.writeField("f5"); w.writeBytes(obj.f5)
    w.endObject()
}

val Five04Codec: SpecCodec<Five04> = SpecCodec(
    encode = { w, obj -> writeFive04(w, obj) },
    decode = { r ->
        var f1Val: Double = 0.0
        var f2Val: Int = 0
        var f3Val: String = ""
        var f4Val: Boolean = false
        var f5Val: ByteArray = byteArrayOf()
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "f1" -> f1Val = r.readFloat64()
                "f2" -> f2Val = r.readInt32()
                "f3" -> f3Val = r.readString()
                "f4" -> f4Val = r.readBool()
                "f5" -> f5Val = r.readBytes()
                else -> r.skip()
            }
        }
        r.endObject()
        Five04(f1 = f1Val, f2 = f2Val, f3 = f3Val, f4 = f4Val, f5 = f5Val)
    }
)

data class Five05(
    val f1: Long,
    val f2: ULong,
    val f3: String,
    val f4: Float,
    val f5: Int,
)

fun writeFive05(w: SpecWriter, obj: Five05) {
    w.beginObject(5)
    w.writeField("f1"); w.writeInt64(obj.f1)
    w.writeField("f2"); w.writeUint64(obj.f2)
    w.writeField("f3"); w.writeString(obj.f3)
    w.writeField("f4"); w.writeFloat32(obj.f4)
    w.writeField("f5"); w.writeInt32(obj.f5)
    w.endObject()
}

val Five05Codec: SpecCodec<Five05> = SpecCodec(
    encode = { w, obj -> writeFive05(w, obj) },
    decode = { r ->
        var f1Val: Long = 0L
        var f2Val: ULong = 0uL
        var f3Val: String = ""
        var f4Val: Float = 0f
        var f5Val: Int = 0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "f1" -> f1Val = r.readInt64()
                "f2" -> f2Val = r.readUint64()
                "f3" -> f3Val = r.readString()
                "f4" -> f4Val = r.readFloat32()
                "f5" -> f5Val = r.readInt32()
                else -> r.skip()
            }
        }
        r.endObject()
        Five05(f1 = f1Val, f2 = f2Val, f3 = f3Val, f4 = f4Val, f5 = f5Val)
    }
)

data class Five06(
    val f1: Boolean,
    val f2: String,
    val f3: Int,
    val f4: Double,
    val f5: UInt,
)

fun writeFive06(w: SpecWriter, obj: Five06) {
    w.beginObject(5)
    w.writeField("f1"); w.writeBool(obj.f1)
    w.writeField("f2"); w.writeString(obj.f2)
    w.writeField("f3"); w.writeInt32(obj.f3)
    w.writeField("f4"); w.writeFloat64(obj.f4)
    w.writeField("f5"); w.writeUint32(obj.f5)
    w.endObject()
}

val Five06Codec: SpecCodec<Five06> = SpecCodec(
    encode = { w, obj -> writeFive06(w, obj) },
    decode = { r ->
        var f1Val: Boolean = false
        var f2Val: String = ""
        var f3Val: Int = 0
        var f4Val: Double = 0.0
        var f5Val: UInt = 0u
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "f1" -> f1Val = r.readBool()
                "f2" -> f2Val = r.readString()
                "f3" -> f3Val = r.readInt32()
                "f4" -> f4Val = r.readFloat64()
                "f5" -> f5Val = r.readUint32()
                else -> r.skip()
            }
        }
        r.endObject()
        Five06(f1 = f1Val, f2 = f2Val, f3 = f3Val, f4 = f4Val, f5 = f5Val)
    }
)

data class Five07(
    val f1: ByteArray,
    val f2: ByteArray,
    val f3: String,
    val f4: Int,
    val f5: Double,
)

fun writeFive07(w: SpecWriter, obj: Five07) {
    w.beginObject(5)
    w.writeField("f1"); w.writeBytes(obj.f1)
    w.writeField("f2"); w.writeBytes(obj.f2)
    w.writeField("f3"); w.writeString(obj.f3)
    w.writeField("f4"); w.writeInt32(obj.f4)
    w.writeField("f5"); w.writeFloat64(obj.f5)
    w.endObject()
}

val Five07Codec: SpecCodec<Five07> = SpecCodec(
    encode = { w, obj -> writeFive07(w, obj) },
    decode = { r ->
        var f1Val: ByteArray = byteArrayOf()
        var f2Val: ByteArray = byteArrayOf()
        var f3Val: String = ""
        var f4Val: Int = 0
        var f5Val: Double = 0.0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "f1" -> f1Val = r.readBytes()
                "f2" -> f2Val = r.readBytes()
                "f3" -> f3Val = r.readString()
                "f4" -> f4Val = r.readInt32()
                "f5" -> f5Val = r.readFloat64()
                else -> r.skip()
            }
        }
        r.endObject()
        Five07(f1 = f1Val, f2 = f2Val, f3 = f3Val, f4 = f4Val, f5 = f5Val)
    }
)

data class Five08(
    val f1: UByte,
    val f2: UShort,
    val f3: UInt,
    val f4: Byte,
    val f5: Short,
)

fun writeFive08(w: SpecWriter, obj: Five08) {
    w.beginObject(5)
    w.writeField("f1"); w.writeUint32(obj.f1.toUInt())
    w.writeField("f2"); w.writeUint32(obj.f2.toUInt())
    w.writeField("f3"); w.writeUint32(obj.f3)
    w.writeField("f4"); w.writeInt32(obj.f4.toInt())
    w.writeField("f5"); w.writeInt32(obj.f5.toInt())
    w.endObject()
}

val Five08Codec: SpecCodec<Five08> = SpecCodec(
    encode = { w, obj -> writeFive08(w, obj) },
    decode = { r ->
        var f1Val: UByte = 0u
        var f2Val: UShort = 0u
        var f3Val: UInt = 0u
        var f4Val: Byte = 0
        var f5Val: Short = 0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "f1" -> f1Val = r.readUint32().toUByte()
                "f2" -> f2Val = r.readUint32().toUShort()
                "f3" -> f3Val = r.readUint32()
                "f4" -> f4Val = r.readInt32().toByte()
                "f5" -> f5Val = r.readInt32().toShort()
                else -> r.skip()
            }
        }
        r.endObject()
        Five08(f1 = f1Val, f2 = f2Val, f3 = f3Val, f4 = f4Val, f5 = f5Val)
    }
)

data class Five09(
    val f1: Float,
    val f2: Double,
    val f3: Int,
    val f4: Long,
    val f5: String,
)

fun writeFive09(w: SpecWriter, obj: Five09) {
    w.beginObject(5)
    w.writeField("f1"); w.writeFloat32(obj.f1)
    w.writeField("f2"); w.writeFloat64(obj.f2)
    w.writeField("f3"); w.writeInt32(obj.f3)
    w.writeField("f4"); w.writeInt64(obj.f4)
    w.writeField("f5"); w.writeString(obj.f5)
    w.endObject()
}

val Five09Codec: SpecCodec<Five09> = SpecCodec(
    encode = { w, obj -> writeFive09(w, obj) },
    decode = { r ->
        var f1Val: Float = 0f
        var f2Val: Double = 0.0
        var f3Val: Int = 0
        var f4Val: Long = 0L
        var f5Val: String = ""
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "f1" -> f1Val = r.readFloat32()
                "f2" -> f2Val = r.readFloat64()
                "f3" -> f3Val = r.readInt32()
                "f4" -> f4Val = r.readInt64()
                "f5" -> f5Val = r.readString()
                else -> r.skip()
            }
        }
        r.endObject()
        Five09(f1 = f1Val, f2 = f2Val, f3 = f3Val, f4 = f4Val, f5 = f5Val)
    }
)

data class Five10(
    val f1: String,
    val f2: Boolean,
    val f3: Long,
    val f4: ULong,
    val f5: Double,
)

fun writeFive10(w: SpecWriter, obj: Five10) {
    w.beginObject(5)
    w.writeField("f1"); w.writeString(obj.f1)
    w.writeField("f2"); w.writeBool(obj.f2)
    w.writeField("f3"); w.writeInt64(obj.f3)
    w.writeField("f4"); w.writeUint64(obj.f4)
    w.writeField("f5"); w.writeFloat64(obj.f5)
    w.endObject()
}

val Five10Codec: SpecCodec<Five10> = SpecCodec(
    encode = { w, obj -> writeFive10(w, obj) },
    decode = { r ->
        var f1Val: String = ""
        var f2Val: Boolean = false
        var f3Val: Long = 0L
        var f4Val: ULong = 0uL
        var f5Val: Double = 0.0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "f1" -> f1Val = r.readString()
                "f2" -> f2Val = r.readBool()
                "f3" -> f3Val = r.readInt64()
                "f4" -> f4Val = r.readUint64()
                "f5" -> f5Val = r.readFloat64()
                else -> r.skip()
            }
        }
        r.endObject()
        Five10(f1 = f1Val, f2 = f2Val, f3 = f3Val, f4 = f4Val, f5 = f5Val)
    }
)

data class Ten01(
    val f1: String,
    val f2: Boolean,
    val f3: Byte,
    val f4: Short,
    val f5: Int,
    val f6: Long,
    val f7: UByte,
    val f8: UShort,
    val f9: UInt,
    val f10: ULong,
)

fun writeTen01(w: SpecWriter, obj: Ten01) {
    w.beginObject(10)
    w.writeField("f1"); w.writeString(obj.f1)
    w.writeField("f2"); w.writeBool(obj.f2)
    w.writeField("f3"); w.writeInt32(obj.f3.toInt())
    w.writeField("f4"); w.writeInt32(obj.f4.toInt())
    w.writeField("f5"); w.writeInt32(obj.f5)
    w.writeField("f6"); w.writeInt64(obj.f6)
    w.writeField("f7"); w.writeUint32(obj.f7.toUInt())
    w.writeField("f8"); w.writeUint32(obj.f8.toUInt())
    w.writeField("f9"); w.writeUint32(obj.f9)
    w.writeField("f10"); w.writeUint64(obj.f10)
    w.endObject()
}

val Ten01Codec: SpecCodec<Ten01> = SpecCodec(
    encode = { w, obj -> writeTen01(w, obj) },
    decode = { r ->
        var f1Val: String = ""
        var f2Val: Boolean = false
        var f3Val: Byte = 0
        var f4Val: Short = 0
        var f5Val: Int = 0
        var f6Val: Long = 0L
        var f7Val: UByte = 0u
        var f8Val: UShort = 0u
        var f9Val: UInt = 0u
        var f10Val: ULong = 0uL
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "f1" -> f1Val = r.readString()
                "f2" -> f2Val = r.readBool()
                "f3" -> f3Val = r.readInt32().toByte()
                "f4" -> f4Val = r.readInt32().toShort()
                "f5" -> f5Val = r.readInt32()
                "f6" -> f6Val = r.readInt64()
                "f7" -> f7Val = r.readUint32().toUByte()
                "f8" -> f8Val = r.readUint32().toUShort()
                "f9" -> f9Val = r.readUint32()
                "f10" -> f10Val = r.readUint64()
                else -> r.skip()
            }
        }
        r.endObject()
        Ten01(f1 = f1Val, f2 = f2Val, f3 = f3Val, f4 = f4Val, f5 = f5Val, f6 = f6Val, f7 = f7Val, f8 = f8Val, f9 = f9Val, f10 = f10Val)
    }
)

data class Ten02(
    val f1: Short,
    val f2: Int,
    val f3: Long,
    val f4: UByte,
    val f5: UShort,
    val f6: UInt,
    val f7: ULong,
    val f8: Float,
    val f9: Double,
    val f10: ByteArray,
)

fun writeTen02(w: SpecWriter, obj: Ten02) {
    w.beginObject(10)
    w.writeField("f1"); w.writeInt32(obj.f1.toInt())
    w.writeField("f2"); w.writeInt32(obj.f2)
    w.writeField("f3"); w.writeInt64(obj.f3)
    w.writeField("f4"); w.writeUint32(obj.f4.toUInt())
    w.writeField("f5"); w.writeUint32(obj.f5.toUInt())
    w.writeField("f6"); w.writeUint32(obj.f6)
    w.writeField("f7"); w.writeUint64(obj.f7)
    w.writeField("f8"); w.writeFloat32(obj.f8)
    w.writeField("f9"); w.writeFloat64(obj.f9)
    w.writeField("f10"); w.writeBytes(obj.f10)
    w.endObject()
}

val Ten02Codec: SpecCodec<Ten02> = SpecCodec(
    encode = { w, obj -> writeTen02(w, obj) },
    decode = { r ->
        var f1Val: Short = 0
        var f2Val: Int = 0
        var f3Val: Long = 0L
        var f4Val: UByte = 0u
        var f5Val: UShort = 0u
        var f6Val: UInt = 0u
        var f7Val: ULong = 0uL
        var f8Val: Float = 0f
        var f9Val: Double = 0.0
        var f10Val: ByteArray = byteArrayOf()
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "f1" -> f1Val = r.readInt32().toShort()
                "f2" -> f2Val = r.readInt32()
                "f3" -> f3Val = r.readInt64()
                "f4" -> f4Val = r.readUint32().toUByte()
                "f5" -> f5Val = r.readUint32().toUShort()
                "f6" -> f6Val = r.readUint32()
                "f7" -> f7Val = r.readUint64()
                "f8" -> f8Val = r.readFloat32()
                "f9" -> f9Val = r.readFloat64()
                "f10" -> f10Val = r.readBytes()
                else -> r.skip()
            }
        }
        r.endObject()
        Ten02(f1 = f1Val, f2 = f2Val, f3 = f3Val, f4 = f4Val, f5 = f5Val, f6 = f6Val, f7 = f7Val, f8 = f8Val, f9 = f9Val, f10 = f10Val)
    }
)

data class Ten03(
    val f1: UByte,
    val f2: UShort,
    val f3: UInt,
    val f4: ULong,
    val f5: Float,
    val f6: Double,
    val f7: ByteArray,
    val f8: String,
    val f9: Boolean,
    val f10: Byte,
)

fun writeTen03(w: SpecWriter, obj: Ten03) {
    w.beginObject(10)
    w.writeField("f1"); w.writeUint32(obj.f1.toUInt())
    w.writeField("f2"); w.writeUint32(obj.f2.toUInt())
    w.writeField("f3"); w.writeUint32(obj.f3)
    w.writeField("f4"); w.writeUint64(obj.f4)
    w.writeField("f5"); w.writeFloat32(obj.f5)
    w.writeField("f6"); w.writeFloat64(obj.f6)
    w.writeField("f7"); w.writeBytes(obj.f7)
    w.writeField("f8"); w.writeString(obj.f8)
    w.writeField("f9"); w.writeBool(obj.f9)
    w.writeField("f10"); w.writeInt32(obj.f10.toInt())
    w.endObject()
}

val Ten03Codec: SpecCodec<Ten03> = SpecCodec(
    encode = { w, obj -> writeTen03(w, obj) },
    decode = { r ->
        var f1Val: UByte = 0u
        var f2Val: UShort = 0u
        var f3Val: UInt = 0u
        var f4Val: ULong = 0uL
        var f5Val: Float = 0f
        var f6Val: Double = 0.0
        var f7Val: ByteArray = byteArrayOf()
        var f8Val: String = ""
        var f9Val: Boolean = false
        var f10Val: Byte = 0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "f1" -> f1Val = r.readUint32().toUByte()
                "f2" -> f2Val = r.readUint32().toUShort()
                "f3" -> f3Val = r.readUint32()
                "f4" -> f4Val = r.readUint64()
                "f5" -> f5Val = r.readFloat32()
                "f6" -> f6Val = r.readFloat64()
                "f7" -> f7Val = r.readBytes()
                "f8" -> f8Val = r.readString()
                "f9" -> f9Val = r.readBool()
                "f10" -> f10Val = r.readInt32().toByte()
                else -> r.skip()
            }
        }
        r.endObject()
        Ten03(f1 = f1Val, f2 = f2Val, f3 = f3Val, f4 = f4Val, f5 = f5Val, f6 = f6Val, f7 = f7Val, f8 = f8Val, f9 = f9Val, f10 = f10Val)
    }
)

data class Ten04(
    val f1: ULong,
    val f2: Float,
    val f3: Double,
    val f4: ByteArray,
    val f5: String,
    val f6: Boolean,
    val f7: Byte,
    val f8: Short,
    val f9: Int,
    val f10: Long,
)

fun writeTen04(w: SpecWriter, obj: Ten04) {
    w.beginObject(10)
    w.writeField("f1"); w.writeUint64(obj.f1)
    w.writeField("f2"); w.writeFloat32(obj.f2)
    w.writeField("f3"); w.writeFloat64(obj.f3)
    w.writeField("f4"); w.writeBytes(obj.f4)
    w.writeField("f5"); w.writeString(obj.f5)
    w.writeField("f6"); w.writeBool(obj.f6)
    w.writeField("f7"); w.writeInt32(obj.f7.toInt())
    w.writeField("f8"); w.writeInt32(obj.f8.toInt())
    w.writeField("f9"); w.writeInt32(obj.f9)
    w.writeField("f10"); w.writeInt64(obj.f10)
    w.endObject()
}

val Ten04Codec: SpecCodec<Ten04> = SpecCodec(
    encode = { w, obj -> writeTen04(w, obj) },
    decode = { r ->
        var f1Val: ULong = 0uL
        var f2Val: Float = 0f
        var f3Val: Double = 0.0
        var f4Val: ByteArray = byteArrayOf()
        var f5Val: String = ""
        var f6Val: Boolean = false
        var f7Val: Byte = 0
        var f8Val: Short = 0
        var f9Val: Int = 0
        var f10Val: Long = 0L
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "f1" -> f1Val = r.readUint64()
                "f2" -> f2Val = r.readFloat32()
                "f3" -> f3Val = r.readFloat64()
                "f4" -> f4Val = r.readBytes()
                "f5" -> f5Val = r.readString()
                "f6" -> f6Val = r.readBool()
                "f7" -> f7Val = r.readInt32().toByte()
                "f8" -> f8Val = r.readInt32().toShort()
                "f9" -> f9Val = r.readInt32()
                "f10" -> f10Val = r.readInt64()
                else -> r.skip()
            }
        }
        r.endObject()
        Ten04(f1 = f1Val, f2 = f2Val, f3 = f3Val, f4 = f4Val, f5 = f5Val, f6 = f6Val, f7 = f7Val, f8 = f8Val, f9 = f9Val, f10 = f10Val)
    }
)

data class Ten05(
    val f1: ByteArray,
    val f2: String,
    val f3: Boolean,
    val f4: Byte,
    val f5: Short,
    val f6: Int,
    val f7: Long,
    val f8: UByte,
    val f9: UShort,
    val f10: UInt,
)

fun writeTen05(w: SpecWriter, obj: Ten05) {
    w.beginObject(10)
    w.writeField("f1"); w.writeBytes(obj.f1)
    w.writeField("f2"); w.writeString(obj.f2)
    w.writeField("f3"); w.writeBool(obj.f3)
    w.writeField("f4"); w.writeInt32(obj.f4.toInt())
    w.writeField("f5"); w.writeInt32(obj.f5.toInt())
    w.writeField("f6"); w.writeInt32(obj.f6)
    w.writeField("f7"); w.writeInt64(obj.f7)
    w.writeField("f8"); w.writeUint32(obj.f8.toUInt())
    w.writeField("f9"); w.writeUint32(obj.f9.toUInt())
    w.writeField("f10"); w.writeUint32(obj.f10)
    w.endObject()
}

val Ten05Codec: SpecCodec<Ten05> = SpecCodec(
    encode = { w, obj -> writeTen05(w, obj) },
    decode = { r ->
        var f1Val: ByteArray = byteArrayOf()
        var f2Val: String = ""
        var f3Val: Boolean = false
        var f4Val: Byte = 0
        var f5Val: Short = 0
        var f6Val: Int = 0
        var f7Val: Long = 0L
        var f8Val: UByte = 0u
        var f9Val: UShort = 0u
        var f10Val: UInt = 0u
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "f1" -> f1Val = r.readBytes()
                "f2" -> f2Val = r.readString()
                "f3" -> f3Val = r.readBool()
                "f4" -> f4Val = r.readInt32().toByte()
                "f5" -> f5Val = r.readInt32().toShort()
                "f6" -> f6Val = r.readInt32()
                "f7" -> f7Val = r.readInt64()
                "f8" -> f8Val = r.readUint32().toUByte()
                "f9" -> f9Val = r.readUint32().toUShort()
                "f10" -> f10Val = r.readUint32()
                else -> r.skip()
            }
        }
        r.endObject()
        Ten05(f1 = f1Val, f2 = f2Val, f3 = f3Val, f4 = f4Val, f5 = f5Val, f6 = f6Val, f7 = f7Val, f8 = f8Val, f9 = f9Val, f10 = f10Val)
    }
)
