// Generated by @specodec/typespec-emitter-kotlin. DO NOT EDIT.
package all_types_nested_deep

import specodec.*

data class DeepModel(
    val payload: ByteArray,
    val count: Long,
)

fun writeDeepModel(w: SpecWriter, obj: DeepModel) {
    w.beginObject(2)
    w.writeField("payload"); w.writeBytes(obj.payload)
    w.writeField("count"); w.writeInt64(obj.count)
    w.endObject()
}

val DeepModelCodec: SpecCodec<DeepModel> = SpecCodec(
    encode = { w, obj -> writeDeepModel(w, obj) },
    decode = { r ->
        var payloadVal: ByteArray = byteArrayOf()
        var countVal: Long = 0L
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "payload" -> payloadVal = r.readBytes()
                "count" -> countVal = r.readInt64()
                else -> r.skip()
            }
        }
        r.endObject()
        DeepModel(payload = payloadVal, count = countVal)
    }
)
