// Generated by @specodec/typespec-emitter-kotlin. DO NOT EDIT.
package all_types

import specodec.*

data class Inner(
    val x: Int,
    val y: Int,
)

fun writeInner(w: SpecWriter, obj: Inner) {
    w.beginObject(2)
    w.writeField("x"); w.writeInt32(obj.x)
    w.writeField("y"); w.writeInt32(obj.y)
    w.endObject()
}

val InnerCodec: SpecCodec<Inner> = SpecCodec(
    encode = { w, obj -> writeInner(w, obj) },
    decode = { r ->
        var xVal: Int = 0
        var yVal: Int = 0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "x" -> xVal = r.readInt32()
                "y" -> yVal = r.readInt32()
                else -> r.skip()
            }
        }
        r.endObject()
        Inner(x = xVal, y = yVal)
    }
)

data class Coord(
    val lat: Double,
    val lng: Double,
)

fun writeCoord(w: SpecWriter, obj: Coord) {
    w.beginObject(2)
    w.writeField("lat"); w.writeFloat64(obj.lat)
    w.writeField("lng"); w.writeFloat64(obj.lng)
    w.endObject()
}

val CoordCodec: SpecCodec<Coord> = SpecCodec(
    encode = { w, obj -> writeCoord(w, obj) },
    decode = { r ->
        var latVal: Double = 0.0
        var lngVal: Double = 0.0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "lat" -> latVal = r.readFloat64()
                "lng" -> lngVal = r.readFloat64()
                else -> r.skip()
            }
        }
        r.endObject()
        Coord(lat = latVal, lng = lngVal)
    }
)

data class IdVal(
    val id: String,
    val value: Int,
)

fun writeIdVal(w: SpecWriter, obj: IdVal) {
    w.beginObject(2)
    w.writeField("id"); w.writeString(obj.id)
    w.writeField("value"); w.writeInt32(obj.value)
    w.endObject()
}

val IdValCodec: SpecCodec<IdVal> = SpecCodec(
    encode = { w, obj -> writeIdVal(w, obj) },
    decode = { r ->
        var idVal: String = ""
        var valueVal: Int = 0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "id" -> idVal = r.readString()
                "value" -> valueVal = r.readInt32()
                else -> r.skip()
            }
        }
        r.endObject()
        IdVal(id = idVal, value = valueVal)
    }
)

data class Label(
    val key: String,
    val text: String,
)

fun writeLabel(w: SpecWriter, obj: Label) {
    w.beginObject(2)
    w.writeField("key"); w.writeString(obj.key)
    w.writeField("text"); w.writeString(obj.text)
    w.endObject()
}

val LabelCodec: SpecCodec<Label> = SpecCodec(
    encode = { w, obj -> writeLabel(w, obj) },
    decode = { r ->
        var keyVal: String = ""
        var textVal: String = ""
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "key" -> keyVal = r.readString()
                "text" -> textVal = r.readString()
                else -> r.skip()
            }
        }
        r.endObject()
        Label(key = keyVal, text = textVal)
    }
)

data class Money(
    val amount: Long,
    val currency: String,
)

fun writeMoney(w: SpecWriter, obj: Money) {
    w.beginObject(2)
    w.writeField("amount"); w.writeInt64(obj.amount)
    w.writeField("currency"); w.writeString(obj.currency)
    w.endObject()
}

val MoneyCodec: SpecCodec<Money> = SpecCodec(
    encode = { w, obj -> writeMoney(w, obj) },
    decode = { r ->
        var amountVal: Long = 0L
        var currencyVal: String = ""
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "amount" -> amountVal = r.readInt64()
                "currency" -> currencyVal = r.readString()
                else -> r.skip()
            }
        }
        r.endObject()
        Money(amount = amountVal, currency = currencyVal)
    }
)

data class Range32(
    val min: Int,
    val max: Int,
)

fun writeRange32(w: SpecWriter, obj: Range32) {
    w.beginObject(2)
    w.writeField("min"); w.writeInt32(obj.min)
    w.writeField("max"); w.writeInt32(obj.max)
    w.endObject()
}

val Range32Codec: SpecCodec<Range32> = SpecCodec(
    encode = { w, obj -> writeRange32(w, obj) },
    decode = { r ->
        var minVal: Int = 0
        var maxVal: Int = 0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "min" -> minVal = r.readInt32()
                "max" -> maxVal = r.readInt32()
                else -> r.skip()
            }
        }
        r.endObject()
        Range32(min = minVal, max = maxVal)
    }
)

data class Addr(
    val street: String,
    val city: String,
    val zip: String,
)

fun writeAddr(w: SpecWriter, obj: Addr) {
    w.beginObject(3)
    w.writeField("street"); w.writeString(obj.street)
    w.writeField("city"); w.writeString(obj.city)
    w.writeField("zip"); w.writeString(obj.zip)
    w.endObject()
}

val AddrCodec: SpecCodec<Addr> = SpecCodec(
    encode = { w, obj -> writeAddr(w, obj) },
    decode = { r ->
        var streetVal: String = ""
        var cityVal: String = ""
        var zipVal: String = ""
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "street" -> streetVal = r.readString()
                "city" -> cityVal = r.readString()
                "zip" -> zipVal = r.readString()
                else -> r.skip()
            }
        }
        r.endObject()
        Addr(street = streetVal, city = cityVal, zip = zipVal)
    }
)

data class Point3(
    val x: Double,
    val y: Double,
    val z: Double,
)

fun writePoint3(w: SpecWriter, obj: Point3) {
    w.beginObject(3)
    w.writeField("x"); w.writeFloat64(obj.x)
    w.writeField("y"); w.writeFloat64(obj.y)
    w.writeField("z"); w.writeFloat64(obj.z)
    w.endObject()
}

val Point3Codec: SpecCodec<Point3> = SpecCodec(
    encode = { w, obj -> writePoint3(w, obj) },
    decode = { r ->
        var xVal: Double = 0.0
        var yVal: Double = 0.0
        var zVal: Double = 0.0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "x" -> xVal = r.readFloat64()
                "y" -> yVal = r.readFloat64()
                "z" -> zVal = r.readFloat64()
                else -> r.skip()
            }
        }
        r.endObject()
        Point3(x = xVal, y = yVal, z = zVal)
    }
)

data class OptInner(
    val name: String? = null,
    val score: Double? = null,
    val tag: String? = null,
)

fun writeOptInner(w: SpecWriter, obj: OptInner) {
    var fieldCount = 0
    if (obj.name != null) fieldCount++
    if (obj.score != null) fieldCount++
    if (obj.tag != null) fieldCount++
    w.beginObject(fieldCount)
    if (obj.name != null) { w.writeField("name"); w.writeString(obj.name) }
    if (obj.score != null) { w.writeField("score"); w.writeFloat64(obj.score) }
    if (obj.tag != null) { w.writeField("tag"); w.writeString(obj.tag) }
    w.endObject()
}

val OptInnerCodec: SpecCodec<OptInner> = SpecCodec(
    encode = { w, obj -> writeOptInner(w, obj) },
    decode = { r ->
        var nameVal: String? = null
        var scoreVal: Double? = null
        var tagVal: String? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "name" -> nameVal = r.readString()
                "score" -> scoreVal = r.readFloat64()
                "tag" -> tagVal = r.readString()
                else -> r.skip()
            }
        }
        r.endObject()
        OptInner(name = nameVal, score = scoreVal, tag = tagVal)
    }
)
