// Generated by @specodec/typespec-emitter-kotlin. DO NOT EDIT.
package all_types_mixed

import specodec.*
import all_types.*

data class ModelArr1(
    val points: List<Inner>,
)

fun writeModelArr1(w: SpecWriter, obj: ModelArr1) {
    w.beginObject(1)
    w.writeField("points"); w.beginArray(obj.points.size)
        for (item in obj.points) { w.nextElement(); writeInner(w, item) }
        w.endArray()
    w.endObject()
}

val ModelArr1Codec: SpecCodec<ModelArr1> = SpecCodec(
    encode = { w, obj -> writeModelArr1(w, obj) },
    decode = { r ->
        var pointsVal: List<Inner> = emptyList()
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "points" -> pointsVal = run { val list = mutableListOf<Inner>(); r.beginArray(); while (r.hasNextElement()) { list.add(InnerCodec.decode(r)) }; r.endArray(); list }
                else -> r.skip()
            }
        }
        r.endObject()
        ModelArr1(points = pointsVal)
    }
)

data class ModelArr2(
    val coords: List<Coord>,
)

fun writeModelArr2(w: SpecWriter, obj: ModelArr2) {
    w.beginObject(1)
    w.writeField("coords"); w.beginArray(obj.coords.size)
        for (item in obj.coords) { w.nextElement(); writeCoord(w, item) }
        w.endArray()
    w.endObject()
}

val ModelArr2Codec: SpecCodec<ModelArr2> = SpecCodec(
    encode = { w, obj -> writeModelArr2(w, obj) },
    decode = { r ->
        var coordsVal: List<Coord> = emptyList()
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "coords" -> coordsVal = run { val list = mutableListOf<Coord>(); r.beginArray(); while (r.hasNextElement()) { list.add(CoordCodec.decode(r)) }; r.endArray(); list }
                else -> r.skip()
            }
        }
        r.endObject()
        ModelArr2(coords = coordsVal)
    }
)

data class ModelArr3(
    val items: List<IdVal>,
    val tag: String,
)

fun writeModelArr3(w: SpecWriter, obj: ModelArr3) {
    w.beginObject(2)
    w.writeField("items"); w.beginArray(obj.items.size)
        for (item in obj.items) { w.nextElement(); writeIdVal(w, item) }
        w.endArray()
    w.writeField("tag"); w.writeString(obj.tag)
    w.endObject()
}

val ModelArr3Codec: SpecCodec<ModelArr3> = SpecCodec(
    encode = { w, obj -> writeModelArr3(w, obj) },
    decode = { r ->
        var itemsVal: List<IdVal> = emptyList()
        var tagVal: String = ""
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "items" -> itemsVal = run { val list = mutableListOf<IdVal>(); r.beginArray(); while (r.hasNextElement()) { list.add(IdValCodec.decode(r)) }; r.endArray(); list }
                "tag" -> tagVal = r.readString()
                else -> r.skip()
            }
        }
        r.endObject()
        ModelArr3(items = itemsVal, tag = tagVal)
    }
)

data class ModelArr4(
    val labels: List<Label>,
    val count: Int,
)

fun writeModelArr4(w: SpecWriter, obj: ModelArr4) {
    w.beginObject(2)
    w.writeField("labels"); w.beginArray(obj.labels.size)
        for (item in obj.labels) { w.nextElement(); writeLabel(w, item) }
        w.endArray()
    w.writeField("count"); w.writeInt32(obj.count)
    w.endObject()
}

val ModelArr4Codec: SpecCodec<ModelArr4> = SpecCodec(
    encode = { w, obj -> writeModelArr4(w, obj) },
    decode = { r ->
        var labelsVal: List<Label> = emptyList()
        var countVal: Int = 0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "labels" -> labelsVal = run { val list = mutableListOf<Label>(); r.beginArray(); while (r.hasNextElement()) { list.add(LabelCodec.decode(r)) }; r.endArray(); list }
                "count" -> countVal = r.readInt32()
                else -> r.skip()
            }
        }
        r.endObject()
        ModelArr4(labels = labelsVal, count = countVal)
    }
)

data class ModelArr5(
    val arr: List<Money>,
    val bs: List<Addr>,
)

fun writeModelArr5(w: SpecWriter, obj: ModelArr5) {
    w.beginObject(2)
    w.writeField("arr"); w.beginArray(obj.arr.size)
        for (item in obj.arr) { w.nextElement(); writeMoney(w, item) }
        w.endArray()
    w.writeField("bs"); w.beginArray(obj.bs.size)
        for (item in obj.bs) { w.nextElement(); writeAddr(w, item) }
        w.endArray()
    w.endObject()
}

val ModelArr5Codec: SpecCodec<ModelArr5> = SpecCodec(
    encode = { w, obj -> writeModelArr5(w, obj) },
    decode = { r ->
        var arrVal: List<Money> = emptyList()
        var bsVal: List<Addr> = emptyList()
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "arr" -> arrVal = run { val list = mutableListOf<Money>(); r.beginArray(); while (r.hasNextElement()) { list.add(MoneyCodec.decode(r)) }; r.endArray(); list }
                "bs" -> bsVal = run { val list = mutableListOf<Addr>(); r.beginArray(); while (r.hasNextElement()) { list.add(AddrCodec.decode(r)) }; r.endArray(); list }
                else -> r.skip()
            }
        }
        r.endObject()
        ModelArr5(arr = arrVal, bs = bsVal)
    }
)

data class Mix01(
    val name: String,
    val value: Int,
    val point: Inner,
)

fun writeMix01(w: SpecWriter, obj: Mix01) {
    w.beginObject(3)
    w.writeField("name"); w.writeString(obj.name)
    w.writeField("value"); w.writeInt32(obj.value)
    w.writeField("point"); writeInner(w, obj.point)
    w.endObject()
}

val Mix01Codec: SpecCodec<Mix01> = SpecCodec(
    encode = { w, obj -> writeMix01(w, obj) },
    decode = { r ->
        var nameVal: String = ""
        var valueVal: Int = 0
        var pointVal: Inner? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "name" -> nameVal = r.readString()
                "value" -> valueVal = r.readInt32()
                "point" -> pointVal = InnerCodec.decode(r)
                else -> r.skip()
            }
        }
        r.endObject()
        Mix01(name = nameVal, value = valueVal, point = pointVal!!)
    }
)

data class Mix02(
    val id: String,
    val loc: Coord,
    val tags: List<String>,
)

fun writeMix02(w: SpecWriter, obj: Mix02) {
    w.beginObject(3)
    w.writeField("id"); w.writeString(obj.id)
    w.writeField("loc"); writeCoord(w, obj.loc)
    w.writeField("tags"); w.beginArray(obj.tags.size)
        for (item in obj.tags) { w.nextElement(); w.writeString(item) }
        w.endArray()
    w.endObject()
}

val Mix02Codec: SpecCodec<Mix02> = SpecCodec(
    encode = { w, obj -> writeMix02(w, obj) },
    decode = { r ->
        var idVal: String = ""
        var locVal: Coord? = null
        var tagsVal: List<String> = emptyList()
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "id" -> idVal = r.readString()
                "loc" -> locVal = CoordCodec.decode(r)
                "tags" -> tagsVal = run { val list = mutableListOf<String>(); r.beginArray(); while (r.hasNextElement()) { list.add(r.readString()) }; r.endArray(); list }
                else -> r.skip()
            }
        }
        r.endObject()
        Mix02(id = idVal, loc = locVal!!, tags = tagsVal)
    }
)

data class Mix03(
    val label: String,
    val valueRange: Range32,
    val active: Boolean,
)

fun writeMix03(w: SpecWriter, obj: Mix03) {
    w.beginObject(3)
    w.writeField("label"); w.writeString(obj.label)
    w.writeField("value_range"); writeRange32(w, obj.valueRange)
    w.writeField("active"); w.writeBool(obj.active)
    w.endObject()
}

val Mix03Codec: SpecCodec<Mix03> = SpecCodec(
    encode = { w, obj -> writeMix03(w, obj) },
    decode = { r ->
        var labelVal: String = ""
        var valueRangeVal: Range32? = null
        var activeVal: Boolean = false
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "label" -> labelVal = r.readString()
                "value_range" -> valueRangeVal = Range32Codec.decode(r)
                "active" -> activeVal = r.readBool()
                else -> r.skip()
            }
        }
        r.endObject()
        Mix03(label = labelVal, valueRange = valueRangeVal!!, active = activeVal)
    }
)

data class Mix04(
    val title: String,
    val price: Money,
    val inStock: Boolean,
    val rating: Double,
)

fun writeMix04(w: SpecWriter, obj: Mix04) {
    w.beginObject(4)
    w.writeField("title"); w.writeString(obj.title)
    w.writeField("price"); writeMoney(w, obj.price)
    w.writeField("inStock"); w.writeBool(obj.inStock)
    w.writeField("rating"); w.writeFloat64(obj.rating)
    w.endObject()
}

val Mix04Codec: SpecCodec<Mix04> = SpecCodec(
    encode = { w, obj -> writeMix04(w, obj) },
    decode = { r ->
        var titleVal: String = ""
        var priceVal: Money? = null
        var inStockVal: Boolean = false
        var ratingVal: Double = 0.0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "title" -> titleVal = r.readString()
                "price" -> priceVal = MoneyCodec.decode(r)
                "inStock" -> inStockVal = r.readBool()
                "rating" -> ratingVal = r.readFloat64()
                else -> r.skip()
            }
        }
        r.endObject()
        Mix04(title = titleVal, price = priceVal!!, inStock = inStockVal, rating = ratingVal)
    }
)

data class Mix05(
    val addr: Addr,
    val coords: List<Coord>,
)

fun writeMix05(w: SpecWriter, obj: Mix05) {
    w.beginObject(2)
    w.writeField("addr"); writeAddr(w, obj.addr)
    w.writeField("coords"); w.beginArray(obj.coords.size)
        for (item in obj.coords) { w.nextElement(); writeCoord(w, item) }
        w.endArray()
    w.endObject()
}

val Mix05Codec: SpecCodec<Mix05> = SpecCodec(
    encode = { w, obj -> writeMix05(w, obj) },
    decode = { r ->
        var addrVal: Addr? = null
        var coordsVal: List<Coord> = emptyList()
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "addr" -> addrVal = AddrCodec.decode(r)
                "coords" -> coordsVal = run { val list = mutableListOf<Coord>(); r.beginArray(); while (r.hasNextElement()) { list.add(CoordCodec.decode(r)) }; r.endArray(); list }
                else -> r.skip()
            }
        }
        r.endObject()
        Mix05(addr = addrVal!!, coords = coordsVal)
    }
)

data class Mix06(
    val name: String,
    val age: Int,
    val address: Addr? = null,
    val email: String? = null,
)

fun writeMix06(w: SpecWriter, obj: Mix06) {
    var fieldCount = 2
    if (obj.address != null) fieldCount++
    if (obj.email != null) fieldCount++
    w.beginObject(fieldCount)
    w.writeField("name"); w.writeString(obj.name)
    w.writeField("age"); w.writeInt32(obj.age)
    if (obj.address != null) { w.writeField("address"); writeAddr(w, obj.address) }
    if (obj.email != null) { w.writeField("email"); w.writeString(obj.email) }
    w.endObject()
}

val Mix06Codec: SpecCodec<Mix06> = SpecCodec(
    encode = { w, obj -> writeMix06(w, obj) },
    decode = { r ->
        var nameVal: String = ""
        var ageVal: Int = 0
        var addressVal: Addr? = null
        var emailVal: String? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "name" -> nameVal = r.readString()
                "age" -> ageVal = r.readInt32()
                "address" -> addressVal = if (r.isNull()) { r.readNull(); null } else { AddrCodec.decode(r) }
                "email" -> emailVal = r.readString()
                else -> r.skip()
            }
        }
        r.endObject()
        Mix06(name = nameVal, age = ageVal, address = addressVal, email = emailVal)
    }
)

data class Mix07(
    val origin: Point3,
    val dest: Point3,
    val distance: Double,
)

fun writeMix07(w: SpecWriter, obj: Mix07) {
    w.beginObject(3)
    w.writeField("origin"); writePoint3(w, obj.origin)
    w.writeField("dest"); writePoint3(w, obj.dest)
    w.writeField("distance"); w.writeFloat64(obj.distance)
    w.endObject()
}

val Mix07Codec: SpecCodec<Mix07> = SpecCodec(
    encode = { w, obj -> writeMix07(w, obj) },
    decode = { r ->
        var originVal: Point3? = null
        var destVal: Point3? = null
        var distanceVal: Double = 0.0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "origin" -> originVal = Point3Codec.decode(r)
                "dest" -> destVal = Point3Codec.decode(r)
                "distance" -> distanceVal = r.readFloat64()
                else -> r.skip()
            }
        }
        r.endObject()
        Mix07(origin = originVal!!, dest = destVal!!, distance = distanceVal)
    }
)

data class Mix08(
    val keys: List<String>,
    val values: List<Int>,
    val meta: Label? = null,
)

fun writeMix08(w: SpecWriter, obj: Mix08) {
    var fieldCount = 2
    if (obj.meta != null) fieldCount++
    w.beginObject(fieldCount)
    w.writeField("keys"); w.beginArray(obj.keys.size)
        for (item in obj.keys) { w.nextElement(); w.writeString(item) }
        w.endArray()
    w.writeField("values"); w.beginArray(obj.values.size)
        for (item in obj.values) { w.nextElement(); w.writeInt32(item) }
        w.endArray()
    if (obj.meta != null) { w.writeField("meta"); writeLabel(w, obj.meta) }
    w.endObject()
}

val Mix08Codec: SpecCodec<Mix08> = SpecCodec(
    encode = { w, obj -> writeMix08(w, obj) },
    decode = { r ->
        var keysVal: List<String> = emptyList()
        var valuesVal: List<Int> = emptyList()
        var metaVal: Label? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "keys" -> keysVal = run { val list = mutableListOf<String>(); r.beginArray(); while (r.hasNextElement()) { list.add(r.readString()) }; r.endArray(); list }
                "values" -> valuesVal = run { val list = mutableListOf<Int>(); r.beginArray(); while (r.hasNextElement()) { list.add(r.readInt32()) }; r.endArray(); list }
                "meta" -> metaVal = if (r.isNull()) { r.readNull(); null } else { LabelCodec.decode(r) }
                else -> r.skip()
            }
        }
        r.endObject()
        Mix08(keys = keysVal, values = valuesVal, meta = metaVal)
    }
)

data class Mix09(
    val id: Long,
    val payload: ByteArray,
    val checksum: UInt,
    val prev: IdVal? = null,
)

fun writeMix09(w: SpecWriter, obj: Mix09) {
    var fieldCount = 3
    if (obj.prev != null) fieldCount++
    w.beginObject(fieldCount)
    w.writeField("id"); w.writeInt64(obj.id)
    w.writeField("payload"); w.writeBytes(obj.payload)
    w.writeField("checksum"); w.writeUint32(obj.checksum)
    if (obj.prev != null) { w.writeField("prev"); writeIdVal(w, obj.prev) }
    w.endObject()
}

val Mix09Codec: SpecCodec<Mix09> = SpecCodec(
    encode = { w, obj -> writeMix09(w, obj) },
    decode = { r ->
        var idVal: Long = 0L
        var payloadVal: ByteArray = byteArrayOf()
        var checksumVal: UInt = 0u
        var prevVal: IdVal? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "id" -> idVal = r.readInt64()
                "payload" -> payloadVal = r.readBytes()
                "checksum" -> checksumVal = r.readUint32()
                "prev" -> prevVal = if (r.isNull()) { r.readNull(); null } else { IdValCodec.decode(r) }
                else -> r.skip()
            }
        }
        r.endObject()
        Mix09(id = idVal, payload = payloadVal, checksum = checksumVal, prev = prevVal)
    }
)

data class Mix10(
    val items: List<String>,
    val total: Int,
    val avg: Double,
    val valueRange: Range32,
)

fun writeMix10(w: SpecWriter, obj: Mix10) {
    w.beginObject(4)
    w.writeField("items"); w.beginArray(obj.items.size)
        for (item in obj.items) { w.nextElement(); w.writeString(item) }
        w.endArray()
    w.writeField("total"); w.writeInt32(obj.total)
    w.writeField("avg"); w.writeFloat64(obj.avg)
    w.writeField("value_range"); writeRange32(w, obj.valueRange)
    w.endObject()
}

val Mix10Codec: SpecCodec<Mix10> = SpecCodec(
    encode = { w, obj -> writeMix10(w, obj) },
    decode = { r ->
        var itemsVal: List<String> = emptyList()
        var totalVal: Int = 0
        var avgVal: Double = 0.0
        var valueRangeVal: Range32? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "items" -> itemsVal = run { val list = mutableListOf<String>(); r.beginArray(); while (r.hasNextElement()) { list.add(r.readString()) }; r.endArray(); list }
                "total" -> totalVal = r.readInt32()
                "avg" -> avgVal = r.readFloat64()
                "value_range" -> valueRangeVal = Range32Codec.decode(r)
                else -> r.skip()
            }
        }
        r.endObject()
        Mix10(items = itemsVal, total = totalVal, avg = avgVal, valueRange = valueRangeVal!!)
    }
)

data class Mix11(
    val name: String,
    val values: List<Double>,
    val nested: Inner? = null,
    val flag: Boolean? = null,
)

fun writeMix11(w: SpecWriter, obj: Mix11) {
    var fieldCount = 2
    if (obj.nested != null) fieldCount++
    if (obj.flag != null) fieldCount++
    w.beginObject(fieldCount)
    w.writeField("name"); w.writeString(obj.name)
    w.writeField("values"); w.beginArray(obj.values.size)
        for (item in obj.values) { w.nextElement(); w.writeFloat64(item) }
        w.endArray()
    if (obj.nested != null) { w.writeField("nested"); writeInner(w, obj.nested) }
    if (obj.flag != null) { w.writeField("flag"); w.writeBool(obj.flag) }
    w.endObject()
}

val Mix11Codec: SpecCodec<Mix11> = SpecCodec(
    encode = { w, obj -> writeMix11(w, obj) },
    decode = { r ->
        var nameVal: String = ""
        var valuesVal: List<Double> = emptyList()
        var nestedVal: Inner? = null
        var flagVal: Boolean? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "name" -> nameVal = r.readString()
                "values" -> valuesVal = run { val list = mutableListOf<Double>(); r.beginArray(); while (r.hasNextElement()) { list.add(r.readFloat64()) }; r.endArray(); list }
                "nested" -> nestedVal = if (r.isNull()) { r.readNull(); null } else { InnerCodec.decode(r) }
                "flag" -> flagVal = r.readBool()
                else -> r.skip()
            }
        }
        r.endObject()
        Mix11(name = nameVal, values = valuesVal, nested = nestedVal, flag = flagVal)
    }
)

data class Mix12(
    val header: String,
    val entries: List<IdVal>,
    val footer: String? = null,
)

fun writeMix12(w: SpecWriter, obj: Mix12) {
    var fieldCount = 2
    if (obj.footer != null) fieldCount++
    w.beginObject(fieldCount)
    w.writeField("header"); w.writeString(obj.header)
    w.writeField("entries"); w.beginArray(obj.entries.size)
        for (item in obj.entries) { w.nextElement(); writeIdVal(w, item) }
        w.endArray()
    if (obj.footer != null) { w.writeField("footer"); w.writeString(obj.footer) }
    w.endObject()
}

val Mix12Codec: SpecCodec<Mix12> = SpecCodec(
    encode = { w, obj -> writeMix12(w, obj) },
    decode = { r ->
        var headerVal: String = ""
        var entriesVal: List<IdVal> = emptyList()
        var footerVal: String? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "header" -> headerVal = r.readString()
                "entries" -> entriesVal = run { val list = mutableListOf<IdVal>(); r.beginArray(); while (r.hasNextElement()) { list.add(IdValCodec.decode(r)) }; r.endArray(); list }
                "footer" -> footerVal = r.readString()
                else -> r.skip()
            }
        }
        r.endObject()
        Mix12(header = headerVal, entries = entriesVal, footer = footerVal)
    }
)

data class Mix13(
    val a: Int,
    val b: Double,
    val c: String,
    val d: Boolean,
    val e: ByteArray,
    val nested: Inner,
)

fun writeMix13(w: SpecWriter, obj: Mix13) {
    w.beginObject(6)
    w.writeField("a"); w.writeInt32(obj.a)
    w.writeField("b"); w.writeFloat64(obj.b)
    w.writeField("c"); w.writeString(obj.c)
    w.writeField("d"); w.writeBool(obj.d)
    w.writeField("e"); w.writeBytes(obj.e)
    w.writeField("nested"); writeInner(w, obj.nested)
    w.endObject()
}

val Mix13Codec: SpecCodec<Mix13> = SpecCodec(
    encode = { w, obj -> writeMix13(w, obj) },
    decode = { r ->
        var aVal: Int = 0
        var bVal: Double = 0.0
        var cVal: String = ""
        var dVal: Boolean = false
        var eVal: ByteArray = byteArrayOf()
        var nestedVal: Inner? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readInt32()
                "b" -> bVal = r.readFloat64()
                "c" -> cVal = r.readString()
                "d" -> dVal = r.readBool()
                "e" -> eVal = r.readBytes()
                "nested" -> nestedVal = InnerCodec.decode(r)
                else -> r.skip()
            }
        }
        r.endObject()
        Mix13(a = aVal, b = bVal, c = cVal, d = dVal, e = eVal, nested = nestedVal!!)
    }
)

data class Mix14(
    val amounts: List<Money>,
    val total: Long,
    val currency: String,
)

fun writeMix14(w: SpecWriter, obj: Mix14) {
    w.beginObject(3)
    w.writeField("amounts"); w.beginArray(obj.amounts.size)
        for (item in obj.amounts) { w.nextElement(); writeMoney(w, item) }
        w.endArray()
    w.writeField("total"); w.writeInt64(obj.total)
    w.writeField("currency"); w.writeString(obj.currency)
    w.endObject()
}

val Mix14Codec: SpecCodec<Mix14> = SpecCodec(
    encode = { w, obj -> writeMix14(w, obj) },
    decode = { r ->
        var amountsVal: List<Money> = emptyList()
        var totalVal: Long = 0L
        var currencyVal: String = ""
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "amounts" -> amountsVal = run { val list = mutableListOf<Money>(); r.beginArray(); while (r.hasNextElement()) { list.add(MoneyCodec.decode(r)) }; r.endArray(); list }
                "total" -> totalVal = r.readInt64()
                "currency" -> currencyVal = r.readString()
                else -> r.skip()
            }
        }
        r.endObject()
        Mix14(amounts = amountsVal, total = totalVal, currency = currencyVal)
    }
)

data class Mix15(
    val srcAddr: Addr,
    val dstAddr: Addr,
    val distance: Double,
    val duration: Double,
)

fun writeMix15(w: SpecWriter, obj: Mix15) {
    w.beginObject(4)
    w.writeField("src_addr"); writeAddr(w, obj.srcAddr)
    w.writeField("dst_addr"); writeAddr(w, obj.dstAddr)
    w.writeField("distance"); w.writeFloat64(obj.distance)
    w.writeField("duration"); w.writeFloat64(obj.duration)
    w.endObject()
}

val Mix15Codec: SpecCodec<Mix15> = SpecCodec(
    encode = { w, obj -> writeMix15(w, obj) },
    decode = { r ->
        var srcAddrVal: Addr? = null
        var dstAddrVal: Addr? = null
        var distanceVal: Double = 0.0
        var durationVal: Double = 0.0
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "src_addr" -> srcAddrVal = AddrCodec.decode(r)
                "dst_addr" -> dstAddrVal = AddrCodec.decode(r)
                "distance" -> distanceVal = r.readFloat64()
                "duration" -> durationVal = r.readFloat64()
                else -> r.skip()
            }
        }
        r.endObject()
        Mix15(srcAddr = srcAddrVal!!, dstAddr = dstAddrVal!!, distance = distanceVal, duration = durationVal)
    }
)

data class AllOpt1(
    val a: String? = null,
    val b: Int? = null,
    val c: Boolean? = null,
)

fun writeAllOpt1(w: SpecWriter, obj: AllOpt1) {
    var fieldCount = 0
    if (obj.a != null) fieldCount++
    if (obj.b != null) fieldCount++
    if (obj.c != null) fieldCount++
    w.beginObject(fieldCount)
    if (obj.a != null) { w.writeField("a"); w.writeString(obj.a) }
    if (obj.b != null) { w.writeField("b"); w.writeInt32(obj.b) }
    if (obj.c != null) { w.writeField("c"); w.writeBool(obj.c) }
    w.endObject()
}

val AllOpt1Codec: SpecCodec<AllOpt1> = SpecCodec(
    encode = { w, obj -> writeAllOpt1(w, obj) },
    decode = { r ->
        var aVal: String? = null
        var bVal: Int? = null
        var cVal: Boolean? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readString()
                "b" -> bVal = r.readInt32()
                "c" -> cVal = r.readBool()
                else -> r.skip()
            }
        }
        r.endObject()
        AllOpt1(a = aVal, b = bVal, c = cVal)
    }
)

data class AllOpt2(
    val x: Double? = null,
    val y: ByteArray? = null,
    val z: Long? = null,
)

fun writeAllOpt2(w: SpecWriter, obj: AllOpt2) {
    var fieldCount = 0
    if (obj.x != null) fieldCount++
    if (obj.y != null) fieldCount++
    if (obj.z != null) fieldCount++
    w.beginObject(fieldCount)
    if (obj.x != null) { w.writeField("x"); w.writeFloat64(obj.x) }
    if (obj.y != null) { w.writeField("y"); w.writeBytes(obj.y) }
    if (obj.z != null) { w.writeField("z"); w.writeInt64(obj.z) }
    w.endObject()
}

val AllOpt2Codec: SpecCodec<AllOpt2> = SpecCodec(
    encode = { w, obj -> writeAllOpt2(w, obj) },
    decode = { r ->
        var xVal: Double? = null
        var yVal: ByteArray? = null
        var zVal: Long? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "x" -> xVal = r.readFloat64()
                "y" -> yVal = r.readBytes()
                "z" -> zVal = r.readInt64()
                else -> r.skip()
            }
        }
        r.endObject()
        AllOpt2(x = xVal, y = yVal, z = zVal)
    }
)

data class AllOpt3(
    val name: String? = null,
    val age: Int? = null,
    val score: Double? = null,
    val active: Boolean? = null,
)

fun writeAllOpt3(w: SpecWriter, obj: AllOpt3) {
    var fieldCount = 0
    if (obj.name != null) fieldCount++
    if (obj.age != null) fieldCount++
    if (obj.score != null) fieldCount++
    if (obj.active != null) fieldCount++
    w.beginObject(fieldCount)
    if (obj.name != null) { w.writeField("name"); w.writeString(obj.name) }
    if (obj.age != null) { w.writeField("age"); w.writeInt32(obj.age) }
    if (obj.score != null) { w.writeField("score"); w.writeFloat64(obj.score) }
    if (obj.active != null) { w.writeField("active"); w.writeBool(obj.active) }
    w.endObject()
}

val AllOpt3Codec: SpecCodec<AllOpt3> = SpecCodec(
    encode = { w, obj -> writeAllOpt3(w, obj) },
    decode = { r ->
        var nameVal: String? = null
        var ageVal: Int? = null
        var scoreVal: Double? = null
        var activeVal: Boolean? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "name" -> nameVal = r.readString()
                "age" -> ageVal = r.readInt32()
                "score" -> scoreVal = r.readFloat64()
                "active" -> activeVal = r.readBool()
                else -> r.skip()
            }
        }
        r.endObject()
        AllOpt3(name = nameVal, age = ageVal, score = scoreVal, active = activeVal)
    }
)

data class AllOpt4(
    val a: UInt? = null,
    val b: ULong? = null,
    val c: Int? = null,
    val d: String? = null,
    val e: ByteArray? = null,
)

fun writeAllOpt4(w: SpecWriter, obj: AllOpt4) {
    var fieldCount = 0
    if (obj.a != null) fieldCount++
    if (obj.b != null) fieldCount++
    if (obj.c != null) fieldCount++
    if (obj.d != null) fieldCount++
    if (obj.e != null) fieldCount++
    w.beginObject(fieldCount)
    if (obj.a != null) { w.writeField("a"); w.writeUint32(obj.a) }
    if (obj.b != null) { w.writeField("b"); w.writeUint64(obj.b) }
    if (obj.c != null) { w.writeField("c"); w.writeInt32(obj.c) }
    if (obj.d != null) { w.writeField("d"); w.writeString(obj.d) }
    if (obj.e != null) { w.writeField("e"); w.writeBytes(obj.e) }
    w.endObject()
}

val AllOpt4Codec: SpecCodec<AllOpt4> = SpecCodec(
    encode = { w, obj -> writeAllOpt4(w, obj) },
    decode = { r ->
        var aVal: UInt? = null
        var bVal: ULong? = null
        var cVal: Int? = null
        var dVal: String? = null
        var eVal: ByteArray? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "a" -> aVal = r.readUint32()
                "b" -> bVal = r.readUint64()
                "c" -> cVal = r.readInt32()
                "d" -> dVal = r.readString()
                "e" -> eVal = r.readBytes()
                else -> r.skip()
            }
        }
        r.endObject()
        AllOpt4(a = aVal, b = bVal, c = cVal, d = dVal, e = eVal)
    }
)

data class AllOpt5(
    val p: Inner? = null,
    val q: String? = null,
)

fun writeAllOpt5(w: SpecWriter, obj: AllOpt5) {
    var fieldCount = 0
    if (obj.p != null) fieldCount++
    if (obj.q != null) fieldCount++
    w.beginObject(fieldCount)
    if (obj.p != null) { w.writeField("p"); writeInner(w, obj.p) }
    if (obj.q != null) { w.writeField("q"); w.writeString(obj.q) }
    w.endObject()
}

val AllOpt5Codec: SpecCodec<AllOpt5> = SpecCodec(
    encode = { w, obj -> writeAllOpt5(w, obj) },
    decode = { r ->
        var pVal: Inner? = null
        var qVal: String? = null
        r.beginObject()
        while (r.hasNextField()) {
            when (r.readFieldName()) {
                "p" -> pVal = if (r.isNull()) { r.readNull(); null } else { InnerCodec.decode(r) }
                "q" -> qVal = r.readString()
                else -> r.skip()
            }
        }
        r.endObject()
        AllOpt5(p = pVal, q = qVal)
    }
)
